### ISSUE TITLE
Making data less awful: the MIRO edition

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/platform#1126]
I'm finding more images from MIRO whose descriptions have unnecessary formatting, namely paragraph breaks and HTML tags.

Here are but two examples of para breaks:
https://wellcomecollection.org/works/xffza9xk
https://wellcomecollection.org/works/ergc92jn

And HTML:
https://wellcomecollection.org/works/enh3ywsj

**Comment by alexwlchan** [comment]
I think we could fix this with a couple of cheap heuristics:

* Remove newlines from any description where the maximum line length is lower than some sentinel value, say 50 – which we treat as an indication that artificial line breaks have been inserted.

* A regex that strips out HTML-like characters (probably `<[^>]+>`) from the descriptions.

Both may mangle the data more than they improve it, so I'd be reluctant to do it without a bit of poking around in the data to see what the effect might be.

**Comment by alexwlchan** [comment]
Wait, `<[^>]+>` might be a terrible regex. Because then `a < b and then a sentence follows >` would get swallowed, but that's not really regex.

WAH.

**Comment by pollecuttn** [comment]
I thought this was impossible? https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454

**Comment by alexwlchan** [comment]
We also have some Unicode issues which are persisting, e.g.: https://api.wellcomecollection.org/catalogue/v1/works/b2djs79x

**Comment by jennpb** [comment]
No need to resolve this now
