### ISSUE TITLE
Updating a record in vhs should not require decoding the previously stored version

### ISSUE THREAD

**Issue by alicefuzier** [wellcomecollection/platform#2339]
The `updateRecord` method in vhs always decodes the thing stored in S3 if a previous version of it exists. This causes the recorder to fail when we change the internal model if there's stuff in an older format in VHS, forcing us to clear it before running a reindex. This has a knock-on effect on the rest of the pipeline because it means that, to have a clean reindex, we also have to clean the matcher graph table

**Comment by alexwlchan** [comment]
I'm going to close this for now; it's been two and a half years and we've not fixed this.

It's substantially cheaper and easier to create new pipelines now for model changes, and the recorder no longer exists. We can revisit it if it's still an issue.
