### ISSUE TITLE
Migrate the catalogue API to use Typesafe config

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#3051]

**Comment by kenoir** [comment]
Closing as done.

**Comment by alexwlchan** [comment]
Reopening, it's not: https://github.com/wellcometrust/catalogue/blob/master/api/api/src/main/scala/uk/ac/wellcome/platform/api/modules/ApiConfigModule.scala

**Comment by alexwlchan** [comment]
Done now.
