### ISSUE TITLE
Check Miro text encoding issues

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#3152]
There are still some text encoding issues with the Miro data, eg:

https://api.wellcomecollection.org/catalogue/v2/works/v8u8haeq

Can we take a look and see if there's an obvious fix?

**Comment by pollecuttn** [comment]
I think there are similar examples on https://github.com/wellcometrust/wellcomecollection.org/issues/2185

**Comment by alexwlchan** [comment]
Certainly; and we’ve got a pretty robust mechanism for editing Miro data now.

**Comment by alexwlchan** [comment]
v8u8haeq looks like we're not decoding from UTF-8 correctly? Hmm…

**Comment by alexwlchan** [comment]
I think this is fixed in the transformer, but it isn't reflected in yesterday's data. I'm not sure why.

**Comment by alexwlchan** [comment]
This looks like it's fixed now, at least on the front-end (if you go to the API in your web browser, the characters may look funky if it's not decoding UTF-8 correctly).

Closing as done; we can open new tickets if we find other issues.
