### ISSUE TITLE
Make Post to Slack less chatty

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#3492]
Next time it wakes up, we want to do something like the following:

1. Have it record the message it's about to send to S3
2. If it last sent the message less than 12 hours ago, *don't send it again*

Long-term that whole hack is coming out and being replaced by a proper monitoring framework, but that's a short-term kludge to make it less repetitive.

**Comment by jamesgorrie** [comment]
> a proper monitoring framework

What's the current conversations on this?

**Comment by alexwlchan** [comment]
> What's the current conversations on this?

It's a thing we need to talk about, but haven't discussed in detail yet.
