### ISSUE TITLE
Update to contributor data SBA

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#3523]
Alexandra reported incorrect contributor data

Please make the change at https://github.com/wellcometrust/catalogue/blob/master/pipeline/transformer/transformer_miro/src/main/resources/miro_contributor_map.json#L822

From: `"SBA" : "St Bartholomew's Hospital Archives & Museum, Wellcome Collection",`
To: `"SBA" : "St Bartholomew's Hospital Archives & Museum",`

and reindex

**Comment by pollecuttn** [comment]
@mklander @jamesgorrie Checking this after the reindex one record, https://wellcomecollection.org/works/q9zx9z5d, still has the incorrect contributor data of 'St Bartholomew's Hospital Archives & Museum, Wellcome Collection' - you can see this by searching for that string: https://wellcomecollection.org/works?query=%22St%20Bartholomew%27s%20Hospital%20Archives%20%26%20Museum%2C%20Wellcome%20Collection%22

Can you please see what's happened and correct it. And then is reindexing just for this one record a bit much or okay, just to get it done?

**Comment by alexwlchan** [comment]
The contributor code "SBA" does not appear anywhere in the Miro record for q9zx9z5d, so that's why the change hasn't affected it!

**Comment by alexwlchan** [comment]
We did this.
