### ISSUE TITLE
Improve our build system Terraform, a wish list

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#3529]
- [ ] Double-check the permissions we’re granting everything, and tighten them up (e.g. we don't really need `ecr:*`).
- [ ] Give the secrets_*.zip files more consistent names.
- [ ] Don't actually embed the PyPI password in the zipfile; put it in SSM and teach the build tooling to read it out of SSM. Get it out of our Terraform state.

- [ ] Currently it creates a new user for each repo, and sticks it in the appropriate account (workflow, storage, etc.). We should use the same model we do for developer accounts: create a single user in the root account, then create roles that they can assume. The side-benefit is that it becomes easier to debug Travis issues, as we can assume those roles ourselves without the credentials.

**Comment by jamesgorrie** [comment]
> create a single user in the root account

@kenoir and I were talking about this, and it would be good to get the same configuration for the @wellcometrust/experience-devs too.

We were talking about keeping the users in a non-platform account (potentially the root account, but not necessarily as we might have a root / billing, user, and service accounts).

There was also talk of potentially setting up [federated users](https://aws.amazon.com/identity/federation/), but not sure how much time I would like to spend working with [AD](https://aws.amazon.com/directoryservice/).

**Comment by alexwlchan** [comment]
Closing as outdated – now we use BuildKite, our approach to secrets in CI is very different.
