### ISSUE TITLE
Square the Archivematica cost circle

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#3539]
Right now Archivematica is running on a c5.4xlarge instance, which costs ~$0.77/hr, or ~$550/month. That seems expensive!

We have a couple of seemingly immutable truths:

* We want to run all the Archivematica tasks on the same instance, or we get weirdness when changes to EFS appear to apply inconsistently across different instances
* We need the dashboard and storage service to run in separate tasks, so they can connect to different ALBs
* That gives us at least three tasks each of which uses a single ENI, and the smallest instance with at least four ENIs (dashboard, storage service, everything else, plus one spare for deployments) is a c5.4xlarge. They each need their own ENI because they're using the awsvpc networking mode for service discovery.

Possibly something with bridge networking would work? But I've been back and forth a bunch of times and I can't see how to get it working and not break Archivematica connectivity.

**Comment by jtweed** [comment]
We can also look at a reserved instance if that makes this easier, it will halve the cost.

**Comment by alexwlchan** [comment]
I'd like to get Robert's take on this next week; I'm sure it can be cheaper, I just need somebody with more AWS networking knowledge!
