### ISSUE TITLE
Re-upload metadata for non-historical Miro images in Tandem Vault

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#3551]
We when loaded non-historical images from Miro into Tandem Vault, we missed a couple of fields in the metadata we put in the description field.

We need to add:

- creator name
- contributor name
- contributor code

We can overwrite existing metadata in Tandem Vault.

**Comment by alexwlchan** [comment]
Closing as stale; I have a vague memory of us doing this and if we didn't it clearly wasn't a big deal. (Tandem Vault isn't even a thing any more!)
