### ISSUE TITLE
Manage the wellcomecollection.org DNS in Terraform

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#3604]
* [x] Certs
* [ ] Storage service
* [ ] Catalogue
* [ ] Workflow
* [ ] Experience team

**Comment by kenoir** [comment]
Pinging @jamesgorrie - in stacks trying an approach where state is _not_ unified but we only manage the entries we are interested in.

**Comment by alexwlchan** [comment]
> trying an approach where state is not unified but we only manage the entries we are interested in

This is what we do now. Closing as done.
