### ISSUE TITLE
Set up users in Archivematica terraform

### ISSUE THREAD

**Issue by helenst** [wellcomecollection/platform#3676]
Currently, the terraform config for Archivematica does not set up a user in the dashboard or storage service. This means they have to be set up manually and API keys entered to cross-authenticate between the two. It also now means the username/authentication keys will need to be manually added for the S3 start-transfer lambda developed in #3555

The dashboard provides an `install` command for setting up an initial user (in the `installer` app) and storage service has a `create_user` command in the `common` app.

Will need #3471 to be sorted first

**Comment by alexwlchan** [comment]
We have users set up, although they’re managed in Archivematica rather than Terraform.
