### ISSUE TITLE
Lowercase and asciifold keyword fields in Elastic

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#3682]
When searching for `v{insert sierra ID}` we get nothing, but searching for `V{insert sierra ID}` we get results.

You can use normalisers which normalise the data at index and query time, I haven't read a huge amount about them, but initially see no down side.

https://www.elastic.co/guide/en/elasticsearch/reference/6.4/normalizer.html

e.g.
https://wellcomecollection.org/works?query=V0004569ER
https://wellcomecollection.org/works?query=v0004569ER

**Comment by alexwlchan** [comment]
If you try these queries now, you get the correct result – I believe we're copying all the identifiers into an `identifiers` field, which has a lowercase keyword analyser.

Also, these are Miro IDs, not Sierra IDs.
