### ISSUE TITLE
Use Elastic index aliases to make index switching easier

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#3761]
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

Might be worth talking about how we move from prod / staging and avoid breaking things.

Indexes can store information with it in metadata.

You could also store what model version we used to create something, and thus know what version to take it out with.

**Comment by alexwlchan** [comment]
Closing as stale; the way we manage indexes now means this is mostly unnecessary. When this ticket was written, we had a single API cluster with all our indexes; now we have a separate cluster per pipeline.
