### ISSUE TITLE
Document using Terraform to do cross-account bucket permissions

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#3795]

**Comment by jamesgorrie** [comment]
https://github.com/wellcometrust/wellcomecollection-data-science/pull/4

https://github.com/wellcometrust/reporting/blob/61c76aa5246d5c3f204bd3710fcdf54663bc4478/terraform/locals.tf#L12

https://github.com/wellcometrust/platform/pull/3639

Places we do something similar, might be worth finding _a_ way to do it.

**Comment by kenoir** [comment]
Closing as not_actionable_as_is.
