### ISSUE TITLE
Sort out proper roles for CI users

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#3806]
Todo: 
- [x] Add a CI role assumed by Travis to carry out CI operations
- Ensure all operations are covered:
  - [x] Write to SSM
  - [x] Update dynamo
  - [x] Force redeploy to ECS
- [x] Clean up existing policies attached to 
- [x] Ensure "read-only" assume role forlocal can be removed from build.sbt in all projects

**Comment by kenoir** [comment]
This is clearly needed - overzelous closing. Re-opening.

**Comment by kenoir** [comment]
Closing as done.
