### ISSUE TITLE
Use new messaging libraries in the catalogue

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#3819]
Libraries:

- [x] internal_model
- [x] display
- [x] elasticsearch
- [x] big_messaging

Pipeline:
- [x] reindex_worker
- [x] id_minter
- [x] ingestor
- [x] matcher
- [x] merger
- [x] recorder
- [x] transformer_miro
- [x] transformer_sierra

API:
- [x] api
- [ ] snapshot_generator

Adapters:
- [ ] goobi_reader
- [ ] sierra_reader
- [ ] sierra_bib_merger
- [ ] sierra_item_merger
- [ ] sierra_items_to_dynamo

## Summary of inputs / outputs of services
`=>` publishes this type of data

Adapter => HybridStoreEntry
Transformer => BigMessaging
Recorder writes to VHS => Location
Matcher => SpecialMatcherMergerLanguage
Merger => BigMessaging
Ingestor => ElasticSearch

**Comment by alexwlchan** [comment]
FYI, new storage libraries are a much bigger disruption than messaging

**Comment by alexwlchan** [comment]
Closing as outdated, and probably done.
