### ISSUE TITLE
Terraform modules upgrade to post 0.12

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#3820]
In order to make use of the latest terraform features and stay in sync with d&t we need to update our terraform modules repo to post 0.12.

**Comment by jamesgorrie** [comment]
@alexwlchan @jamieparkinson @alicefuzier 

A few options I can think of this:

### Clean slate
We create a new version with nothing in it (or 1 module say) in 0.12. We no longer write 0.11 as terraform-modules@20 would be the starting point.

[There is a way to plan this by using remote state of older versions of infra](https://www.terraform.io/upgrade-guides/0-12.html#remote-state-references) (I think). So you could have in your project:
```
terraform/
├── 11/
│   └── old_modules.tf
└── 12/
    └── new_modules.tf
```

__Pros__:
- Forced to start writing everything in 0.12
- infrastructure upgrade becomes part of the day to day

__Cons__:
- It becomes very hard if we need to start modifying current infrastructure (not that hard)
- Potentially hard to keep in your head what's going on
- Maybe hard to reference old modules to see what was going on, but GH tags helps with that.

### New repo
Start again. New repo.

__Pros__:
- Can continue to add to old modules

__Cons__:
- Choosing to keep adding to old modules as it's more convenient.

## Have a multi-versioned repo

You could split the current repo into `/0.11/modules` & `/0.12/modules`.

__Pros:__
- can keep maintaining old modules
- can get a move on with new modules

__Cons:__

Given that with all versions, you are almost definitely going to hit

**Comment by jamesgorrie** [comment]
On another note - as part of this, it might be good to talk about the versionsing too - as knowing what latest of a module is, and what might have changed over time is very very hard.

**Comment by jamesgorrie** [comment]
As a quick test - you can't easily share state between versions... Bah.

**Comment by alexwlchan** [comment]
I don't think it's that disruptive a change – you can see the changes I've made to get the storage-service working here: https://github.com/wellcometrust/terraform-modules/pull/173

There's definitely room to improve the way we version terraform-modules – semver doesn't make sense on a global basis. I've considered versioning each module/directory individually, but never quite got around to it. But that's a bigger discussion than the 0.12 upgrade.

**Comment by jamesgorrie** [comment]
@alexwlchan so in that change is the idea that the module will support both 11 and 12?

**Comment by alexwlchan** [comment]
Very much hoping so!

It looks like I might need some breaking changes; going to play a bit and see how it goes.

**Comment by alexwlchan** [comment]
I think we should consider breaking up the terraform-modules repo into separate pieces.

**Comment by jamieparkinson** [comment]
@alexwlchan @jamesgorrie shall we have a chat about this this morning? Currently working on a load of TF changes for the catalogue API and would like to avoid aiming at a moving target

**Comment by jamieparkinson** [comment]
fwiw I like this idea
> I've considered versioning each module/directory individually, but never quite got around to it.

**Comment by alexwlchan** [comment]
I'm not in until this afternoon, but yes, let's chat when I'm in.

**Comment by kenoir** [comment]
Closing this as I think it's done!
