### ISSUE TITLE
VersionedStore.update should catch exceptions from user function & wrap as Left

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#3840]
It would also be nice for users to say that an update is not allowed e.g. `UpdateNotAllowed extends UpdateError`.

Now: `def update(id: Id)(f: T => T)`
Better `def update(id: Id)(f: T => Either[UpdateNotAllowed[UserDefinedError], T])`

The user can then tell us _why_ that update is not allowed.

**Comment by alexwlchan** [comment]
Done.
