### ISSUE TITLE
LockingService should maybe not be tied to single output type

### ISSUE THREAD

**Issue by warrd** [wellcomecollection/platform#3873]
The original`DynamoLockingService` allowed callbacks to return arbitrary types, as the `withLocks` method itself was parameterised by some `T` (see [here](https://github.com/wellcometrust/scala-storage/blob/0a6128d5d20096246467b533f4a581f51518eab3/storage/src/main/scala/uk/ac/wellcome/storage/locking/DynamoLockingService.scala#L20))

The new `LockingService` is tied to a single `Out` type (see [here](https://github.com/wellcometrust/scala-storage/blob/master/storage/src/main/scala/uk/ac/wellcome/storage/locking/LockingService.scala#L9))

I have had to do a bit of a hack to get round this when moving to the new storage lib in the [`matcher`](https://github.com/wellcometrust/catalogue/pull/153/files)

**Comment by alexwlchan** [comment]
Closing as not planned; this hasn't been a major issue in the last four years and is unlikely to become more pressing as we're not using this code in new places.
