### ISSUE TITLE
Expose query parameters via API so clients can react to them

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#3893]
As an example #3891 
- Include min/max values for pageSize in the Swagger response for the catalogue API
- Expose valid values for aggregations and includes
- Expose type of parameter e.g. iso date for `_dateFrom`

**Comment by alexwlchan** [comment]
min/max values for pageSize: https://github.com/wellcomecollection/catalogue/pull/904

**Comment by alexwlchan** [comment]
Closing as stale.
