### ISSUE TITLE
Move Wellcome Collection projects to wellcomecollection Github org

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#3989]
Wellcome Collection has a Github Org: https://github.com/wellcomecollection

## Moved
- [x] https://github.com/wellcometrust/wellcomeplayer-pdf-extension
- [x] https://github.com/wellcometrust/wellcomeplayer-dialogues-module
- [x] https://github.com/wellcometrust/wellcomeplayer-seadragon-extension
- [x] https://github.com/wellcometrust/wellcomeplayer-seadragoncenterpanel-module
- [x] https://github.com/wellcometrust/wellcomeplayer-treeviewleftpanel-module
- [x] https://github.com/wellcometrust/wellcomeplayer-searchfooterpanel-module
- [x] https://github.com/wellcometrust/wellcomeplayer-extendedfooterpanel-module
- [x] https://github.com/wellcometrust/wellcomeplayer-moreinforightpanel-module
- [x] https://github.com/wellcometrust/wellcomeplayer-shared-module
- [x] https://github.com/wellcometrust/wellcomeplayer-mediaelement-extension
- [x] https://github.com/wellcometrust/alpha (should be public wellcometrust/platform#3989)
- [x] https://github.com/wellcometrust/catalogue
- [x] https://github.com/wellcometrust/platform
- [x] https://github.com/wellcometrust/wellcomecollection.org
- [x] https://github.com/wellcometrust/dockerfiles
- [x] https://github.com/wellcometrust/docker_run
- [x] https://github.com/wellcometrust/prismic-remapper
- [x] https://github.com/wellcometrust/storage-service
- [x] https://github.com/wellcometrust/tzitzit
- [x] https://github.com/wellcometrust/archivematica
- [x] https://github.com/wellcometrust/archivematica-docs
- [x] https://github.com/wellcometrust/archivematica-storage-service
- [x] https://github.com/wellcometrust/loris
- [x] https://github.com/wellcometrust/python-gearman
- [x] https://github.com/wellcometrust/scala-fixtures
- [x] https://github.com/wellcometrust/scala-json
- [x] https://github.com/wellcometrust/scala-messaging
- [x] https://github.com/wellcometrust/scala-monitoring
- [x] https://github.com/wellcometrust/scala-storage
- [x] https://github.com/wellcometrust/wellcome-collection-tei
- [x] https://github.com/wellcometrust/wellcome-typesafe-app
- [x] https://github.com/wellcometrust/workflow
- [x] https://github.com/wellcometrust/sierra-streams-source

## Archived / Deleted
- [x] https://github.com/wellcometrust/annotated-viewer (deleted)
- [x] https://github.com/wellcometrust/aws-azure-login (deleted)
- [x] https://github.com/wellcometrust/aws_utils (archived)
- [x] https://github.com/wellcometrust/chemist-and-druggist-dataweek (archived)
- [x] https://github.com/wellcometrust/collection (archived)
- [x] https://github.com/wellcometrust/data-for-data-science (deleted)
- [x] https://github.com/wellcometrust/dotorg-dash (deleted)
- [x] https://github.com/wellcometrust/feature-flags  (deleted)
- [x] https://github.com/wellcometrust/iiif-features  (deleted)
- [x] https://github.com/wellcometrust/iiif-manifests (archived)
- [x] https://github.com/wellcometrust/loris-docker (deleted)
- [x] https://github.com/wellcometrust/parser_test (deleted)
- [x] https://github.com/wellcometrust/platform-cli (deleted)
- [x] https://github.com/wellcometrust/platform-developer-docs (archived)
- [x] https://github.com/wellcometrust/platform-makefiles (archived)
- [x] https://github.com/wellcometrust/player (archived)
- [x] https://github.com/wellcometrust/requests (deleted)
- [x] https://github.com/wellcometrust/terraform-modules (archived)
- [x] https://github.com/wellcometrust/toggler (deleted)
- [x] https://github.com/wellcometrust/universalviewer (archived)
- [x] https://github.com/wellcometrust/universalviewer.github.io  (archived)
- [x] https://github.com/wellcometrust/uv-cy-GB-theme  (archived)
- [x] https://github.com/wellcometrust/uv-en-GB-theme  (archived)
- [x] https://github.com/wellcometrust/wecobot (deleted)
- [x] https://github.com/wellcometrust/wellcomeBDD (archived)
- [x] https://github.com/wellcometrust/timeline (archived)
- [x] https://github.com/wellcometrust/womens-work (archived)
- [x] https://github.com/wellcometrust/drink (archived)
- [x] https://github.com/wellcometrust/configuration (archived)
- [x] https://github.com/wellcometrust/whos-the-pest (archived)
- [x] https://github.com/wellcometrust/wellcomecollection-dns-infra (archived)

See https://github.com/wellcometrust/platform-private/issues/62 for private repos.

Migrating a repo includes:

* Transferring it across, or deleting it if no longer needed
* Setting up permissions for anybody who needs access to it
* Setting up CI in the new organisation

Projects should be transitioned to the new organisation when possible - this includes repos in https://github.com/wellcomelibrary.

**Comment by jennpb** [comment]
This one too, please; and make it public! https://github.com/wellcometrust/alpha
