### ISSUE TITLE
add deeper conversion data to search tracking

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/platform#4005]
In addition to tracking searches and result clicks, we should start thinking about what deeper engagement with works might look like, ie tracking users' engagements with the viewer or item downloads. This still contributes to our list of implicit metrics, not explicit ones, but gives us insight into more of the user journey

**Comment by jamesgorrie** [comment]
Ping @taceybadgerbrook @jennpb as this has already had thinking one when setting up GA and goals.

**Comment by jtweed** [comment]
To expand on the above, let's add Segment to the works pages so that we can track the following:

- Search conversion, defined as a search that leads to a digitised view, item request (current proxy for that is the wl.org link), click on the collections tree (where available), click on the "images from this work"
- Work page views, so that Tacey can look at #4547 

cc @jennpb in case she has any other ideas for what should be considered a conversion.

**Comment by jennpb** [comment]
Other conversions:
- Download hi/lo res JPEG
- Download PDF
- click on the CTA for 3rd party resource (when available)

(I think of these conversions as being the equivalent of taking something off a bookshelf to consult)

Question: how tied to a specific UI or button does the conversion tracking need to be? Where we might want to improve the UI in future, for example for the related/featured images from a work, is the tracking UI-agnostic?

**Comment by jtweed** [comment]
Thanks @jennpb - agree with all of those.

I think we should try to define these as events that named as per what they are, rather than exactly what they are currently connected to, in an attempt to do exactly as you suggest and not tie them too closely to current UX.

**Comment by taceybadgerbrook** [comment]
Can I clarify these?

digitised view = views pages of book or image
item request (current proxy for that is the wl.org link) = uses online requesting service
click on the collections tree (where available) = navigates tree structure for archive
click on the "images from this work" = feature not yet available

**Comment by jtweed** [comment]
Those three are correct @taceybadgerbrook

**Comment by taceybadgerbrook** [comment]
I think we could define conversion as the following events:

VIEW
- view book/image in catalogue
- view book/image via archive tree
- view image in images API
- view via 3rd party resource

PLAY
- video
- audio

DOWNLOAD
- image (high/low resolution)
- book (pdf)
- video
- audio

REQUEST
- successfully places order online

**Comment by jtweed** [comment]
With that breakdown, which is definitely tilting in the right direction, is there really a difference between view and play? I'm not sure there is, because a play is just a view of video.

**Comment by jennpb** [comment]
Are we interested in an equivalent to a text-based 'reading time'? If so, I can see the value in having Play as a separate metric. We could potentially calculate time spent viewing/listening based on duration. But that might be too granular and overkill.

Another area where the specificity isn't needed is in the VIEW grouping
- view book/image in catalogue
- view book/image via archive tree

They're all digitised items, it doesn't matter where on the page the view button is, whether it's accessible on a work page, or in an archive tree (indeed, at the moment, the digitised item isn't available from the archive tree at all, nor do I think it would be). IMO this should just be:
View:
- Viewed `item` with `digitalLocation` on wellcomecollection.org

**Comment by taceybadgerbrook** [comment]
I think generalising view as a digital location conversion makes sense.

Play could come under the same heading as view. Users engage with audio or video files by playing them, similar to people viewing books or images.

**Comment by jtweed** [comment]
Just to note what I said in the call just now, I think there is probably a separate play/reading time metric, that is more of a metric for the works page rather than search. Ie, the search journey ends when you view, how long you view is not part of the search journey.

**Comment by jennpb** [comment]
Agreed. Any 'play time', like our text-based 'reading time' metric should be tracked from the front end, if we choose to track it as part of our engagement metrics.

**Comment by taceybadgerbrook** [comment]
@jamesgorrie, I'm interested in discussing the specific criteria for conversions because it's possible to clock up lots of Views in quick succession without deriving much benefit from this activity. You can do this with image search views, too.

**Comment by jamesgorrie** [comment]
> @jamesgorrie, I'm interested in discussing the specific criteria for conversions because it's possible to clock up lots of Views in quick succession without deriving much benefit from this activity. You can do this with image search views, too.

As discussed on Slack, we aren't going to assume intent from this behaviour.

**Comment by taceybadgerbrook** [comment]
Conversion rates require 2 pieces of data, otherwise they are just counts.  Below are analysis questions about conversion that we should be able to answer and the data needed to answer these questions:

![image](https://user-images.githubusercontent.com/32418070/98973058-2a54ca80-250b-11eb-9e80-744b23118b7b.png)

**Comment by taceybadgerbrook** [comment]
@jtweed It's certainly more useful to express conversion in terms of a funnel so that we can spot where user get "stuck." James has said that conversions will be left to me to calculate (ie data is not going to be transformed to produce a field called, "Converted"), so I'm happy to investigate how to create something funnel-like in the dashboard.

If I have to produce a conversion rate for tracking or reporting purposes, this is a different matter. I can only create a rate out of 2 two numbers.

**Comment by taceybadgerbrook** [comment]
@jamesgorrie Could you include data.source in the new search index? This would allow filtering for users coming in from search engines and also identify archive tree navigation clicks (event:Search result selected & data.source:archive)

**Comment by taceybadgerbrook** [comment]
@jennpb Here is a link to the revised conversion definitions:
https://docs.google.com/document/d/1Hs1gm5ztCG88yDg_9PsT6hKPPSvK4KtbwzUJxZ6fHyg/edit

![image](https://user-images.githubusercontent.com/32418070/99787368-8de88480-2b17-11eb-9fb9-ed8ef77dd28b.png)

**Comment by taceybadgerbrook** [comment]
These revisions are in response to comments in 
https://wellcomecloud-my.sharepoint.com/:w:/g/personal/j_phillips-bacher_wellcome_ac_uk/EcoMXJuvFhVCseTxjuIYiSIBzzLup7Igo2cD6wB4s-HSng?e=FP7ZuO

I've changed things and provided more description but happy to revise/discuss if I've misinterpreted your comments.

**Comment by jennpb** [comment]
One final question - what's the rationale for using views/searches on the second row, but requests/works accessed in the third row? 

To me, given that you've already accounted for searches and click-through in the 'find what they're looking for' in the first conversion, the second two are both about access, really. The second row being 'accessed and used a digital item' and the third row being 'accessed and used a physical item'.

**Comment by taceybadgerbrook** [comment]
I've included the third row (users are more able to access the physical collection) so that we can track how this service works over time but it doesn't have to be a permanent part of the search dashboard. I can remove it.

**Comment by jennpb** [comment]
My opinions, though feel free to disregard, rows 2 + 3 are the same: 
Are users using more of what we offer?
Data comes from: 

- Views of digitised material
- Downloads of digitised material
- Clicks through to 3rd party online resources
- Requests of physical material

So is the conversion about Events/Total number of workPages accessed?

**Comment by taceybadgerbrook** [comment]
On the basis that usage is usage, it makes sense to evaluate online requesting wrt search. 

I should add that in addition to conversions, the search dashboard will also report headline figures, eg searches and views and so will include online requests.
