### ISSUE TITLE
Use nested fields for relevant objects

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#4134]
- Subjects
- Genres
- Agents
- Concepts?

* Ensure strict mapping is set on all
* From Person => Works:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-reverse-nested-aggregation.html

**Comment by alexwlchan** [comment]
Closing as stale; we've pretty extensively reworked the index structure recently and nothing from that needed nested fields.
