### ISSUE TITLE
Be more explicit about fields included in index

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#4136]
[We currently only query certain fields](https://github.com/wellcometrust/catalogue/blob/master/api/api/src/main/scala/uk/ac/wellcome/platform/api/services/ElasticsearchQueryBuilder.scala) we should be more explicit about which of these are included in the index mapping.

https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html

Use `dynamic:false`.

**Comment by alexwlchan** [comment]
Closing as done, as part of the index restructure.
