### ISSUE TITLE
Use .keyword not .raw for keyword fields

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#4142]
We use `.raw` to indicate that we are storing the keyword along with text and other data.

This should probably be called `.keyword`.

https://github.com/wellcometrust/catalogue/blob/master/common/elasticsearch/src/main/scala/uk/ac/wellcome/elasticsearch/WorksIndex.scala#L7

**Comment by alexwlchan** [comment]
Done: https://github.com/wellcomecollection/catalogue/blob/085e4dcb24da95475b6b40ad4e764f83cdda7abf/common/elasticsearch/src/main/scala/uk/ac/wellcome/elasticsearch/IndexConfig.scala#L28
