### ISSUE TITLE
Look at using Rank Evaluation for testing search

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4143]
In order to ensure quality of search results look at using Rank Evaluation for testing relevancy of search results to known queries.

Rank Evaluation allows you to evaluate the effectiveness of a query against some expected result.

See:
- https://www.elastic.co/guide/en/elasticsearch/reference/current/search-rank-eval.html
- https://www.elastic.co/blog/test-driven-relevance-tuning-of-elasticsearch-using-the-ranking-evaluation-api

**Comment by alexwlchan** [comment]
Closing as “yeah, we did this 😎”
