### ISSUE TITLE
Diagnose cause and re-enable Loris 4xx alarm

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/platform#4170]
https://github.com/wellcometrust/platform/pull/4169 disabled the 4xx alarm for Loris because it was being loud - we should figure out what was causing all of these errors and if/when we fix that root cause, the alarm should be re-enabled.

**Comment by alexwlchan** [comment]
Closes by https://github.com/wellcomecollection/platform/issues/4884
