### ISSUE TITLE
Continued improvement to search relevance

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4172]
### Objective

Researchers find more of what they're looking for

### Measures

- Are we returning better results for more queries?
- Can users find both physical and digitised items via search?

### Initiatives

- [ ] Add conversion metrics to search tracking
- [ ] Filter by license and availability location
- [ ] Ongoing AB tests to improve search relevance
- [ ] Return all work types in search by default

**Comment by jamesgorrie** [comment]
>  Return all work types in search by default

🌟 ✨ 🚀

**Comment by jtweed** [comment]
Superseded
