### ISSUE TITLE
Rebase Archivematica forks to latest core versions

### ISSUE THREAD

**Issue by helenst** [wellcomecollection/platform#4175]
We've had several pull requests merged into Archivematica in the last few months, and there have been many other changes to the core repository in that time.

Our branches should be updated to bring them closer to the core repository. I suggest creating separate rebased branches which can be deployed to staging to be tested.

- [x] Rebase archivematica
- [x] Rebase storage service

**Comment by ross-spencer** [comment]
👋 spotted this ticket being logged and just thought I'd say as y'all test, keep an eye on some of the ones with red labels that are milestoned: [here](https://github.com/archivematica/issues/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.11.0) or those marked for triage [here](https://github.com/archivematica/issues/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone+label%3Atriage-release-1.11) as they'll likely represent some bugs or regressions that we're picking through prior to the `1.11` release which I believe we're still anticipating in February.

**Comment by helenst** [comment]
Rebased branches (named `wellcome-storage-service-rebase` in both repos) are passing tests.

Still TODO:
- [ ] make sure `ensure_bucket_exists` works with our AWS setup (this may involve patching the way _ensure_bucket_exists() so it doesn't fail if the bucket is owned by another user - see https://github.com/artefactual/archivematica-storage-service/pull/497#issuecomment-566999265)
- [ ] Document what needs to be done to existing installs to fix up migrations. We developed wellcome plugin first, and then additions to S3. But now s3 additions are in the core fork, and we need to apply wellcome plugin migrations after those. So migrations will be re-ordered in the rebase. There are also one or two differently named fields in the s3 plugin.
- [ ] ensure elasticsearch bulk indexing still works (https://github.com/wellcometrust/platform/issues/4092)
- [ ] test and look out for 1.11 bugs

**Comment by helenst** [comment]
I'm currently getting one test failure on mcp client, on `test_sanitize_transfer_with_multiple_files` and trying to identify what's broken this...

**Comment by alexwlchan** [comment]
Eek! I think we might have tweaked sanitise transfer in an attempt to make it go faster, so sounds plausible?

**Comment by helenst** [comment]
Hmm, may not be related (I think your sanitise changes are already in core) - also, I'm not getting reliable results from running the tests - sometimes I get multiple failures and sometimes it just passes :woman_facepalming:

Anyway, this is the error I sometimes get:
```
>       assert len(agents) == NUMBER_OF_EXPECTED_AGENTS, "Agents not all written for Event"      
E       AssertionError: Agents not all written for Event
E       assert 2 == 3
E         -2
E         +3   

tests/test_sanitize.py:187: AssertionError
```

**Comment by helenst** [comment]
I will ignore this for now and try focusing on the migrations instead!

**Comment by helenst** [comment]
I've fixed up the migrations so that field names won't change across the rebase.

The migrations diverge between the rebased and original branch at 0022 (which is the last migration in common). After that, the following migrations exist in the rebased branch:

```
0023_s3_bucket_field
0024_allow_blank_aws_auth
0025_update_package_size
0026_wellcome
0027_add_wellcome_callback_fields
0028_wellcome_blank_aws_auth
0029_auto_20200122_0726
```

All of these except `0025` are equivalent to migrations from the original branch. So the following commands should be run when the rebased branch is deployed:

```
python manage.py migrate --fake locations 0024
python manage.py migrate --fake locations 0025
python manage.py migrate --fake locations 0029

**Comment by helenst** [comment]
Error while testing zipfiles with special characters in compressed filenames:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 331, in _invoke_callbacks
    callback(self)
  File "/src/MCPServer/lib/server/queues.py", line 233, in _job_completed_callback
    next_job = future.result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 102, in inner
    _reraise(*exc)
  File "/usr/local/lib/python2.7/site-packages/contextdecorator.py", line 95, in inner
    result = f(*args, **kw)
  File "/src/MCPServer/lib/server/jobs/client.py", line 126, in run
    self.submit_tasks()
  File "/src/MCPServer/lib/server/jobs/client.py", line 238, in submit_tasks
    arguments = self.replace_values(self.arguments, command_replacements)
  File "/src/MCPServer/lib/server/jobs/client.py", line 104, in replace_values
    escaped_replacement = _escape_for_command_line(replacement)
  File "/src/MCPServer/lib/server/jobs/client.py", line 28, in _escape_for_command_line
    value = value.replace("\\", "\\\\")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 79: ordinal not in range(128)
```

**Comment by helenst** [comment]
Which is nothing in particular to do with zipfiles, but there does appear to be a problem with characters in filenames in this new branch.

I am testing with other zipfiles for now, which don't have special characters. All appears fine for transfer, ingest and create sip from appraisal. Also, transfer from S3 still works. Just need to check the wellcome storage plugin still works. :)

**Comment by alexwlchan** [comment]
^^ noting the migrations need to be run in the storage service, not dashboard
