### ISSUE TITLE
Image search with linked images and works

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4176]
### Objective

Researchers find more of what they're looking for

### Measures

- Are we using less data from Miro? 
- Can users find images that meet their requirements for use?

### Initiatives

- [x] Create images from Miro works related to Sierra
- [x] Create images from Miro works that are standalone
- [x] Create images from METS for visual Sierra works
- [x] Change image search to search images not works
- [x] Visual similarity working reliably for all images

**Comment by jamieparkinson** [comment]
## Merging / image generation rules:

- Sierra bib [workType=Pictures] + METS: 1 Work + `n` Images (`n = 1`)

- Sierra bib + Miro: 1 Work + `n` Images (`n = #{Miro images}`)

- Sierra bib + METS + Miro: 1 Work + `n` Images (`n = #{Miro images} + 1`)

- Miro: 1 Image

Where no. of METS images may really be `> 1` but we are currently only pulling through the first of these, currently used for creating the thumbnail.

**Comment by jtweed** [comment]
Superseded by #4638
