### ISSUE TITLE
Regular ingest of archive catalogue

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4177]
### Objective

Researchers find more of what they're looking for

### Measures

- Are updates coming being ingested from Calm?
- Is Calm data merged with Sierra?

### Initiatives

- [x] Ingest data from Calm
- [x] Transform data from calm
- [ ] Merge Calm data with Sierra data
- [ ] Add archive hierarchy to Catalogue API
- [ ] Display archive hierarchy on work pages

#### Transformer
<img width="1260" alt="Screenshot 2020-01-27 at 16 36 44" src="https://user-images.githubusercontent.com/31692/73193971-53929e80-4123-11ea-8944-a193ee2df532.png">

| API                                 | Calm                  |
|-------------------------------------|-----------------------|
| workType                            | Level                 |
| identifiers                         | RecordID                 |
| identifiers                         | RefNo                 |
| identifiers                         | AltRefNo              |
| identifiers                         | AccNo                 |
| identifiers                         | PreviousNumbers       |
| title                               | Title                 |
| contributors                        | CreatorName           |
| production                          | Date                  |
| language                            | Language              |
| arrangement                         | Arrangement           |
| physicalDescription                 | Extent                |
| physicalDescription                 | UserWrapped6          |
| subjects                            | Subject               |
| accessConditions.status             | AccessStatus          |
| accessConditions.terms              | AccessConditions      |
| accessConditions.to (if closed)     | ClosedUntil           |
| accessConditions.to (if restricted) | UserDate1             |
| notes (BiographicalNote)            | AdminHistory          |
| notes (ownership)                   | CustodHistory         |
| notes (acquisition)                 | Acquisition           |
| notes (appraisal)                   | Appraisal             |
| notes (accruals)                    | Accruals              |
| notes (related)                     | RelatedMaterial       |
| notes (PublicationsNote)            | PubInNote             |
| notes (finding-aids)                | UserWrapped4          |
| notes (CopyrightNote)               | Copyright             |
| notes (TermsOfUse)                  | RepoductionConditions |

[Archive => catalogue mapping (PDF)](https://github.com/wellcometrust/platform/files/4118156/archive.catalogue.mapping.pdf).

#### Merger
The entire record should come from Calm and only have the the Sierra ID attached.

#### Identifiers
- `RefNo` cannot be considered canonical to a record as they can be edited and on occasion is to restructure hierarchies. e.g.
  We want to add a record between `4` and `5`. Two methods are:
  ```
    - /PGN/PD/1
    - /PGN/PD/2
    - /PGN/PD/3
    - /PGN/PD/4
    - /PGN/PD/5

    # First method: Add a alpha version
    - /PGN/PD/1
    - /PGN/PD/2
    - /PGN/PD/3
    - /PGN/PD/4
    - /PGN/PD/4a // <= new record
    - /PGN/PD/5

    # Second method: Bump things down
    - /PGN/PD/1
    - /PGN/PD/2
    - /PGN/PD/3
    - /PGN/PD/4 // <= new record
    - /PGN/PD/5 // <= was 4
    - /PGN/PD/6 // <= was 5
  ```
- There is also an RCN (Record number?) - these _can_ be edited in Calm though so might be unsafe to use as unique
- RecordID - this is a long has looking string that isn't editable in Calm, and seems to be safe to assume as unique

You can read about the fields here:
http://www.dswebhosting.info/documents/Manuals/ALM/V09/MANUAL/main_menu/basics/complete_field_list_catalog.htm

# Sorting
Calm sorts records numerical / alpha ascending. e.g.
```
/test/1
/test/3
/test/5
/test/5a
/test/5b
/test/5f
/test/a
/test/b
/test/c
/test/c1
/test/c2
/test/cb
/test/cc
/test/d
```

**Comment by jamesgorrie** [comment]
@jtweed @warrd  some questions, maybe some can be answered when we look at the data. I'll update the ticket as we answer them.

## Identifiers
1. With the IDs - are we keeping the Sierra ID as the `sourceIdentifier`? This to me feels wrong as it should be calm as the source, and we put the Sierra ID on the record to be able to physically request the item. If we remove the current dependency on Sierra for booking, we can remove the calm sync all together and just run the two systems making collection people's lives much easier.

## Transformer
1. With the notes fields `ownership`, `acquisition`, `appraisal`, `accruals`, `related`, `finding-aids` - do we want to just create new note types?
1. `arrangement` isn't part of the model as it currently in our model, are we adding it? What type is it?
1. How do we want to combine `extent` and `UserWrapped6` in the physical description?

## Merger
1. Do we just use Calm data and ignore the Sierra data given that it can go out of sync etc and the people maintaining this data are generally up to date in Calm.

## Collection
1. We'll probably need to keep an eye on what data we want to denormalise into each work and how we might do that.

**Comment by kenoir** [comment]
@jtweed domain model is excellent - really clear way of conveying what goes where.

**Comment by warrd** [comment]
Quoting @jtweed from slack:

> Thanks - answers to some of those
the sourceIdentifier here should definitely come from calm
for the notes types, yes if they don't exist then we create additional ones
(i've tried to map as far as possible)
arrangement should be added to the model as a string
physical description - need to look at the data
use the calm data for the work, disregarding the sierra data
we will need to add the sierra item ids and location info the to item
collection - yep, let's let that one evolve as we go

**Comment by warrd** [comment]
Reading through the domain model, don't we also need a way to represent the position of a work within an archive (i.e. it's path inside the tree)? I know this data comes from the `RefNo` field, but using `sourceIdentifier` wouldn't make sense considering there are lots of works which aren't part of an archive, where using it in this way wouldn't make sense.

**Comment by jamesgorrie** [comment]
@warrd updated the comment to include sorting / position. Does that answer your question?

@jtweed - can we find somewhere that's easier to edit the mappings? Maybe something in the docs folder that's versioned?

**Comment by warrd** [comment]
Hmmm not really what I asking. We can discuss in person when everyone is around.
