### ISSUE TITLE
Delete all the ALTO files on the LIB_DDS_METS file share

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4189]
Now it's all been migrated to the new storage service, we should be safe to clean this up.

Part of #4187.

**Comment by alexwlchan** [comment]
Ticket asking for a VM: https://wellcome.service-now.com/sp?id=ticket&table=sc_req_item&sys_id=7a0ef5761be60c107ac0ea0e6e4bcb98&view=sp

**Comment by pollecuttn** [comment]
@alexwlchan That link doesn't work for me, maybe because I only get to see my tickets? Can you add the INC or REQ number here if you need me to follow up.

**Comment by alexwlchan** [comment]
@pollecuttn RITM0014982 / REQ0014963

**Comment by alexwlchan** [comment]
Jon has kindly provided me with a CentOS VM that has a much bigger pipe to the METS share. Files are vanishing much faster now! 😄

**Comment by alexwlchan** [comment]
Update:

> Deleted 777.1 GB (777,146,311,696 bytes) in 12,326,581 files @ 2020-01-31T09:54:59.766965

**Comment by alexwlchan** [comment]
> Deleted 991.2 GB (991,213,499,893 bytes) in 15,643,670 files @ 2020-01-31T16:09:34.798105

**Comment by alexwlchan** [comment]
> Deleted 1.1 TB (1,105,551,735,088 bytes) in 17,492,231 files @ 2020-02-03T10:31:19.408611

**Comment by alexwlchan** [comment]
> Deleted 1.3 TB (1,321,588,784,229 bytes) in 20,737,732 files @ 2020-02-03T17:21:06.627337

**Comment by alexwlchan** [comment]
> Deleted 1.4 TB (1,381,845,361,334 bytes) in 21,668,312 files @ 2020-02-05T10:54:15.405123

**Comment by alexwlchan** [comment]
Rescoping just to cover the ALTO files – I’ll do the METS files in a separate ticket.

**Comment by alexwlchan** [comment]
> Running 21 processes; deleted 1.8 TB (1,805,697,286,683 bytes) in 28,246,993 files @ 2020-02-07T16:35:41.294312

**Comment by alexwlchan** [comment]
> Deleted 1.8 TB (1,820,146,654,252 bytes) in 28,467,619 files @ 2020-02-10T09:21:24.237988

**Comment by alexwlchan** [comment]
> Deleted 1.9 TB (1,927,801,434,127 bytes) in 30,170,170 files @ 2020-02-10T11:25:40.324564

**Comment by alexwlchan** [comment]
> Deleted 2.0 TB (2,039,288,604,012 bytes) in 31,851,857 files @ 2020-02-10T15:34:33.427128

**Comment by alexwlchan** [comment]
> Deleted 2.1 TB (2,135,754,488,381 bytes) in 33,407,902 files @ 2020-02-18T12:46:13.315877

**Comment by alexwlchan** [comment]
There are 222 ALTO prefixes left in the DDS share which are in some way “interesting” (for example, there are ALTO files which aren’t in the storage service).

**Comment by alexwlchan** [comment]
172 ALTO prefixes!

**Comment by alexwlchan** [comment]
131 ALTO prefixes!

**Comment by alexwlchan** [comment]
Scratch that, 158 – I was missing all of `x/`.

**Comment by alexwlchan** [comment]
Done! With the help of #4289, I know that everything on the ALTO share has either:

* Been copied to the storage service; or
* Is no longer referenced by any of the METS in the storage service
