### ISSUE TITLE
RFC for observability of pipeline

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#4198]
Currently we have the issue that deploying is a bit fiddly.

Because of this we are having releasing a few changes at once, which compounds the fiddlyness and lands up with a developer spending a day or more ploughing through it.

Step 1 would be to have greater observability on the pipeline to be able to debug quicker and more effectively, making deployment a less arduous task.

The transformer seems like a good place to start as it's where most the debugging happens as parsing on real data is something that is hard to capture in tests.

APM is something we already use, so it might be good to investigate how it might be useful here.

This will hopefully lead us to being closer to [be able to continually deploy](https://github.com/wellcometrust/platform/issues/4197), ☁️ the dream ☁️ !

**Comment by jamieparkinson** [comment]
https://github.com/wellcomecollection/docs/pull/8

**Comment by kenoir** [comment]
Closing as outdated.
