### ISSUE TITLE
Fix physical description for multi-format video

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4201]
The physical description for videos with multiple formats (DVD and video, for example) is merged into one line, like this:

1 videocassette (VHS) (1 min.) : 1 DVD (1 min.) : sound, color, PAL. sound, color

It should be like this:

1 videocassette (VHS) (1 min.) : sound, color, PAL
1 DVD (1 min.) : sound, color

Take a look at Antismoking Baby: https://wellcomecollection.org/works/v6q9dnym

**Comment by alexwlchan** [comment]
Done!
