### ISSUE TITLE
We need to be able to index AIPs manually in Archivematica

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4216]
A precursor to finishing https://github.com/wellcometrust/platform/issues/4092

Not infrequently, Archivematica will fail at the "verify AIP" or "store AIP" stage because something times out or falls over – especially on larger transfers. The AIP has been successfully created, or even uploaded to the Wellcome Storage, you just can't see it in the Archival Storage tab.

Since that tab is likely how the archivists will interact with the storage service, we need to be able to add AIPs to that tab manually.

**Comment by ross-spencer** [comment]
:eyes: you might be interested in the management commands around this, at least as reference, those can be found [here](https://github.com/artefactual/archivematica/tree/6946cb55158ca3fe33e2504c358ace79b1be1ed5/src/dashboard/src/main/management/commands). There are a couple of issues open around them, notably for us to document them better! I haven't tried indexing a single AIP before, so they might need some work there.

**Comment by alexwlchan** [comment]
@ross-spencer Ooh, that rebuild_elasticsearch_aip_index_from_files.py command looks like it might be very close to what I need, interesting, thanks!

**Comment by alexwlchan** [comment]
Ah, and we also need to add them to the database, so it has the necessary attributes to get the space/external identifier. >.<

**Comment by alexwlchan** [comment]
Closing as not necessary thanks to reliability improvements.
