### ISSUE TITLE
Change the way the Catalogue VHS works to reduce S3 interactions

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4230]
One of the things we discussed at yesterday's retro was the speed/cost of a reindex.

## S3 API calls are expensive

I've just seen the cost graph for the platform account, and we're spending ~$400/month on PutObject API calls. (By comparison, we spent <$6 on PutObject calls in the storage service.)

Some back of the envelope numbers:

* A full reindex means processing ~2.5m records. That breaks down as:

    - 2.5m GetObject calls from the source data VHS
    - 2.5m PutObject calls to the recorder VHS
    - 2.5m GetObject calls in the matcher
    - 2.5m GetObject calls in the merger
    - 2.5m PutObject calls for the merger for the works graph
    - 2.5m GetObject calls in the ingest reading them back out

    That ~$30/reindex in S3 PutObject and GetObject API calls alone – not counting the actual storage or compute costs.

* Every night, we get ~250k records (?) in the Sierra overnight harvests. That means:

    - 250k GetObject calls in the Sierra data VHS (what's the current state of this record?)
    - 250k PutObject calls back (write the new record)
    - 1m GetObject calls for the pipeline (see above)
    - 500k PutObject calls for the pipeline

   That’s ~$7 a day, or ~$200 a month. Again, not accounting for storage or compute costs.

## Changing the VHS behaviour

Currently VHS always stores an object in S3 and a pointer in DynamoDB:

```
def store_record_in_vhs(<thing>)
    s3_location = s3.store_json_copy_of(<thing>)
    dynamodb.store_pointer_to(s3_location)
```

My proposal: store the record in DynamoDB unless it's above a certain threshold, otherwise write an object to S3 and store a pointer in DynamoDB. As pseudocode:

```
def store_record_in_vhs_new(<thing>):
    json_string = serialise_as_json(<thing>)

    if json_string.length() > THRESHOLD:
        s3_location = s3.store_json_copy_of(<thing>)
        dynamodb.store_pointer_to(s3_location)
    else:
        dynamodb.store_json_copy_of(<thing>)
```

For bonus points, gzip compress the JSON before deciding where to put it, and put a binary blob in S3 and/or DynamoDB.

The interface remains the same as before – whether an object is stored/retrieved from DynamoDB or S3 should be transparent to the calling code.

## Prior art

* This is how VHS used to work! We'd store complete records in DynamoDB, and then we switched to all S3 when we started to see a few records that were too big.

* The catalogue pipeline message sender already does something similar – messages are sent via SNS/SQS unless they're too big, in which case they're serialised to S3 and a pointer gets sent along. To the receiving app, the difference is hidden: https://github.com/wellcometrust/catalogue/blob/master/common/big_messaging/src/main/scala/uk/ac/wellcome/bigmessaging/BigMessageSender.scala

I'd like to keep the storage service manifests in S3 because they're less transient and having them available for batch analysis is useful. For the catalogue, I think this would make reindexing a bit faster and noticeably cheaper.

**Comment by alicefuzier** [comment]
I think ~all~ most of these S3 operations and Dynamo operations are in the recorder, so another option is what @kenoir suggested a few weeks ago, which is swap the VHS in the recorder for something else entirely, for example elasticsearch.

The disadvantage here is that we can't use the current storage interface in the recorder because ingestions would need to be batched. But we already have batching code in the ingestor that we can extract in the storage libraries.

I think this would have a bigger impact in term of cost savings (no dynamo/s3 reads). Also, it would make data in the recorder much easier to access for debugging purposes in Kibana.
Lastly, it would make all of those annoying orphaned buckets when you destroy a pipeline not be a problem

I think these problems might be symptomatic that a VHS is not the correct storage here. 

Not saying we definitely have to go down this route, but it is interesting so it would be good to keep this in mind.

**Comment by kenoir** [comment]
As @alicefuzier i'd be interested in looking at alternative data stores (while attempting to maintain the storage lib interface).

> I think these problems might be symptomatic that a VHS is not the correct storage here.

Or perhaps that the recorder may be unnecessary with some rearranging.

**Comment by alicefuzier** [comment]
> Or perhaps that the recorder may be unnecessary with some rearranging.

I think the main problem with that would be what is the output of the matcher. Currently the matcher spits out `LIst[Set[WorkIdentifier]]` where ` WorkIdentifier` is `WorkIdentifier(identifier: String, version: Option[Int])`. The merger then uses these identifiers to get the works from the table. 
Without the recorder, the matcher would need to send a `List[Set[TransformedBaseWork]]` which would almost certainly be too big and need be written to S3 for every single message that the matcher sends. I don't think we would reduce S3 costs this way, we would just move them somewhere else.

**Comment by alexwlchan** [comment]
Closing – the recorder is gone now!
