### ISSUE TITLE
Enable access to CALM from AWS services

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4232]
Request from D&T access to CALM from a fixed external IP address.

We need to scope with D&T the possibility of setting up firewall rules to allow access from a fixed IP address. It is likely this change will need to go via CAB.

Reestablishing a VPN connection is also an option, but fixed IP access is preferable to us as reduces infra complexity from our side.

**Comment by kenoir** [comment]
cc @warrd @pollecuttn

**Comment by pollecuttn** [comment]
I'm checking about the CALM API with Library Systems Support and will update here when I've heard back.

**Comment by pollecuttn** [comment]
The CALM API is available at http://wt-calm/CalmAPI/ .

@warrd has the username and password from Library Systems Support

@kenoir It doesn't need to be accessed from a fixed IP currently. Does you need it to be available only from specific IP addresses?

**Comment by alexwlchan** [comment]
@pollecuttn http://wt-calm/ isn't available outside the corporate network

**Comment by warrd** [comment]
Alex's comment (which has now disappeared) is correct, we can't access the API from AWS (where our code runs), as it is outside of the corporate network. We need a solution to this, so as @kenoir suggested either

1) Setting up the CALM API so we can access from a fixed AWS address (preferable)

2) Tunnel our AWS connections inside the Wellcome network (not as preferable)

**Comment by pollecuttn** [comment]
Thanks - I've gone back to ask about 1.

**Comment by louisesimon** [comment]
I've opened a call with Axiell, third-party for the CALM API.

**Comment by pollecuttn** [comment]
There's a newer version of the CALM API available. @louisesimon is going to try to let you know what's in the current and newer versions, so you can see if it would be worth upgrading, or if staying on the current version is fine.

**Comment by louisesimon** [comment]
Chris Dennehy thinks it would be possible to give access to the API from AWS via a fixed address.  He's taking a better look tomorrow and will come back with further info.

**Comment by pollecuttn** [comment]
@kenoir 
From Chris Dennehy re giving access to the API from AWS via a fixed address:

> Yes this can be done.
> 
> wt-calm already has a public DNS record, is accessible externally and located in a Library DMZ. So we will need to know the fixed AWS IP address and we can configured to firewall as required.
> 
> Let me know we you have the details and we can get a changed raised.

**Comment by pollecuttn** [comment]
Wellcome is currently using CALM API v3.

This is the guide for CALM API v 4.0.4.588:
[Calm API Guide.pdf](https://github.com/wellcomecollection/platform/files/4244727/Calm.API.Guide.pdf)

It is the same as v3 up to p14.

@warrd Please have a look to see if there is anything in this newer API that would be useful and let me know if there is.

**Comment by warrd** [comment]
Thanks @pollecuttn! Nothing is jumping out to me that would help with the Calm adapter, and have already coded against the older API, so happy with current version for now

**Comment by pollecuttn** [comment]
@warrd Chris Dennehy has permitted access. Please test and let me know if it's worked or not.
