### ISSUE TITLE
Decide on design of the merger-with-images

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/platform#4263]

**Comment by jamieparkinson** [comment]
Current thinking on this:

1. Modify the `WorkPairMerger` trait to separate the logic of determining whether a merge is achievable, and performing that merge. Something like:
```scala
trait WorkPairMerger {
  protected def canMergeWorks(
    firstWork: UnidentifiedWork,
    secondWork: TransformedBaseWork): Boolean

  protected def mergeAndRedirectWorkPair(
    firstWork: UnidentifiedWork,
    secondWork: TransformedBaseWork): MergedWork
}
```

2. Add another trait, `ImageCreator` (exact name tbd), which implementors of `MergerRule` must also mix in. Something like:
```scala
trait ImageCreator {
  protected def createImage(
    firstWork: UnidentifiedWork,
    secondWork: TransformedBaseWork): MergedImage[Unidentified]
}
```

- Filter out unmergeable works using `1.`, then create images and merged works independently from the resulting set of unmerged works.

**Comment by alexwlchan** [comment]
This has been deployed and running for a while, closing.
