### ISSUE TITLE
Archivematica - Failed to copy files to SIP arrange

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/platform#4271]
When using the Archivematica appraisal tab, you should be able to drag and drop files from the backlog into a new SIP arrangement on the right hand side of the screen. 

Dragging a single file over to the arrangement section results in the error: Failed to copy files to SIP arrange

Expected behavior is that the file name will appear under the directory you created in the arrangement section.

![image](https://user-images.githubusercontent.com/49983203/74520757-21997e80-4f10-11ea-8e47-c449f66aa521.png)

**Comment by alexwlchan** [comment]
Prod or staging; when did you try this?

**Comment by aray-wellcome** [comment]
Staging, about twenty minutes ago.

**Comment by aray-wellcome** [comment]
I've tried adding PPSHF to the backlog but got an error 
![image](https://user-images.githubusercontent.com/49983203/74539690-659f7a00-4f36-11ea-9a69-23a610f5fda7.png)

`list index out of rangeTraceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/move_to_backlog.py", line 236, in call
    job.set_status(main(job, transfer_id, transfer_path, created_at))
  File "/src/MCPClient/lib/clientScripts/move_to_backlog.py", line 182, in main
    backlog = storage_service.get_location(purpose="BL")[0]
IndexError: list index out of range`

**Comment by alexwlchan** [comment]
Aha, I have a pretty good idea what that means.

On 14 Feb 2020, at 14:30, aray-wellcome <notifications@github.com> wrote:

﻿

I've tried adding PPSHF to the backlog but got an error
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F49983203%2F74539690-659f7a00-4f36-11ea-9a69-23a610f5fda7.png&data=02%7C01%7Ca.chan%40wellcome.ac.uk%7Cbe58b021c2c345c1199508d7b15a674c%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637172874142622124&sdata=AOigyI3sVethIH9uwyusOOMR2%2BQQgjKCVcobXVdeq4s%3D&reserved=0>

list index out of rangeTraceback (most recent call last): File "/src/MCPClient/lib/job.py", line 111, in JobContext yield File "/src/MCPClient/lib/clientScripts/move_to_backlog.py", line 236, in call job.set_status(main(job, transfer_id, transfer_path, created_at)) File "/src/MCPClient/lib/clientScripts/move_to_backlog.py", line 182, in main backlog = storage_service.get_location(purpose="BL")[0] IndexError: list index out of range

**Comment by alexwlchan** [comment]
This seems to be working now!
