### ISSUE TITLE
If config in container doesn't work nothings tells us

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#4281]
If something is wrong with reading the application.conf, nothing logs to logstash, nor ecs logs, but does to cloudwatch.

We should log to logstash.

**Comment by kenoir** [comment]
In order to do this we would need to be reading from stdout, our applications transport logs elsewhere so this is currently impossible without rethinking how we do logging.

**Comment by kenoir** [comment]
This is worth a read: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html

ECS will export logs to a very limited set of places if you use Fargate.
