### ISSUE TITLE
Merger rewrite 🎉

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/platform#4283]
We think that the current merger design is (a) tricky to reason about and (b) will be difficult to extend to creating images. Therefore, we want to redesign it before doing https://github.com/wellcomecollection/platform/issues/4205.

Things:

- [x] per-field merger rules: there is one rule for each field, which takes a target and a list of sources and returns the new field value.
- [x] one target for all field rules / sets of matched works
- [x] how do we deal with redirects?
- [x] logging
- [x] tests

**Comment by jamesgorrie** [comment]
How do you deal with redirects?

**Comment by jamieparkinson** [comment]
I'll document everything properly when I PR it but the short answer is that each rule returns a list of works that it would like redirected, then the top-level merger accumulates and de-duplicates and applies whatever other logic it might want to those

**Comment by jamieparkinson** [comment]
Will be closed by https://github.com/wellcomecollection/catalogue/pull/440
