### ISSUE TITLE
Creating wireframes based on acceptance criteria

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/platform#4284]
## Who is this for?
Digital team

## What's it for?
For us to see the acceptance criteria visually so we know what is going to be built.
Based on https://github.com/wellcomecollection/platform/issues/4280

**Comment by pollecuttn** [comment]
@DominiqueMarshall Please add the zeplin link here so we know where to look for them in future

**Comment by DominiqueMarshall** [comment]
**Logged out user scenarios:**
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a35deafd9662acdd215/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a3572ead876e1493115/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a35f9503e7360d94a55/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568a35bb57d361c1de3950/

**Single item requests:**
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568ca18004be787c89832e/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568ca19c2ec1615ab7dfb3/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568ca2762da8697d15f2ae/

**Multiple item requests:**
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568db3ae3c7066192f1159/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568db427cd32677b2555ac/
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568db44bd744669422b32e/

**Library account page:**
https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5e568e26f42eda67d4480f28/
