### ISSUE TITLE
Index all the storage manifests into Elasticsearch

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4303]
A key idea of the storage service is to give you a way to do batch analysis of all our bags!

But… there's no way to get a list of all the bags from the API endpoints. You can do it if you have access to the storage manifests VHS table, but:

1. Not everybody has access to that
2. That's an icky way to do it
3. It ties anything that wants to iterate over all the bags to an implementation detail

This is something that would have been useful for some of the recent ALTO/METS cleanup work, and also for the bag browser.

Ideas:

- Shove all the data into an Elasticsearch cluster. Would open lots of other benefits and you could do queries directly in the cluster, but is more infra to maintain.
- ~Add an API endpoint for scanning the VHS table under the hood. Less moving parts, but we'd need to think about pagination.~

We don't need to do this imminently, but it's been a source of pain for me several times and I'd like a more officially supported way to do it.

**Comment by alexwlchan** [comment]
There’s an early prototype over here which indexes whole manifests: https://github.com/wellcomecollection/storage-service/pull/468

I was assuming we might want to iterate over all storage manifests _or_ all unique files in the storage service (which might appear in multiple bags)

If you wanted to do this properly:

- [ ] Work out what sort of queries we want to perform
- [ ] Pull out the elasticsearch code from the catalogue repo into a standalone library
    - [ ] Update the catalogue to use the standalone library
- [ ] Add support for indexing files in the `BagIndexer` class in that patch, and in particular recording all the bag versions that a particular file appears in
- [ ] Wrap it in a queue-backed worker
- [ ] Modify the ingests monitor to support "ingest index update event" that adds to the list of ingest events, but doesn't affect the succeeded/failed status

Plus wire up the queues, builds, permissions, etc.

I reckon there’s about a week of work here to do this properly (and needs discussion with somebody else, I can't do this alone).

**Comment by jamesgorrie** [comment]
> Update the catalogue to use the standalone library

I'm going to pull the [rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) card here. An abstraction might just make it harder to maintain as the ES setups will be different, and also make it harder to pull out.

I'd prefer the flexibility in the catalogue over having to think of how to push any changes upstream to a generic library. We already use `elastic4s` which abstracts out the hard bits.

**Comment by alexwlchan** [comment]
Queries we know we want to be able to do:

* Tell me about every bag in the storage service, because I want to do some processing on each bag
* Tell me about every bag in the storage service with a file that has checksum X (because it's a symptom of the poster image issue)
* Tell me about every JP2 that was ingested during these dates (Christy wants these stats)

Here’s a suggestion for the schema:

We have two indexes in the cluster, one for manifests, one for individual files.

* The *manifests* index contains the raw storage manifests; essentially the VHS but in Elasticsearch form. You'd use this if you wanted to search across bags.

   Within *manifests*, the `manifest.files` field (i.e. the payload files) is a nested document. For example, you could search for all bags with a .JP2 file that's >5MB.

* The *files* index contains an entry for every distinct file in the storage service (i.e. every object in S3). You'd use this if you wanted to query individual files – e.g. how many new JP2s did we ingest in February?

   The fields are:

    - `bucket`, `path`, `name` (from the bag location/file path)
    - `size`, `checksum` (from the file metadata)
    - `createdDate` (from the bag)
    - `bag.space`, `bag.externalIdentifier`, `bag.versions`

    The one interesting field is bag.versions, which is a list of every distinct version a file has appeared in (e.g. `["v1", "v3", "v4"]`). So if you refer to a file in a previous version in a fetch.txt, we append to this array.

What's missing is a way to filter on the "latest" version of a bags – e.g. if I'm looking for bags with poster image issues, I only care if they're the latest version of the bag. If I've already pushed a fixed bag, I don't care about seeing that in results. If we want to keep all past versions in the index, I'm not sure how we do that.

Thoughts?

**Comment by alexwlchan** [comment]
Closing as a dupe of #4521.
