### ISSUE TITLE
Merger mismatch? Image and description don't match

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#4311]
@jtweed FYI

The image and description for this work don't match
https://wellcomecollection.org/works/x884bsb7

The description looks like it's from http://encore.wellcomelibrary.org/iii/encore/record/C__Rb1665830, which is also at https://wellcomecollection.org/works/saf89au6

**Comment by jtweed** [comment]
This isn't a bug, it's a data issue. It can be fixed by Collections Information, by finding the correct record in Sierra and adding a link to this image, like for other images from Wellcome Images.

**Comment by pollecuttn** [comment]
Jonathan and I spoke about this one. There isn't an equivalent of https://wellcomecollection.org/works/x884bsb7 in Sierra.

The image and metadata need to be removed.

**Comment by jtweed** [comment]
Or the image added to Sierra - can you check with C&R?

**Comment by pollecuttn** [comment]
Found it.

Sent to Collections Information:

> I think the image at https://wellcomecollection.org/works/x884bsb7
goes with the Sierra record http://search.wellcomelibrary.org/iii/encore/record/C__Rb3216547.

> The description that is currently showing with the image is from http://encore.wellcomelibrary.org/iii/encore/record/C__Rb1665830, but the image and metadata are already correctly showing at https://wellcomecollection.org/works/saf89au6

> For b3216547 please link to https://wellcomecollection.org/works/x884bsb7 and that should make the image and metadata match.
