### ISSUE TITLE
What would it take for somebody else to use the storage service?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4366]
This is a ticket for dumping thoughts/ideas for what we'd need for somebody who isn't us to pick up the storage service and use it. Probably incomplete.

- [ ] Publish images in a publicly accessible location (e.g. Docker Hub) with changelogs (https://github.com/wellcomecollection/platform/issues/4365)
- [ ] Document how to get started with Terraform, Cognito Pools, etc.
- [ ] Document the replicator/verifier interface – this is the bit I imagine people are most likely to want to replace
- [ ] Document (or better, fix) the issue with read-after-write consistency upsetting the verifiers

(This ticket is just for saving ideas; actually doing the work needs prioritising separately.)

**Comment by tuanlpham** [comment]
Document from step 1 - to actually start from blank AWS account/console
Document the development environment.

**Comment by kenoir** [comment]
Closing as outdated, we're not focussing on this at the moment.
