### ISSUE TITLE
IAM role digitisation-developer needs access to wellcomecollection-assets-workingstorage

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/platform#4370]
Holly Peel needs access to https://console.aws.amazon.com/s3/buckets/wellcomecollection-assets-workingstorage/miro/Wellcome_Images_Archive/ but assuming the digitisation-developer role does not allow access. 

I have assumed the digitisation-admin role as well and it didn't allow me access. 

Can we be allowed access to this bucket as Holly sometimes needs the MIRO images for fulfilling orders.

**Comment by alexwlchan** [comment]
@aray-wellcome I’ve made a tweak to the permissions; try now?

**Comment by aray-wellcome** [comment]
@alexwlchan That is perfect. I can get into it in both roles now and download. Happy days! Thanks!
