### ISSUE TITLE
Does the storage account still need access to wc-assets-workingstorage?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4371]
While looking at #4370 and https://github.com/wellcomecollection/platform-infrastructure/pull/6, I noticed that the storage account has read-only access to the wc-assets-workingstorage bucket:

https://github.com/wellcomecollection/platform-infrastructure/blob/caf7547e3c6886c93ca369022fd30f2d5ced8740/assets/s3_workingstorage.tf#L44-L59

This was so the bagger could read METS out of this bucket, but I don’t think there’s anything we need there now. Can we remove these permissions?

**Comment by kenoir** [comment]
I think I you are correct, we can remove access.
