### ISSUE TITLE
Decide how we verify objects inside Azure

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4398]
Part of ~https://github.com/wellcomecollection/platform/issues/4399~ #4414

When we create our third replica in Azure, we'll need to create a replicator/verifier pair that can manage the Azure replica.

We have a couple of options:

1. **Run the replicator in AWS, the verifier in Azure.**

   Pros:

   - We only pay the egress cost once, when the data leaves AWS. The verification happens entirely inside Azure, where there are no extra egress costs.

   </p>

   Cons:

   - We need to do work to run containers inside Azure, and pass queue messages between AWS and Azure.
   - We'd be running services in two clouds, which increases the overhead for monitoring, infrastructure, etc.
   - We need to put write permissions from Azure inside AWS.

   </p>

2. **Run both the replicator and verifier inside AWS.**

   Pros:

   - Simpler development and monitoring: all the code runs inside AWS, and Azure is just a simple data store.

   </p>

   Cons:

   - We pay the egress cost in both directions: once to replicate data from AWS to Azure, once to read it from Azure back into AWS.
   - We need to put write permissions from Azure inside AWS.

   </p>

3. **Run both the replicator and verifier in Azure.**

   Pros:

   - Only pay the egress cost once.
   - Each cloud only has read permissions for storage in the other cloud

   </p>

   Cons:

   - Complexity of running multi-cloud apps

---

Let's put some actual numbers on the question. We currently have ~60TB in the storage storage.

To make the numbers easy, let's round that up to 100TB, accounting for future growth and experiments as we set up the Azure replica.

Let’s also assume we’re paying for the most expensive tier, because after the initial migration that’s the rate we’ll be paying:

* **Amazon S3 egress cost: $9000** = 100TB * $0.09/GB (https://aws.amazon.com/s3/pricing/)
* **Azure Blob Storage egress cost: $8700** = 100TB * $0.087/GB (https://azure.microsoft.com/en-us/pricing/details/bandwidth/)

Double or triple that number as you expect our storage capacity to grow (e.g. for A/V material).

---

Questions:

* Have I missed anything? Are there other options or considerations?
* What should we do?

**Comment by kenoir** [comment]
I'd like to check our assumptions about Azure as the other cloud provider - I can guess the reasons (and have heard @jtweed recount some of them) but worth having them in writing.

Off the top of my head:
- AWS/Azure data centres share less physical co-location than AWS/Google
- Azure is more used and a more reliable cloud provider (from a will the business stay in the cloud provider market point of view).

**Comment by alexwlchan** [comment]
> AWS/Azure data centres share less physical co-location than AWS/Google

I don’t think that’s relevant to our use case, is it?

AIUI, the plan is to write a third replica to an Azure data centre in Amsterdam, so we get geographic redundancy of our data. Whether there's an AWS data centre in Amsterdam or an Azure data centre in Dublin doesn't matter, because we won't be using them.

**Comment by alexwlchan** [comment]
I hadn’t realised the volume of A/V material we're getting for the MXFs; which is closer to 200TB.

That means there's a potential saving of closer to $25k if we do the verification inside Azure, which tips the balance on that a bit.

**Comment by jtweed** [comment]
That is definitely an upper bound though, it is won’t be quite that high. That’s based on 1000 videos each 200GB. If you look in the av buckets in the digitisation account, you can see what’s come in so far.

**Comment by alexwlchan** [comment]
We decided we're going to run both services in AWS for now.
