### ISSUE TITLE
Prepare inference services for deployment

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/platform#4402]
In order to deploy the inference manager / inferrer pair, the following needs to be done:

- [x] S3 bucket for model data
- [x] IAM task role for accessing said bucket
- [x] Task definition containing both manager and inferrer
- [x] ECS service

**Comment by jamieparkinson** [comment]
@harrisonpim how much memory does the inferrer require?

**Comment by harrisonpim** [comment]
not sure off the top of my head - 2GB is _probably_ fine, 4GB should be comfortable?
