### ISSUE TITLE
How do we index storage manifests in Elasticsearch?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4410]
Taken from https://github.com/wellcomecollection/platform/issues/4303

We want to put the data from the storage service in Elasticsearch, so people can run queries on it.

1. What sort of queries do we want to be able to run?
2. Once we know (1), how should we index the data in Elasticsearch? 

This ticket is to discuss (1) and (2); actually implementing that will be a separate ticket.

**Comment by alexwlchan** [comment]
Queries I want to be able to do:

- **What are the bags in the storage service?** I want to do some processing of each bag.
- **Which bags have files with properties XYZ?** For example, finding every bag with a file that has checksum X, which was the indicator of the poster image issue.
- **How many JP2 and XML files were ingested into the digitised space during this month?** Christy has asked Ashley for these stats, and we don't have a great way to get them right now.
- **How many new files were ingested into space S between date D1 and D2?** I know this is something people wanted from Preservica and were never able to get.

---

With those queries in mind, here's a suggestion for the schema:

We have two indexes in the cluster, one for manifests, one for individual files.

* The *manifests* index contains the raw storage manifests; essentially the VHS but in Elasticsearch form. You'd use this if you wanted to search across bags.

   Within *manifests*, the `manifest.files` field (i.e. the payload files) is a nested document. For example, you could search for all bags with a .JP2 file that's >5MB.

* The *files* index contains an entry for every distinct file in the storage service (i.e. every object in S3). You'd use this if you wanted to query individual files – e.g. how many new JP2s did we ingest in February?

   The fields are:

    - `bucket`, `path`, `name` (from the bag location/file path)
    - `size`, `checksum` (from the file metadata)
    - `createdDate` (from the bag)
    - `bag.space`, `bag.externalIdentifier`, `bag.versions`

    The one interesting field is bag.versions, which is a list of every distinct version a file has appeared in (e.g. `["v1", "v3", "v4"]`). So if you refer to a file in a previous version in a fetch.txt, we append to this array.

What's missing is a way to filter on the "latest" version of a bags – e.g. if I'm looking for bags with poster image issues, I only care if they're the latest version of the bag. If I've already pushed a fixed bag, I don't care about seeing that in results. If we want to keep all past versions in the index, I'm not sure how we do that.

Questions:

* Have I missed any category of query we'd like to make?
* If not, is this a reasonable schema for the index?

**Comment by alexwlchan** [comment]
(There's an initial experiment over here that implements the schema described above, but it's not usable in its current state.)

**Comment by kenoir** [comment]
Files index has an entry for every version of every file? - so entries are immutable.

**Comment by alexwlchan** [comment]
> Files index has an entry for every version of every file? - so entries are immutable.

Not quite, it's an entry for every object in S3.

* Store bag V1: `v1/alice.txt` ~> create a new File in Elasticsearch `{path: v1/alice.txt, versions: 1}`
* Store bag V2, with a fetch.txt to `v1/alice.txt` ~> update existing File in Elasticsearch `{path: v1/alice.txt, versions: 1, 2}`
* Store bag V3, with a new `v3/alice.txt` ~> create a new File

**Comment by kenoir** [comment]
> Not quite, it's an entry for every object in S3. 

I'm suggesting we have an entry for every version.

**Comment by alexwlchan** [comment]
Ah, got it.

**Comment by kenoir** [comment]
i'm suggesting the rolling/rollup pattern as with log data - because it feels similar.

It's to do with handling load in ES when ingesting & having lots of "old" data hanging around. Basically when you've got loads of new documents being created (loads of files ingested) you want to spread them across multiple nodes (so your _hot_) index i.e. today, is multiple shards across multiple nodes. 

But you don't want loads of shards for your old data as that's not good for search performance so you aggregate those indices when they get older than a few days.

**Comment by kenoir** [comment]
The immutability bit is nice when ingesting as you don't have to merge things at the point of ingestion - you can batch that later when you do the rollup.

**Comment by alexwlchan** [comment]
:nod:

Makes sense.

If we do that, it would be useful to add a boolean field that says “is this an original or from a previous version” or something similarly named, because being able to find unique S3 objects is useful.

**Comment by kenoir** [comment]
You probs don't need to note the most recent - when you search you'll just get all the versions (and the rolled up version) and you can consolidate that after the search - though without an API in front of ES you would have to do that in your head.

Are we planning for Kibana to be the UI that folk will use to search?

**Comment by alexwlchan** [comment]
I would assume so, at least for now. @jtweed would know for sure.

You can create nicer interfaces on top of it (eg the bag browser), but I don’t think that’s in scope for this quarter. Getting the data into a usable shape is.

**Comment by kenoir** [comment]
aye, but if that's an aspiration it might shape some decisions now.

**Comment by jtweed** [comment]
Yes, I'd assume that people will use Kibana for now.

I think there should be three indexes:

* ingests
* bags
* files

With whatever slightly flattened version of the API model makes sense.

Those are the main entity within the storage service, so they should be reflected as such in the search indexes.

**Comment by alexwlchan** [comment]
Yeah, ingests should be easy to index – although we’d have to think about where to get the completed ingests from.

Robert sent me a link to the rollup docs; that makes sense now and seems sensible, with the ingests especially. And I can tweak the File model so it's immutable per Robert's suggestion (it means deleting the most complex bit of the current app, ha).

**Comment by alexwlchan** [comment]
If we're throwing ingests into the mix, here's a question I regularly want to know the answer to:

* What ingests are currently in-flight?

**Comment by jtweed** [comment]
Indeed - it would be great if updates to elasticsearch are streamed during ingest, so that the ingest status and event log are up to date.

**Comment by kenoir** [comment]
> Within manifests, the manifest.files field (i.e. the payload files) is a nested document. For example, you could search for all bags with a .JP2 file that's >5MB.

I think we should verify this is the correct relationship as (we all know) there are performance considerations depending on what we choose.

**Comment by kenoir** [comment]
> Indeed - it would be great if updates to elasticsearch are streamed during ingest, so that the ingest status and event log are up to date.

We should definitely be able to do this.

**Comment by alexwlchan** [comment]
>> Indeed - it would be great if updates to elasticsearch are streamed during ingest, so that the ingest status and event log are up to date.
>
> We should definitely be able to do this.

The ingest indexer as implemented will do this.

**Comment by alexwlchan** [comment]
One additional consideration: would it be worth indexing the human-readable file size alongside the bytes?

**Comment by alexwlchan** [comment]
>> Within manifests, the manifest.files field (i.e. the payload files) is a nested document. For example, you could search for all bags with a .JP2 file that's >5MB.
>
> I think we should verify this is the correct relationship as (we all know) there are performance considerations depending on what we choose.

Given that there will be a separate "files" index, I'm inclined to drop this.

**Comment by jtweed** [comment]
Yep, we can always add it back if it turns out we need it but better to start without.

**Comment by alexwlchan** [comment]
One additional consideration: there are going to be queries where people only want to find the latest version of a given bag. How do you do that?

e.g. Ashley currently needs to find all bags with spaces in the filenames. Once we push a new version, that bag is "fixed". **Should the reporting cluster index all versions, or just the latest version?**

**Comment by alexwlchan** [comment]
Two more notes:

* A real query that Ashley wanted to run today: "how many bags in the digitised space have filenames with spaces?"
* Further discussion of the indexing question in Slack: https://wellcome.slack.com/archives/CN56BRQ5B/p1588250269102500

**Comment by alexwlchan** [comment]
Okay, so bringing this all together, here's a proposal:

*   **We have a single index for the latest version of every manifest.**

    This holds a version of the API model, but with a couple of extra bits attached (in particular, the ingest ID, which I don't think we expose externally). The `manifest.files` field isn't nested.

    This doesn't preclude us creating an index that holds every version of a bag later if we need it, but is simpler now and exposes the "latest" data, which is the most useful immediate stuff.

*   **We have a single index for every file in the S3 bucket.**

    This index contains something like:

    ```json
    {
      "path": "data/objects/b12345678.jp2",
      "size": 1234,
      "checksum": "sha256:abcd…1234",
      "key": "digitised/b12345678/v1/data/objects/b12345678.jp2",
      "parentBag": {
        "space": "digitised",
        "externalIdentifier": "b12345678",
        "version": 1
      }
    }
    ```

    One entry for every object in S3; if the same file appears in multiple bags you only get a `parentBag` for the first bag it appears in.

    If you want to find all the bags a given file appears in, search on the `manifest.files.path` in the manifest, e.g. `"v1/data/objects/b12345678.jp2"`.

**Comment by alexwlchan** [comment]
We discussed this a bit further in Slack; see https://wellcome.slack.com/archives/CN56BRQ5B/p1589387281100400

I’m going to close this ticket, and create a new ticket describing the proposed approach.

In particular, this context from Jonathan was helpful:

<blockquote>
<h2 id="storagereporting">Storage reporting</h2>

<h3 id="ingests">Ingests</h3>

<ul>
<li>Total number of ingests</li>
<li>Filter by time</li>
<li>Filter by space</li>
<li>Filter by status</li>
<li>Find by ingest ID</li>
<li>Find by external ID</li>
<li>View event log</li>
</ul>

<h3 id="bags">Bags</h3>

<ul>
<li>Total number of bags</li>
<li>Avg number of files per bag</li>
<li>Avg number of versions per bag</li>
<li>Filter by time</li>
<li>Filter by space</li>
<li>Filter by location type</li>
<li>Find by external ID
This should be bag-centric, not version centric
So could show just current version of bag, potentially adding details of historical versions later</li>
</ul>

<h3 id="files">Files</h3>

<ul>
<li>Total number of files</li>
<li>Aggregate by suffix (type)
Can this be done by listing files inside bags?
Pagination is irrelevant, just ability to aggregate files from current version of the bags that currently exist</li>
</ul>
</blockquote>
