### ISSUE TITLE
Storage tiering for video master files

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4413]
### Objective

Sustainable digitised and born-digital preservation

### Measures

- Are all existing MXF files only stored in cold storage tiers?
- Are new MXF files only stored in cold storage tiers during ingest?

### Initiatives

- [x] Support new AV workflow in Goobi
- [x] Support new AV workflow in DDS/DLCS
- [x] Store new MXF files in cold storage tiers
- [x] Migrate existing MXF files to cold storage tiers (https://github.com/wellcomecollection/platform/issues/4490)

**Comment by alexwlchan** [comment]
Related: https://github.com/wellcomecollection/platform/issues/4403
