### ISSUE TITLE
Storage service ad hoc querying and reporting

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4416]
### Objective

Sustainable digitised and born-digital preservation

### Measures

- Is it possible to search for ingests and view their event logs in Kibana?
- Can Kibana be used to search for and report on files within the storage service?

### Initiatives

- [x] Index ingests into Elasticsearch (https://github.com/wellcomecollection/platform/issues/4453)
- [x] Index bags into Elasticsearch
- [x] Index files into Elasticsearch
- [x] Create dashboards for storage reporting

**Comment by alexwlchan** [comment]
Some initial discussion of this in #4410
