### ISSUE TITLE
How do we index storage service ingests in Elasticsearch?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4417]
Part of https://github.com/wellcomecollection/platform/issues/4416

The individual services send ingest updates to the ingests monitor; the monitor is responsible for combining those updates with data in the ingests table to produce the complete ingest. How do we get the ingests out of the ingests monitor and into Elasticsearch?

My suggestion and some questions follow.

---

When the ingests monitor finishes writing to the ingests DynamoDB table, it sends the complete ingest to a new SNS topic.

The ingest indexer (a new app) listens to the events from this stream, serialises that as a display ingest, indexes that blob of JSON in Elasticsearch. 

![ingest_indexer](https://user-images.githubusercontent.com/301220/78590806-52c06c00-783a-11ea-9c1c-74a62f1f4746.png)

Notes:

* The indexer would use the version field on the ingest to ensure updates are ordered correctly (similar to the Works ingestor in the catalogue pipeline)
* The indexer writes into a rolling index, the name of which is determined when it starts (say `storage_service_ingests-day-{YYYYMMDD}`). We roll it up on a regular basis (say once a week).

Rationale:

* I don't think the indexing logic belongs in the ingests monitor; updating DynamoDB and Elasticsearch are two different tasks.
* The ingest indexer shouldn't know about (1) the DynamoDB table or (2) how to construct an ingest from partial updates. We shouldn't be duplicating that logic.
* Ingests are small and can easily fit in SNS/SQS. We know they fit, because we send the complete ingest to the notifier when an ingest completes.
* Having a stream of ingest updates may have other uses.

Questions:

* What do people think of this design?
* Which Elasticsearch cluster should we be indexing these into? The reporting cluster?

**Comment by alexwlchan** [comment]
Per Jonathan in Slack, this is all going into the reporting cluster.

**Comment by kenoir** [comment]
I completely agree that there should be another service for this.

**Comment by alexwlchan** [comment]
Robert pointed out something important in Slack: the design suggested above means the indexer wouldn't know about ingests that have been accepted but haven't started any work yet.

There are several ways we could solve that, unclear which we pick:

* The ingests API sends a notification to the ingest indexer input topic
* The ingests API sends a no-op update to the ingests monitor, which forwards the ingest to the topic
* The ingests monitor becomes the only app that writes to the ingests data store, and the API uses a synchronous, internal API to start ingests (#4419)

**Comment by alexwlchan** [comment]
There's enough discussion here; I'm going to close this and break the remaining work down into separate tickets.
