### ISSUE TITLE
Consolidate ingests tasks into single service 

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4419]
We have a slightly odd thing in the storage service: both the ingests API and the ingests monitor can update the ingests data store. It would be cleaner if the ingests monitor was the only thing that wrote to the store, and the API was just read-only.

This has knock-on effects for https://github.com/wellcomecollection/platform/issues/4417

Past discussion:

- https://wellcome.slack.com/archives/CN56BRQ5B/p1586245695191800

Wiring up the ingests API:

- [x] Add a getIngest() method (https://github.com/wellcomecollection/storage-service/pull/509)
- [x] Add a createIngest() method (https://github.com/wellcomecollection/storage-service/pull/510)
- [x] Use the new methods in the external API (https://github.com/wellcomecollection/storage-service/pull/511)
- [x] Remove config/perms for the database from the external ingests API (https://github.com/wellcomecollection/storage-service/pull/504)
- [ ] Make the internal and external URIs consistent (`/ingest`, `/ingests`!!)
- [x] Move the ingests-related apps into a single directory (https://github.com/wellcomecollection/storage-service/pull/513)

**Comment by kenoir** [comment]
Another thing to consider is the consequence of making either change (new event type / consolidate ingest work to monitor) to future work, e.g. what if we want to _cancel_ or in some way modify ingests in progress.

My impression is that making a change where the ingests monitor is the only thing writing to the data store would be cleaner in general (clearer to devs, easier to work with in the future). 

It's contained only to a couple of services, introduces only 1 unusual thing (field "work to do" from SQS/REST) - so at present I prefer to do that over: the ingest API sending messages to another service over SQS and the monitor service understanding another special event type.

**Comment by alexwlchan** [comment]
> e.g. what if we want to _cancel_ or in some way modify ingests in progress

I've done this a couple of times manually, when messages fall off DLQs but the ingest is never cancelled. Being able to do it in a more controlled way would be nice.

**Comment by kenoir** [comment]
We will consolidate ingest tasks in a single service:

- A "tracker" which takes the responsibility of communicating with the internal data store and provides a private internal REST API to do so.
- A "monitor" that relays requests from SQS to the tracker.
- A "api" that relays requests from the public API to the tracker.

As per @alexwlchan's diagram:

![Screenshot 2020-04-29 at 11 40 05](https://user-images.githubusercontent.com/953792/80593439-294dc700-8a19-11ea-85d1-703a05a28824.png)

**Comment by kenoir** [comment]
Part of https://github.com/wellcomecollection/platform/issues/4453

**Comment by alexwlchan** [comment]
Closing as done.
