### ISSUE TITLE
why aren't we collecting any queries with 0 results?

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/platform#4440]
As pointed by @taceybadgerbrook and @jamesgorrie, we're not seeing any searches which result in 0 results in reporting.wellcomecollection.org
They're almost definitely happening, so why aren't they appearing in the data?

**Comment by jamesgorrie** [comment]
Maybe because we're sending `totalResults = null` for `0`.

**Comment by jamesgorrie** [comment]
The PR is in - we can then run an [`update_by_query`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html) to make the `null`s `0`s.
