### ISSUE TITLE
Collection search

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#4449]
Keeping track of on what's potting with searching Collection.

When we say/imply "do" below, it is just the current implementation, ready to discuss.

When we say/imply "don't" below, we mean currently don't - not always won't.

## Where we are

We currently search for collections the same way we search for anything else.

We can also search by collection `RefNo` and collection depth (1, 2, 3).

We surface any Collection level items on the main search.

**Comment by alexwlchan** [comment]
Closing as stale.
