### ISSUE TITLE
Redirect HTTPs domains (alpha / www)

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#4462]

**Comment by pollecuttn** [comment]
@jamesgorrie Can you please update this with the latest information - I think you said you had to go into 215? Have you planned when you'll be doing that?

**Comment by alexwlchan** [comment]
This works for HTTP, but not HTTPS. Closing in favour of https://github.com/wellcomecollection/platform-infrastructure/issues/326, which tracks finishing this.
