### ISSUE TITLE
Investigate exports as CSVs

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#4467]
From Christy on behalf of the Global Digitisation Database, can we get a CSV of works that have IIIF resources along with the following metadata:

Local ID: Your own identifier, not useful for the end user, but worth knowing

Title / creator / date / publisher / fields x/y/z: Basic metadata fields that would be useful for a reader to search for texts (bearing in mind this wouldn’t be full text search), and avoiding potentially tricky fields from a licencing (OCLC) point of view like subject terms.

Master URL: The page you would send a reader to

IIIF URL: If you have one, a IIIF manifest

PDF URL: If you have one, a link to a PDF

Format X URL: If there are other common file formats, we could also point to these

Licence: E.g. CC-BY, etc

**Comment by alexwlchan** [comment]
I don't think we ever did any work towards this, so I'm closing it for now – we can open a new ticket if the question ever reappears.
