### ISSUE TITLE
Rules for construction of `provider`

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4472]
If DDS.new produces IIIF3, it needs to construct a `provider` instead of separate logo etc.

https://iiif.io/api/presentation/3.0/#provider

* What does this look like when it's just Wellcome?
* What does this look like for archive content from other repositories?

**Comment by tomcrane** [comment]
Discussed - to be dealt with when we get to it. Here's an example from the spec, for reference. We'd change the homepage and logo to wellcomecollection:

```
{
  "provider": [
    {
      "id": "https://example.org/about",
      "type": "Agent",
      "label": { "en": [ "Example Organization" ] },
      "homepage": [
        {
          "id": "https://example.org/",
          "type": "Text",
          "label": { "en": [ "Example Organization Homepage" ] },
          "format": "text/html"
        }
      ],
      "logo": [
        {
          "id": "https://example.org/images/logo.png",
          "type": "Image",
          "format": "image/png",
          "height": 100,
          "width": 120
        }
      ]
    }
  ]
}
```

And the reason for this:
https://iiif.io/api/presentation/3.0/change-log/#1212-wrap-logo-in-a-structure-with-more-information-introduce-provider-property

**Comment by donaldgray** [comment]
Everything about Wellcome that the PDF CoverPage requires must be returned in the `provider` (e.g. address)

**Comment by tomcrane** [comment]
Example of Wellcome and partner provider:

https://iiif-test.wellcomecollection.org/dash/Peek/IIIF/b24967646

How to manage this info?

In old DDS, partner logos live in a folder on a shared internal network drive.
Unlike poster images, I don't think it makes sense for them to go in the storage service - they are presentation furniture, not preservation assets.

How about they live here, in GitHub:
https://github.com/wellcomecollection/iiif-builder/tree/master/src/Wellcome.Dds/Wellcome.Dds.Server/wwwroot/partners

And you can make changes/updates with simple PRs, here:
https://github.com/wellcomecollection/iiif-builder/blob/master/src/Wellcome.Dds/Wellcome.Dds.Repositories/Presentation/PartnerAgents.cs#L10

I think this is one for @chenshaw and @aray-wellcome

**Comment by Chenshaw** [comment]
Hi Tom,

Whatever makes most sense – is there other presentation furniture stored on Github? E.g. if we have a default image to display for audio files or something along those lines.

Christy

**Comment by tomcrane** [comment]
Goof point - yeah, the audio and video placeholders, and the Wellcomecollection logo(s), can all be served along with the partner logos as static assets from the same webapp that serves the IIIF Presentation API. They then live in the iiif-builder GitHub repo and are easy to update.

**Comment by aray-wellcome** [comment]
Christy was quick! Yes, I think it's fine to have our preservation "furniture" and placeholders living in Github too. I can leave a note in our team's documentation about where it is as well and having someone on the Preservation team do a PR for us if we need to change or add a new one.

**Comment by tomcrane** [comment]
One last thing - the labels and homepage URLs here - I made a best attempt at what these should be (we only had the logo before). So they need checking!

https://github.com/wellcomecollection/iiif-builder/blob/master/src/Wellcome.Dds/Wellcome.Dds.Repositories/Presentation/PartnerAgents.cs#L10

**Comment by aray-wellcome** [comment]
Those URLs look good to me! They make sense.

**Comment by tomcrane** [comment]
I've hoovered up the logos from the shared drive and put them here:

https://github.com/wellcomecollection/iiif-builder/tree/master/src/Wellcome.Dds/Wellcome.Dds.Server/wwwroot/partners

Also the two Wellcome logos here:

https://github.com/wellcomecollection/iiif-builder/tree/master/src/Wellcome.Dds/Wellcome.Dds.Server/wwwroot/logos

If @jtweed is happy with the way these `provider` elements look then this issue could be closed.

This one has two providers, Wellcome and Glasgow University:
https://iiif-test.wellcomecollection.org/dash/Peek/IIIF/b24967646

**Comment by jtweed** [comment]
Thanks @tomcrane - looks good to me with one caveat. @jennpb is currently working on a new section page for the collections and we should probably use the URL for that when it’s available, which it’s not yet but should be before this work is finished.

**Comment by tomcrane** [comment]
Yep, it's easy to change - I just put these in as best-guess placeholders.

One related thing - in the old manifests there's no `provider` - that's a IIIF3 thing. In old manifests we convey the info in a free text metadata field, that a viewer will just display. The new `provider` gives publishers the opportunity to say a lot more about themselves _formally_ in the manifest, by adding what they want to an `Agent` type (many people wanted this).

If the material is from a third party, in the old version we have a free text metadata field that includes the partner logo, and text that says:

> This material has been provided by [blah] where the originals may be consulted.

In the new version, I've just included two providers; Wellcome first, then the third party (I can swap the order). I haven't put that old text in yet. 

Just having the two providers isn't explictly saying "if you want to look at this for real, come to Euston Rd", or "DON'T come to Euston Rd, it's actually in Glasgow - pop over the road to the station and see you later". Obviously the works page on wc.org can interpret the presence of two providers like this, and maybe that's fine for now - need to see what viewers (Mirador, UV etc) do with it.

**Comment by tomcrane** [comment]
I added the above text to the `requiredStatement` property.

https://iiif.io/api/presentation/3.0/#requiredstatement

A couple of examples:

b24967646 (from Glasgow)

```
  "rights": "https://creativecommons.org/publicdomain/mark/1.0/",
  "requiredStatement": {
    "label": { "en": [ "Attribution and usage" ] },
    "value": {
      "en": [
        "This material has been provided by The University of Glasgow Library where the originals may be consulted.",
        "<span>This work has been identified as being free of known restrictions under copyright law, including all related and neighbouring rights and is being made available under the <a target=\"_top\" href=\"http://creativecommons.org/publicdomain/mark/1.0/\">Creative Commons, Public Domain Mark</a>.<br/><br/>You can copy, modify, distribute and perform the work, even for commercial purposes, without asking permission.</span>"
      ]
    }
  },
```

b18031511_0003

```
  "rights": "https://creativecommons.org/licenses/by-nc/4.0/",
  "requiredStatement": {
    "label": { "en": [ "Attribution and usage" ] },
    "value": {
      "en": [
        "Wellcome Collection",
        "<span>You have permission to make copies of this work under a <a target=\"_top\" href=\"http://creativecommons.org/licenses/by-nc/4.0/\">Creative Commons, Attribution, Non-commercial license</a>.<br/><br/>Non-commercial use includes private study, academic research, teaching, and other activities that are not primarily intended for, or directed towards, commercial advantage or private monetary compensation. See the <a target=\"_top\" href=\"http://creativecommons.org/licenses/by-nc/4.0/legalcode\">Legal Code</a> for further information.<br/><br/>Image source should be attributed as specified in the full catalogue record. If no source is given the image should be attributed to Wellcome Library.</span>"
      ]
    }
  },
```

**Comment by tomcrane** [comment]
See https://github.com/wellcomecollection/iiif-builder/blob/master/docs/Altering-IIIF.md

Text and logos are now reasonably straightforward to change.
