### ISSUE TITLE
Which AWS estate/account does migrated DDS live in?

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4473]
* All DDS things on their own cluster even if in same AWS acct?
* Separate account, separate terraform?
* Do it in the dlcs.io account (probably not)?

Catalogue API - does it need special access/identity to avoid being regarded as a Denial of Service?

**Comment by tomcrane** [comment]
Decision is to do this in the dlcs.io account for simplicity, and keeps Digirati things together.

See https://github.com/wellcomecollection/platform/issues/4483 which should be done before going too far with this.

The DDS.new and DLCS have zero interdependency at the AWS level and should be kept isolated. DDS talks to DLCS through its public API only.

**Comment by kenoir** [comment]
Closing as I think this is resolved.
