### ISSUE TITLE
What's the best way to learn about changes in the Catalogue API?

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4477]
Changes in METS/assets come through Goobi workflow.

Bibliographic changes (e.g., update title of work) come through Sierra.

How does DDS.new learn about descriptive metadata changes, so that it can reflect them in IIIF resources?

NB given the data DDS needs to keep to manage its own work, provision of IIIF Change Discovery API is pretty simple.

**Comment by tomcrane** [comment]
Discussed earlier with @kenoir and @jtweed - have added some further thoughts.

The Sierra adaptor can provide a firehose of change notifications.
There might be A LOT of these, so listening to them needs to be lightweight and low cost.

e.g., SNS topic, take a look at the update, evaluate whether it is worth processing.
The DDS is only interested in changes that are going to change the IIIF manifest. So bibliographic rather than admin/systems changes, and even then, only changes to fields that appear in public API, or influence public API. An update to a MARC field that doesn't get reflected in IIIF isn't a change as far as DDS is concerned.

What might the message contain?
If the message doesn't contain enough info to make the evaluation, then the DDS might end up hammering the Catalogue API very hard.

* e.g., message: b12345678 has changed.
* Do we have a row in the DDS db for b12345678?
* If not, we'll ignore the message. Only Goobi can tell us about *new _digitised_* things. A Sierra event can't trigger a record creation in the DDS.
* OK, we **do** have a record for b12345678.
* Get b12345678 from the catalogue API. 
* Compare its fields with what we have. How? Did we save the catalogue API response last time so we can do a quick diff?
* If not, do we need to construct the IIIF resource anyway and then see if it's different from what we have? That's effectively the same as diffing fields because the catalogue API and the eventual manifest are not themselves diffable, you have to run the logic to see if the product is different.
* But now we've just gone and built a new manifest for every message - so we've done the hard work anyway. The only little benefit is that if the manifest is the same as the one we already had, don't save it to S3 or update the DB.

Optimisations
* Message body says whether it's digitised, so don't even have to do a SQL `EXISTS`
* Message body tells us something that helps us decide whether it contains a significant (for us) change. Don't know what that is yet.
* Storing the catalogue API response just so that we can diff it when notified of a change is not as odd as it sounds. Keep it in S3 alongside the generated IIIF resources. This isn't every b number - just the digitised ones. It's a few hundred thousand JSON blobs. Still sounds a bit weird though. Could also store it as a JSON blob in PostgreSQL. 

IIIF Collections are dynamically generated from queries to the DB so we shouldn't have cascading update issues from changes to collections. We don't have this problem in current DDS.

Other considerations

* Are there any other systems that are interested in the same sort of significant changes in the Catalogue API that DDS is interested in? If so, should this service be external to the DDS? I suspect that they are currently getting that info via OAI/PMH.
* Current DDS does not provide the IIIF Change Discovery API. New one can easily do so from the DDS DB data. But, it really wants to be able to consume something like that itself, for changes to **descriptive** metadata from the catalogue API. Without the firehose.

**Comment by tomcrane** [comment]
This sounds very brute-forcey, but it might be quicker than other alternatives.

* Use catalogue API dumps from #4820
* rattle through every line picking up digital locations (just string matching)
* compute record hash for objects with digital locations to create a big dictionary (bnumber => hash of line string json)
* get current hash dictionary via something like `SELECT identifier, record_hash from manifestations where index=0`
* compare dictionaries and enqueue any required reprocessing as appropriate
 
Note - for this to work the stored hash for a b number record must be made from a string that matches the line in the dump, not the pretty-printed API HTTP response. I think that would just be the JSON re-stringified with no whitespace.

**Comment by kenoir** [comment]
We should really be able to provide this feed by tapping the catalogue pipeline.

**Comment by tomcrane** [comment]
Addendum
Bulk reprocessing should be careful not to do unnecessary work.

We already have config for what a job should do:
https://github.com/wellcomecollection/iiif-builder/blob/master/src/Wellcome.Dds/WorkflowProcessor/RunnerOptions.cs

If we could mark a job for reprocessing but rather than a single bool flag, a set of flags for _how_ it should be re-processed, we can do bulk manifest-only refreshes without hammering the DLCS.
