### ISSUE TITLE
Configuration and secrets in DDS.new

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4482]
Those apps that stay need their config migrated from .NET xml .config files to CORE JSON formats, and adherence to policy for management of secrets.

Align management of secrets with rest of platform.

**Comment by donaldgray** [comment]
Using AWS SecretManager for managing secrets. Other 'non-secret' values can be stored in ParameterStore or `appsettings.{environment}.json`. The environments will be Staging and Production (default dotnetcore values). These are set in the relevant Terraform (see: [staging dashboard](https://github.com/wellcomecollection/iiif-builder-infrastructure/blob/master/infrastructure/staging/dashboard.tf#L49) for example).

We are using the [terraform-aws-ecs-service](https://github.com/wellcomecollection/terraform-aws-ecs-service) modules to inject secrets via the ecs containerdefinition 'secrets[].valueFrom' property. These are set as envvars and picked up by standard .netcore configuration.

**Comment by donaldgray** [comment]
@tomcrane - closing this as we have the pattern for getting secrets into containers. We can add values as and when they are migrated.
