### ISSUE TITLE
Dashboard application running on AWS, secured with Azure AD + OpenID Connect

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4497]
(Milestone)

Wellcome staff with the necessary Active Directory account privileges can use the dashboard for the same functions they currently use in the on-premise version.

**Comment by tomcrane** [comment]
Question: What cachebusting functionality will still be required from the dashboard?

**Comment by tomcrane** [comment]
@jtweed @kenoir we now have a limited but functioning dashboard app - can we get this registered so that it appears on the Azure portal? What's the process for this? 

Having it visible like this is a good spur to progressing it (you can all see what we're doing) and obviously exercises our rapid/continuous delivery approach.

From our end it will be something like this:
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp

But I assume that D&T will need to register the app(s).

We'll actually need 3 apps - prod, stage, and the hybrid version that uses prod source material (i.e., prod storage API content) with stage Dds code (e.g., staging a change in what goes into Manifests).

But one will do for now, we can start with the production one.

Question - who needs to see it?

Is it like the Goobi app that really only a few people ever use, so lives in the special Azure portal for devs? I don't know who has access to that.

Right now, I can send wt-havana dashboard links to lots of people (within Wellcome), post them on shared Slack etc, to show how the digital objects are structured or demonstrate something for discussion. This has proved fairly useful on occasion.

You can't do any damage to source data in the dashboard. It isn't the origin of any data; you can trigger reprocessing but you can't edit things. It's a window on how METS becomes IIIF. So it could have wider availability than Goobi.

**Comment by jtweed** [comment]
I think that @kenoir can create these. They should be linked to wellcome.ac.uk accounts, so that @aray-wellcome and co can access without needing dev accounts.

@aray-wellcome will know who should have access.

**Comment by aray-wellcome** [comment]
@kenoir @tomcrane The way DDS is set up now, anyone on my team can view it but only some of us had the logins that give us the ability to bust cache and force re-ingests. 

I'd like to keep the ability of everyone on my team to be able to view the dashboard, if possible so it'd be: 

Me
Harkiran Dhindsa
Branwen Lloyd-Evans
Christy Henshaw
Holly Peel
Rosie Curran
Emilie Bell
Daila Malafronte
Paul Horn
Cassidy Philips 

If access to the prod dashboard gives everyone the power to reingest and bust cache as well, that's fine.

**Comment by donaldgray** [comment]
Added basic AzureAD authentication to dashboard and deployed to AWS. Currently setup to only let Wellcome Cloud users in. There are no role/claims based restrictions yet.

PRs: 
* https://github.com/wellcomecollection/iiif-builder/pull/6
* https://github.com/wellcomecollection/iiif-builder-infrastructure/pull/2

**Comment by donaldgray** [comment]
Have example dashboard endpoint, secured by AzureAD at: https://dds-stage.dlcs.io/Home/Index/b18402768 (url will be altered eventually).

This proves that we can:
- Access Wellcome S3 buckets
- Pull secrets from SecretManager 
- Get data from DLCS
- Access deployed RDS DB
