### ISSUE TITLE
Finish IIIF Presentation 3 Library

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4500]
(v3 version of https://github.com/digirati-co-uk/iiif-model)

This might not be part of the DDS migration specifically but it is a dependency.

**Comment by tomcrane** [comment]
WIP over here - https://github.com/dlcs/protagonist/pull/17

Will be moved into its own repo (and made into a nuget package) once fully exercised in DDS and DLCS.

**Comment by tomcrane** [comment]
Going to move this back into TODO as have stopped working on it just now, not needed for immediate phase of work.

**Comment by tomcrane** [comment]
And moved to milestone 4

**Comment by donaldgray** [comment]
At this point the library will only be for creation of IIIF-Presentation and serialisation (we don't need to deserialize iiif-presentation JSON back to classes)

**Comment by tomcrane** [comment]
Marking this as closed, as we have now implemented all features - we don't need more major additions to the library.

This library will have further tweaks over time - cosmetic serialisation improvements, refinement of model - but it's working for IIIF-Builder.
