### ISSUE TITLE
Decide on and create infra/devops for iiif-builder

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4502]
- [x] Terraform for iiif-builder
 - [x] Build Mechanism
 - [x] Deployment Mechanism

with reference to https://github.com/wellcomecollection/docs/tree/master/rfcs/013-release_deployment_tracking

**Comment by donaldgray** [comment]
TF written but unable to run until we've had a catch up with Wellcome around AWS permissions.

**Comment by donaldgray** [comment]
New repository created for Terraform: https://github.com/wellcomecollection/iiif-builder-infrastructure

**Comment by donaldgray** [comment]
Build mechanism for iiif-builder is using jenkins instance that already exists for dlcs.io

**Comment by donaldgray** [comment]
Closing - there will be more infra to add in but we have some basics in the above repository and containers deploying from dlcs.io.

Dockerfile + Jenkinsfile per project will be in the iiif-builder repo. Jenkins file will build the container, push it to ECR (with known tag, e.g. :production) and then update service.
