### ISSUE TITLE
Implement logging for iiif-builder as per Firelens RFC

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4503]
https://github.com/wellcomecollection/docs/tree/master/rfcs/022-logging

**Comment by donaldgray** [comment]
This should be covered by using Wellcome's AWS modules from: https://github.com/wellcomecollection/terraform-aws-ecs-service

Will deploy a fluentbit sidecar per service.

**Comment by donaldgray** [comment]
Successfully deployed basic IIIF-builder service to ECS along with fluentbit.

Checked Elastic and can see logs coming through but the formatting is a bit off. Opened 4606 to
