### ISSUE TITLE
DDS Workflow / Sync daemons

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4504]
There are two processes that run as part of the current DDS, that need to run in ECS. They can scale as much as we like.

(Milestone 2)

WorkflowProcessor
 - Constructs b-number-level jobs in response to Goobi workflow end-state
 - Rework as daemon to run on ECS (log output via Firelens)

DlcsJobProcessor
 - TASK - the core DLCS synchronisation runner. Picks up DLCS Ingest jobs that have been left for it in the DDS Jobs database.
 - Rework as daemon to run on ECS (log output via Firelens)

**Comment by donaldgray** [comment]
See ticket #4629 for basic deployment.

**Comment by donaldgray** [comment]
PR for code changes: https://github.com/wellcomecollection/iiif-builder/pull/24
