### ISSUE TITLE
iiif-builder stub JSON endpoints

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4505]
(Milestone 3)

Milestone 3 rounds off the first phase of the work, by providing stubs for some of the skeleton services that will be worked on in the next phase. It should be quick - getting the routing to IIIF endpoints with the identifiers we want, but instead of returning the JSON-LD for a IIIF resource, it returns the JSON representation of the METS resource (by serialising the model already in use). This then gives us something to work on, gradually changing into IIIF.

**Comment by tomcrane** [comment]
PR: https://github.com/wellcomecollection/iiif-builder/pull/25

**Comment by donaldgray** [comment]
This has been deployed, see: https://iiif-test.wellcomecollection.org/presentation/b29718697

@tomcrane - can this now be closed?
