### ISSUE TITLE
Set up Archivematica upload for archivists

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4522]
To help support born-digital cataloguing, we want to let the archivists begin to upload packages to Archivematica.

We'll need to set up appropriate access keys for use with the S3 client app they have access to.
And then work with @aray-wellcome to get them set up.

**Comment by alexwlchan** [comment]
I've given the archivists some instructions and AWS access keys. I may need to do some troubleshooting, but I consider this functionally "done" once the Terraform is merged.
