### ISSUE TITLE
Create data source for tracking breadth of catalogue accessed

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#4547]
Currently we're using the search relevance "Search result selected" metric to infer how much of our catalogue is being accessed (being the main entry of people getting to works).

We should start collecting work pages being accessed to be a more accurate indication of this.

**Comment by taceybadgerbrook** [comment]
Are you suggesting creation of a new index for work pages accessed by more than "Search result selected"? What would this look like?

**Comment by jamesgorrie** [comment]
@taceybadgerbrook would the first thing to collect be "What works have been accessed"?

Currently we will track the ID of the work. What other data about the work do you need?

e.g.
```ts
{
  "event": "Work viewed",
  "data": {
    "id": "njfu764k"
  }
}
```

**Comment by taceybadgerbrook** [comment]
I'm linking this to #4005 assuming this new index is the same as the index for conversion.

In addition to workId, I'd also like anonymousId and sessionId to be collected (just in case we finally stop collecting anonymousId.)

And if access is being compared to taking a book down from the shelf to look at it, should we also include clicking on archive tree? @jennpb what do you think?

**Comment by taceybadgerbrook** [comment]
@jamesgorrie Jenn's recommended that "access" stays defined as search result selected and not to include navigating archive trees.

**Comment by taceybadgerbrook** [comment]
So if you track workId and search result selected, that's all I need.
