### ISSUE TITLE
Merging causes problems with WI redirects

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#4552]
Collections & Research staff report that Sierra records they edited (fields: 245, 246 1 and 500) lost their images on wc.org after their Sierra edit. None of those fields are links to the image.

For example:
http://libsys.wellcomelibrary.org/record=b1187988
You can see the thumbnail on the record, but when you click it you get "We couldn't find anything that matched V0039617. Please try again."
https://wellcomecollection.org/works?query=V0039617&wellcomeImagesUrl=/indexplus/image/V0039617.html

You can find the record on wc.org by searching for the title, but there is no associated image.
https://wellcomecollection.org/works?query=A%20young%20woman%20stands%20with%20a%20sheep%20by%20her%20side

More of those affected records (these are a few they've given me, there are more still):
30148i - http://libsys.wellcomelibrary.org/record=b1187988
32518i - http://libsys.wellcomelibrary.org/record=b1190388
32532i - http://libsys.wellcomelibrary.org/record=b1190369
32536i - http://libsys.wellcomelibrary.org/record=b1190373
32542i - http://libsys.wellcomelibrary.org/record=b1190379
32546i - http://libsys.wellcomelibrary.org/record=b1190383
32549i - http://libsys.wellcomelibrary.org/record=b1190386
32625i - http://libsys.wellcomelibrary.org/record=b1190462

**Comment by pollecuttn** [comment]
It looks like the toggle 'Entire catalogue search' needs to be on, I presume C&R are using it or they wouldn't see the wc.org record with no image.

**Comment by jamesgorrie** [comment]
Looking into this, what seems to be happening is the [redirect for the Miro work is bring created](https://api.wellcomecollection.org/catalogue/v2/works/wgq5uw5b) but the identifier for that work is not being added to the target.

🔍 continues.

**Comment by jamesgorrie** [comment]
Looking at the marc data of all of these ([e.g](https://search.wellcomelibrary.org/iii/encore/record/C__Rb1190462?marcData=Y)) - there is data like `(OCoLC)808200303` in the 035 field.

[Currently we just assume that 035 will be a calm identifier](https://github.com/wellcomecollection/catalogue/blob/5bda039aaadace5e5f7e52378baaae85cbf4fcbc/pipeline/transformer/transformer_sierra/src/main/scala/uk/ac/wellcome/platform/transformer/sierra/transformers/SierraMergeCandidates.scala#L108-L123), which is wrong. This was causing the merger not to work properly.

Fixing that should help.
