### ISSUE TITLE
Changes to bag reporting

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4557]
Some tweaks to bags as ingested into Elasticsearch for reporting:

- [x] Change `payloadFiles` to `files` to match the API
- [x] Remove `payloadStats.*`
- [x] Add `suffix` to files
- [x] Add the `v` prefix to version number
- [x] Add `location` and `replicaLocations`
- [x] Add `info.*` for flattened bag info

We're also seeing an error that we need to get the bottom of:

`The length of [payloadFiles.name] field of [digitised/b21726000] doc of [storage_bags] index has exceeded [1000000] - maximum allowed to be analyzed for highlighting. This maximum can be set by changing the [index.highlight.max_analyzed_offset] index level setting. For large texts, indexing with offsets or term vectors is recommended!`

**Comment by kenoir** [comment]
Are we sure we want to remove `payloadStats.*` ? It might not be useful for aggregating across all bags but it might be useful for viewing that info on a single bag.

**Comment by kenoir** [comment]
> Add the v prefix to version number

The version needs be present as an integer currently in some form as it is used by Elasticsearch to ensure older bags don't overwrite newer bags. 

We can have an additional field, or have the version as an object: 

```json
{ 
   "ordering": 1,
  "id": "v1"
}
```

**Comment by alexwlchan** [comment]
I agree about keeping payload stats; what we could do is move them to the top level – rather than `files`, just have `payloadFileSize`, `payloadFileCount`, since there's not a similar block.

I'd vote for having both forms of the version. Sorting a number alphanumerically gets fiddly (e.g. does "v10" sort before or after "v2"?)
