### ISSUE TITLE
Bag verifier should tag objects + read checksum tags

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4562]
Part of #4413.

We modify the bag verifier to use S3/Azure tags for verification:

- [x] After the bag verifier verifies an object, it adds the tag `Content-SHA256` to the checksum value of this object
- [x] Before reading an object, the bag verifier looks for this tag. If the tag is present, it trusts it is correct and skips re-reading the object
- [x] Rename some of the internal classes to be less confusing (https://github.com/wellcomecollection/storage-service/pull/578)

We modify the replicator:

- [x] Don't copy tags when replicating objects (https://github.com/wellcomecollection/scala-storage/pull/135, https://github.com/wellcomecollection/storage-service/pull/575)
- [x] In the replicator, test that tags don't get copied (https://github.com/wellcomecollection/storage-service/pull/585)

We modify the S3 object tagger:

- [ ] Modify tags in-place, don't replace them (https://github.com/wellcomecollection/storage-service/pull/562)

**Comment by kenoir** [comment]
We want to be very sure how tags behave in S3 with Glacier lifecycled objects.

**Comment by alexwlchan** [comment]
> We want to be very sure how tags behave in S3 with Glacier lifecycled objects.

I'd be shocked if Glacier doesn't preserve tags when you lifecycle to Glacier. But to be absolutely sure, I've put a small object in wellcomecollection-storage-infra with a tag (Source=MyDesktop) and a lifecycle rule to send it to Glacier after 1 day.
