### ISSUE TITLE
Archive collection search relevance

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#4568]

**Comment by pollecuttn** [comment]
@jamesgorrie can this also be non-archive collection search relevance to include Tacey's example of 'origin of species'. I would expect to see a lot of [these](http://catalogue.wellcomelibrary.org/search/X?origin+of+species) showing up at the top of the search results but I'm not seeing them at https://wellcomecollection.org/works?query=origin%20of%20species

**Comment by jamesgorrie** [comment]
Going to close this as it's been usurped by the search project and archive project.
