### ISSUE TITLE
Ensure a password management solution is available to digital engagement

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4580]
In order to ensure credentials are securely available when required we should have a solution for storing and dispensing service credentials. 

For services owned by digital engagement (social media/soundcloud/analytics things/elastic cloud).

We should look to use a solution provided by D&T _if it is fit for purpose_.

**Comment by alexwlchan** [comment]
Also shared AWS keys.

**Comment by alexwlchan** [comment]
Closing as stale.
