### ISSUE TITLE
How do we do authentication between Azure and AWS?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4582]
The problem: we have data in AWS. We want to replicate that data to Azure.

![crosscloud](https://user-images.githubusercontent.com/301220/84889028-1908ae80-b090-11ea-98d4-5c9ff94f98f9.png)

How do we set up the auth to let something:

1. Read from AWS
2. Write to Azure

?

**Comment by alexwlchan** [comment]
Some notes from earlier:

* We need a service that can read from AWS and write to Azure

  (This will initially run in AWS rather than Azure, because we don’t want to do the work to set up compute running inside Azure.)

* We want to be able to revoke credentials immediately if they get leaked

  (You can create ad hoc SAS URIs that allow access to an individual blob or container, but they expire after a fixed period. You can’t revoke them without rotating the account-level storage key)

**Comment by kenoir** [comment]
We will likely want a set of "stored access policies" (SAP) associated with a container in Azure Blob storage.

A SAP allows you to create SAS tokens that can then later be invalidated by revoking the associated SAP later.

```console
# Create SAP
> az storage container policy create --account-name wellcomecollectionstage --container-name replica --name testpolicy2 --permissions lr
# Generate SAS from SAP
> az storage container generate-sas --name replica --policy testpolicy2 --account-name wellcomecollectionstage
```
