### ISSUE TITLE
Historical library merging questions

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/platform#4583]
- Are we sure about L/M?
- Is "historical library" the best name for these works?
- What do we do with existing works that would now be suppressed?
- Do we still create images from the suppressed works?

**Comment by jtweed** [comment]
Some answers to the above.

- Historical library images is a good term for these.
- We should make sure that we are accounting for spaces and non-zero padded Miro IDs in 089
- We should keep M, they should not be suppressed if they do not merge.
- Are there identifiable number ranges in the L images that are not merged?
- If so, we may be able to suppress certain ranges. If not, they should not be suppressed.
- If we do end up suppressing any L images, they should be put into Tandem Vault.
