### ISSUE TITLE
How do we migrate all the existing bags to Azure?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4589]
We have ~260,000 odd bags already in the storage service, which only exist in S3 and Glacier. How do we get them to Azure?

**Comment by alexwlchan** [comment]
Here's my proposal:

1. Deploy a replicator/verifier pair that can store Azure replicas. Update the replica aggregator to expect three replicas.

    All newly-ingested bags are now being stored in Azure. Get this up and running, watch it ingest new bags, leave it for a few days.

2. Modify the bag register (temporarily) so that it can *replace* an existing manifest, if it can't already.

    I haven't checked, but I think it would throw an error if you ask it to register a bag that it already knows about. This is a temporary fix that means it would be able to create new manifests if it got a new message from the replica aggregator.

3. Send messages to the Azure replicator of the following form:

    ```
    {source => (warm S3 replica), destination => azure}
    ```

    One for every bag in the replica aggregator database that only has a Glacier replica.

    This will trigger a replication + verification of the bag in Azure. Then the replica aggregator counts the third replica, sends that to the bag register, and it creates a new storage manifest that includes both replicas.

Repeat step 3 until every bag known to the register/aggregator has a replica in Azure.

**Comment by kenoir** [comment]
This sounds sensible. My reading is that we are not creating "new versions" of the bags to do this and the mechanism you describe will overwrite existing storage manifests at their existing version.

**Comment by alexwlchan** [comment]
> My reading is that we are not creating "new versions" of the bags to do this and the mechanism you describe will overwrite existing storage manifests at their existing version.

Yes. Normally each version of a storage manifest is immutable after it's written, but we want to temporarily change that.

(Or add a mechanism by which the register can add a replica to an existing manifest without regenerating the whole thing, but that seems like more work unless we routinely plan to add new replicas.)

**Comment by alexwlchan** [comment]
BTW, the overarching bent here is to do as little jiggery-pokery as possible. We push as much work as possible into the pipeline apps, to minimise duplicated effort and avoid mistakes.

**Comment by alexwlchan** [comment]
I realised last night that this might not be what we want.

Having the bag register recreate the manifests from scratch will reset the created date, which probably isn't what we want – it would make all bags appear to be created as they were replicated to Azure. We want to preserve the original creation date, right? It's the creation date of the bag, not the JSON manifest?

As a data point: whenever I've tweaked the manifests in the past, I've preserved the original creation date.

**Comment by alexwlchan** [comment]
@weco-bot Yes, we might need some custom code that reads the existing storage manifest and just appends to the replica rather than recreating it from scratch.

**Comment by alexwlchan** [comment]
Alice and I discussed this at some length after planning today; a revised plan:

1. We get to a point where we can reliably ingest new bags that are replicated, verified and tagged in Azure.
2. We create a new instance of the bag register (the “Azure backfill register”), which writes bags to an empty VHS.

    - It receives updates from the replica aggregator
    - Newly-ingested bags will be written to the live bag register (and thus available in the external API) and copied to the empty VHS
    - This Azure backfill register does _not_ send updates to the ingest tracker – it may register a bag before it’s available in the external API, and we don’t want to break the success->callback->get bag flow for external users.

3. We give the replicator/verifier temporary permissions to read from the primary storage bucket.

4. Once we're happy the Azure backfill register is storing bags successfully, we send messages to the replicator telling it "replicate bag from (warm storage) to (azure)". This bag passes through the replicator, verifier and replica aggregator as normal.

   - When a backfilled bag reaches the live bag register, it will fail, because it doesn't know how to replace the existing manifest
   - When a backfilled bag reaches the Azure backfill register, it will create a new manifest in the empty VHS

   Eventually the two VHS instances will be in sync – each bag will have a manifest in both VHS instances.

5. We run a script that copies the creation date from (old VHS) to (new VHS).

6. We modify the live bag register to point at the (new VHS), which now has a record of every bag with a correct creation date, and we turn off the Azure backfill infra. We may reindex the bags into Elasticsearch at this point.

New bags will be replicated to Azure automatically, and we gradually backfill the existing archive without interrupting new ingests or bags.

![azure_backfill](https://user-images.githubusercontent.com/301220/90026374-2072bf80-dcaf-11ea-9f2b-bc27a1aacfc9.png)

**Comment by alexwlchan** [comment]
One note:

The bag register can only register bags in order – e.g. you can only register v1 before you register v2.

We’ll need to order the messages sent to the replicator accordingly.

**Comment by alexwlchan** [comment]
Closing in favour of #4589 – we've got an approach that we're all happy with, I think.
