### ISSUE TITLE
The verifier should check the replicated bag matches the original bag

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4594]
Currently the post-replica verifier will tell you "this bag is internally consistent", but it doesn't check if it bears any resemblance to the bag you started with. If the replicator wrote the same bag over and over under every identifier, the verifier wouldn't notice.

To get round this, the bag replicator compares the tag manifest of the original and replicated bag. We should push that logic into the verifier.

As part of the verifier refactor for #4414

**Comment by alexwlchan** [comment]
Rough plan:

We have a trait BagVerifier, which has a single S3 implementation:

```scala
```

**Comment by kenoir** [comment]
Very clear. Good plan.

**Comment by alexwlchan** [comment]
Had another look at this, realise we never actually send the location of the unpacked bag from the replicator. Oops.

**Comment by alexwlchan** [comment]
This is deployed and working. 🎉
