### ISSUE TITLE
Hostnames for migrated iiif-builder (DDS) and Dashboard

### ISSUE THREAD

**Issue by donaldgray** [wellcomecollection/platform#4603]
If all the migrated DDS is to live at xxx.wellcomecollection.org, what's xxx?
For public facing URLs there are two applications to consider:

- The Dashboard (not public - similar to Goobi in that respect)
- The API (IIIF Manifests, Search API, text resources etc)

Then there is also the DLCS serving assets and Image API at dlcs.io, which also should move to something.wellcomecollection.org.

Then there are staging/test versions of the DDS and Dashboard.

There is already iiif.wellcomecollection.org, which is where Loris lives. It can't all live under there though, without some reorganisation.

https://github.com/wellcomecollection/platform/issues/4541 covers path design within the DDS
https://github.com/wellcomecollection/platform/issues/4487 is about the different configurations of DDS and dashboard that are needed.

As a straw person, how about:

{environment}.iiif.wellcomecollection.org/iiif/{dds-api-paths} - for manifests, search api, text etc
{environment}.iiif.wellcomecollection.org/assets/{dlcs-paths} - for Image API, video
{environment}.dds.wellcomecollection.org/{dashboard-paths} - for staff-only dashboard

...where {environment} is missing for production.
...and /iiif, /assets are used to route to DLCS/DDS (and NOT Loris) under iiif.wellcomecollection.org

This may be a bit tricky to set up Route53 for if in multiple accts.

**Comment by tomcrane** [comment]
One for @jtweed - tidied up comment

**Comment by kenoir** [comment]
We tend to do: `thing-env.wellcomecollection.org`

**Comment by kenoir** [comment]
This is how we present storage / catalogue APIs

![api wellcomecollection org](https://user-images.githubusercontent.com/953792/86233648-a4546a80-bb8d-11ea-9d6b-24763428fdf3.png)

**Comment by jtweed** [comment]
Thinking something like the following, submitting for discussion not as a decree...

### For manifests, search api, text etc

```
iiif.wellcomecollection.org/presentation
-> {DDS}/iiif
```

```
iiif.wellcomecollection.org/search
-> {DDS}/annoservices
```

```
iiif.wellcomecollection.org/presentation/collections
-> {DDS}/service/collections
```

```
api.wellcomecollection.org/text/v1
-> {DDS}/service
```

### For Image API, video

```
iiif.wellcomecollection.org/image/[A-Z]
-> {loris}
```

```
iiif.wellcomecollection.org/image/[a-z]
-> {dlcs}/iiif-img/wellcome/5
```

```
iiif.wellcomecollection.org/thumbs/{id}/
-> {dds}/posterimages/{id}/
```

```
iiif.wellcomecollection.org/thumbs
-> {dlcs}/thumbs/wellcome/5
```

```
iiif.wellcomecollection.org/av
-> {dlcs}/iiif-av/wellcome/5
```

```
iiif.wellcomecollection.org/pdf
-> {dlcs}/pdf/wellcome/pdf-item
```

### For staff-only dashboard

```
{name}{-stage}.wellcomecollection.org/{dashboard-paths}
```

**Comment by tomcrane** [comment]
While we're here we should widen the discussion to paths, too.

If I'm looking at https://wellcomecollection.org/works/km3uczhf, should I be able to hack the URL to get the manifest? Should there be harmony in URLs across the IIIF representation and the web page? While the DDS will continue to use the b number internally, as that's driving the digitisation, it could still _respond_ to the work identifier. The work identifier could be canonical.

e.g., 

iiif.wellcomecollection.org/presentation/km3uczhf gives me the manifest.
iiif.wellcomecollection.org/search/km3uczhf gives me the search API endpoint.

B numbers in that slot could redirect to the work id version of the URL - 
iiif.wellcomecollection.org/presentation/b28047345 => iiif.wellcomecollection.org/presentation/km3uczhf

Another note about collections...
The new path scheme should drop the /manifest/ element of the path.

The IIIF resource for a given b number / work identfier is usually a manifest but not always a manifest.
Chemist and Druggist is obviously not a Manifest.
Neither are multi-volume works. They are Collections.

The speculative consumer of endpoints doesn't know this, so if you ask for 

https://wellcomelibrary.org/iiif/b18031511/manifest

... you get redirected to 

https://wellcomelibrary.org/iiif/collection/b18031511

If the URL of the IIIF resource that represents this digitised item instance of the work doesn't mention the Type of resource it is, then this redirect isn't required. 

iiif.wellcomecollection.org/presentation/ysmqsfhg is a IIIF Collection
iiif.wellcomecollection.org/presentation/km3uczhf is a IIIF Manifest

(btw being **flexible** about the mapping between an intellectual object that has been described and assigned an identifier, and the IIIF resource that represents it, is a hill I will die on...)

This leaves the door open to providing, say, a reference to a IIIF Range as the representation of a work (e.g., a catalogued article in a periodical).

**Comment by jtweed** [comment]
Broadly agree with that @tomcrane - would be nice if we could do that as part of this, but I think it might depend on both how long the basic migration takes and also any downstream impacts of changing the services.

**Comment by tomcrane** [comment]
From conversation with @donaldgray 

Staff-only dashboard

`{name}{-stage}.wellcomecollection.org/{dashboard-paths}`

There are three combinations that are commonly used.

iiif-dash.wellcomecollection.org - this is production - uses production storage, production DDS and DLCS space 5.
iiif-dash-stage.wellcomecollection.org - this is pure stage - uses staging storage, staging DDS, DLCS space 6.
iiif-dash-test.wellcomecollection.org - a mixed environment - production storage, staging DDS, DLCS space 6

(struggling with sensible names for these... iiif-dash-prod-stage...?)

The two staging environments could be on autoscaling groups that normally are set to 0, and only spin up when there is demand for them. This does mean that if you need to do something on them you will need to make a cup of tea between first request and actually getting something. Then they could go to sleep after, say, a few hours inactivity.
This fits well with the kind of usage that these get - a concentrated burst of testing for a day or two and then nothing for ages.

If we can do that without any further manual intervention, just the request trigger, that would make it easier for users of the dashboard.

The production one would be always available.

**Comment by donaldgray** [comment]
>The two staging environments could be on autoscaling groups that normally are set to 0, and only spin up when there is demand for them. This does mean that if you need to do something on them you will need to make a cup of tea between first request and actually getting something. Then they could go to sleep after, say, a few hours inactivity.
This fits well with the kind of usage that these get - a concentrated burst of testing for a day or two and then nothing for ages.

This doesn't look to be cleanly doable. One option would be to scaleup services if a request came into ELB but most metrics are either too coarse (any request to ELB) or need a target to respond. Found a [forum post](https://forums.aws.amazon.com/thread.jspa?threadID=305409) asking for exact behaviour but not yet available. 

Will create a static mixed env for now, can look at timebased scaling e.g. (overnight + weekends) or something manually triggered.

**Comment by tomcrane** [comment]
Back to hostnames (https://github.com/wellcomecollection/platform/issues/4603#issuecomment-653121630)

It would be good to get this done and routed through now even if we just stub out anything not yet implemented.

```
iiif.wellcomecollection.org/presentation
-> {DDS}/iiif
```

In general we'll use the same path within the DDS, so `iiif.wellcomecollection.org/presentation -> {DDS}/presentation` (mostly to avoid confusing ourselves). This is trivial routing within the DDS app. I'll make some stubs for these paths so there'll be something waiting for the routing.

Question though...

In the above we have the same subdomain going to different endpoints in different AWS accounts, based on path routing. 
Is that possible? Where do these rules live? Loris is not in the same managed AWS estate as DDS in dlcs-io. Does that matter?

For `iiif.wellcomecollection.org/image/...` , something a bit trickier that might not be possible in AWS Application Load Balancer (if that's where the rules live). You can't use regexes - https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-update-rules.html - only /path/*.

Other than that they all make sense. The non-DLCS paths are straightforward but we'll need to give some thought to the DLCS paths. Is there URL-rewriting going on? 

```
iiif.wellcomecollection.org/image/[a-z]
-> {dlcs}/iiif-img/wellcome/5
```

To clarify:

Public 
```
https://dlcs.io/iiif-img/wellcome/5/b28047345_0032.jp2/info.json`
https://dlcs.io/iiif-img/wellcome/5/b28047345_0032.jp2/full/max/0/default.jpg`
```

becomes
```
https://iiif.wellcomecollection.org/image/b28047345_0032.jp2/info.json
https://iiif.wellcomecollection.org/image/b28047345_0032.jp2/full/max/0/default.jpg
```

For _production_, iiif-img/wellcome/5 are all redundant path components underneath iiif.wellcomecollection.org/image/.
Do we rewrite the URLs up at the routing level (rules would be aware that space 5 is production and space 6 is stage)? Do we make the DLCS itself respond to these paths? The latter is possible but then inconsistent with its public API. 


Public 
```
https://dlcs.io/iiif-img/wellcome/6/b28047345_0032.jp2/full/max/0/default.jpg`
                               nb ^
=>
https://iiif-stage.wellcomecollection.org/image/b28047345_0032.jp2/full/max/0/default.jpg
            nb ^ 
```

(Or should we keep the space id (5 or 6) as part of the public URL?)

**Comment by tomcrane** [comment]
mentioned on standup ^ to discuss with @jtweed and @kenoir and @donaldgray

**Comment by kenoir** [comment]
>In the above we have the same subdomain going to different endpoints in different AWS accounts, based on path routing.
> Is that possible? Where do these rules live?

We would likely want to point the `iiif.` subdomain to a CloudFront distro in the platform account and hand off to origins (that could be spread across various AWS accounts) there.

**Comment by kenoir** [comment]
> (Or should we keep the space id (5 or 6) as part of the public URL?)

I'd prefer not to do that and use the subdomain as you describe.

**Comment by tomcrane** [comment]
Putting this all behind Cloudfront will be great - this replaces the DMZ reverse proxies that sit in front of the current DDS, and also provides a reverse proxy cache for the DLCS which it currently doesn't have.

Subdomains - we still need to think of names.
iiif and iiif-stage, obviously - but which configuration does iiif-stage represent, and what do we call the other configuration?

iiif <= production
iiif-stage <= stage DDS, stage storage API, DLCS space 6 - no live data sources or destinations
iiif-test <= stage DDS, production storage, DLCS space 6 - **live data sources**, but no live destinations

Still can't think of a good name for the last one.
Other combinations are occasionally required, but we could repurpose the last one for variations as needed.

Actions - I would like to get this configuration up as soon as we can, to uncover any issues. We haven't run DLCS' IIIF Auth implementation behind a CDN, for example. There's nothing waiting to stop us deploying all the configs, making sure they can sit alongside current live Loris delivery, etc. As part of the catalogue spelunking exercise we can prepare some DDS API endpoints that dump source data, that we later replace with IIIF Presentation 3.

**Comment by tomcrane** [comment]
Update after standup

Cloudfront for new DDS is fine as long as the hand-off to various origins is based on the first path segment.
But looks like you can't do complex URL-rewriting in Cloudfront directly:
https://linuxacademy.com/guide/19955-url-rewriting-in-aws-cloudfront/

That approach seems inappropriate for large numbers of tile requests. So some of the above rules can't be done in Cloudfront.

Maybe the DLCS orchestrator should be updated to handle _aliases_ for the `operation/customer/space` path segment triplet, where the alias can be a combination of host name and path segment.

hostname: `iiif.wellcomecollection.org`, path segment `image`: => `iiif-img/wellcome/5`
hostname: `iiif-stage.wellcomecollection.org`, path segment `image`: => `iiif-img/wellcome/6`

(this would need a bit of DLCS development obviously, in orchestrator)
Also the Cloudfront-proxied addresses should run alongside the "native" addresses to allow a transition.

Further comments on @jtweed suggestions (https://github.com/wellcomecollection/platform/issues/4603#issuecomment-653121630)

- The Loris/DLCS choice between `image/[A-Z]` and `image/[a-z]` - can you do that in Cloudfront? If not, where would that happen?
- Note that one of them is an api.wellcomecollection route, not iiif, just to catch you out when setting them up.
- The catch-all unmatched route from iiif.wc.org - suggest that goes to the DDS rather than Loris or DLCS. More flexible for new additions and changing things around.
- If DDS is the catch-all, what other dlcs.io paths need to be set up? Named queries, auth endpoints etc.
- This is only for dlcs.io, not api.dlcs.io which the DDS carries on using as before.

@donaldgray @jtweed @kenoir

**Comment by tomcrane** [comment]
```iiif.wellcomecollection.org/image/[A-Z]
-> {loris}
iiif.wellcomecollection.org/image/[a-z]
-> {dlcs}/iiif-img/wellcome/5
```

The problem with this is that some DLCS identifiers start with a capital B because the Goobi filename starts with a capital B.
If we know that Loris ids never start with b/B then we're OK and the Cloudfront Regex can be aware of it.

**Comment by tomcrane** [comment]
# Hostnames proposal from call

Don't have separate hostnames for dashboard, use first path segment `/dash`
(requires a little work in dashboard but not a huge amount - also remember static wwwroot content)

In front of DDS/IIIFBuilder **and** DLCS **and** Dashboard:

- iiif.wellcomecollection.org
- iiif-stage.wellcomecollection.org
- iiif-test.wellcomecollection.org

The Dashboard doesn't have to go through Cloudfront. Probably shouldn't, Goobi doesn't. 
But... does going through Cloudfront for Dash cause any problems for the Azure SSO (apart from adding another signin redirect URL)?

## Origins

In all cases the path is preserved in full, no removing first segment, or rewrites.

We have four origins:

* (Loris) 
* dlcs.io - existing DLCS
* iiif.dlcs.io - new DDS (IIIF-Builder)
* dds.dlcs.io - new dashboard

For the last two, we also have stage and test variants that correspond to the iiif-*.wc.org hostnames in the above list:

* iiif-stage.dlcs.io, iiif-test.dlcs.io
* dds-stage.dlcs.io, dds-test.dlcs.io

(Loris may have similar, too)

## Rules

(I haven't put in the equivalents for the -stage and -test, to avoid clutter below, but they will be obvious)

This rule first!

- `image/[VLMBNAWS]00.+`  -> Loris

Then a special rule for poster images, which don't go to DLCS, and b number thumbs, which the DDS redirects to the right thumbnail:

`thumbs/b[0-9x]{8}$` -> **iiif.dlcs.io**

Then:

`image/(.+)`
`thumbs/(.+)`
`av/(.+)`
`pdf/(.+)`

all to -> **dlcs.io**

Then:

`dash(.*)` -> **dds.dlcs.io**

Then, the fall through:

(.*) -> **iiif.dlcs.io**

There is also another rule to be added for `api.wellcomecollection.org`:

`text/v1(.+)` -> **iiif.dlcs.io**

(with -stage and -test too). This path will also be handled by the catch-all for iiif, so we can test without this additional entry.

## Examples

 * iiif-stage.wellcomecollection.org/dash/manifestation/b12345678 => dds-stage.dlcs.io/dash/manifestation/b12345678
 * iiif.wellcomecollection.org/thumbs/b12345678 => iiif.dlcs.io/thumbs/b12345678
 * iiif.wellcomecollection.org/thumbs/b12345678_0001.jp2 => dlcs.io/thumbs/b12345678_0001.jp2
 * iiif-test.wellcomecollection.org/presentation/b12345678 => iiif.dlcs.io/presentation/b12345678
 * iiif.wellcomecollection.org/image/B0000003 => (Loris) 
 * iiif.wellcomecollection.org/image/B1000003 => dlcs.io/image/B1000003 (fake but correct)
 * api.wellcomecollection.org/text/v1/b28047345/annotations/b28047345_0014.jp2 => iiif.dlcs.io/text/v1/b28047345/annotations/b28047345_0014.jp2

**Comment by tomcrane** [comment]
This is the last issue open in Milestone 1 - now just needs some testing before we close.

**Comment by tomcrane** [comment]
@kenoir I should have spotted this in the tf PR yesterday, but the default rule is going to the wrong origin:

https://github.com/wellcomecollection/platform-infrastructure/pull/39/files#diff-c497ad0da26a59c58b8403fa809325c6R76

This should be `target_origin_id = "iiif"`

e.g., handle /presentation/b12345678

**Comment by kenoir** [comment]
> This should be target_origin_id = "iiif"

If updated the distro to reflect this.

**Comment by donaldgray** [comment]
Setup ELB rules and tested:

* iiif-stage.wellcomecollection.org/dash -> dashboard
* iiif-stage.wellcomecollection.org/ -> iiif
* iiif-test.wellcomecollection.org/dash -> dashboard
* iiif-test.wellcomecollection.org/ -> iiif

**Comment by tomcrane** [comment]
Ready to close this?

I can raise a separate issue for the DLCS work required to handle these new paths, which can be done later.
(Note... in an ideal world we would only include this feature in to our re-write of Orchestrator in https://github.com/dlcs/protagonist but that may be too far off).

**Comment by donaldgray** [comment]
Yeah, think it's good to go. Also tested production paths :

* iiif.wellcomecollection.org/dash -> dashboard
* iiif.wellcomecollection.org/ -> iiif
