### ISSUE TITLE
S3 Buckets for iiif-builder 

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4623]
These replace the various network file shares the current DDS uses for building and caching.
We don't need all of the existing ones, because we're not building and storing descriptive metadata.

But we do need:

- [x] wellcomecollection-iiif-storagemaps
- [x] wellcomecollection-stage-iiif-storagemaps

These are used to resolve relative paths in METS files to absolute S3 locations in storage. 

- [x] wellcomecollection-iiif-presentation
- [x] wellcomecollection-stage-iiif-presentation

This is where generated IIIF Manifests and Collections will be stored.

- [x] wellcomecollection-iiif-text
- [x] wellcomecollection-stage-iiif-text

We could have just these text buckets, and store all text-related assets in here under three distinct top-level key paths:

- `/raw` - full plain text in zipped and unzipped form, for download
- `/textmaps` - for each manifest, map of words to text (used for Search API)
- `/annotations` - pregenerated annotation lists, for all the images/figures in a work, and all the text in a single annotation list.

...rather than have three separate buckets for these.

Note that at the moment, the per-page text annotation list is generated on the fly, by transforming the METS-ALTO from the storage service in real time. This can continue - there's no real benefit to storing 20-30m files in two different forms (ALTO in storage, annotations in IIIF) when the transformation from ALTO to annotations is computationally low cost.

There are a few other things related to presentation but I think they can go in the presentation bucket, for example, IssueCache is used to map the issues of Chemist and Druggist but doesn't need to live in its own bucket.

**Comment by tomcrane** [comment]
@kenoir do these suggested bucket names conform to your conventions?

**Comment by kenoir** [comment]
Looks fine to me. @alexwlchan and @jtweed might have opinions.

**Comment by jtweed** [comment]
Fine with that.

**Comment by alexwlchan** [comment]
Typo in `wellcomesollection-stage-iiif-presentation`, but otherwise LGTM. 👍

**Comment by tomcrane** [comment]
Fixed, I blame my bruised fingers.
@donaldgray can add these to the terraform.

**Comment by donaldgray** [comment]
All of the `wellcomecollection-stage-iiif*` buckets created. 

There is no Terraform for the production environment yet so moving this back into 'To do' and these can be created along with the Prod environment.

**Comment by tomcrane** [comment]
A thought about versioning in these buckets - they don't need it, and shouldn't have it.
Only the latest version of any key is of any interest.

**Comment by donaldgray** [comment]
Implemented as part of #4684
