### ISSUE TITLE
Setup Wellcome user access for new DDS

### ISSUE THREAD

**Issue by donaldgray** [wellcomecollection/platform#4630]
Copied from comment by @aray-wellcome on #4497 (4497 was configuring dashboard to run in AWS):

> The way DDS is set up now, anyone on my team can view it but only some of us had the logins that give us the ability to bust cache and force re-ingests.
>
> I'd like to keep the ability of everyone on my team to be able to view the dashboard, if possible so it'd be:
>
> Me
> Harkiran Dhindsa
> Branwen Lloyd-Evans
> Christy Henshaw
> Holly Peel
> Rosie Curran
> Emilie Bell
> Daila Malafronte
> Paul Horn
> Cassidy Philips
>
> If access to the prod dashboard gives everyone the power to reingest and bust cache as well, that's fine.

**Comment by tomcrane** [comment]
I think this is close-able as membership of the AD group for access is controlled by D&T? The mechanism works.
