### ISSUE TITLE
Improved deployment tracking

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4637]
## Description

As the platform has evolved, the number of services it consists of and the number of developers working on it has increased. This has made managing deployments and the dependencies between services more difficult. We want to rebuild our deployment tools to make them easier and more reliable to use.

## Objective

Better preservation of our digitised and born-digital collections

## Measures

- Is it easier and more reliable to deploy services?

- Are we more aware of what gets deployed where and when?

## Initiatives

- Rebuild existing deployment tooling

- Use new deployment for all services

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4845124

**Comment by kenoir** [comment]
Closing as done.
