### ISSUE TITLE
Reduce size of born-digital metadata

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4639]
## Description

The METS files created by Archivematica to describe the contents of AIPs can be extremely large in size, especially when an AIP contains a large number of files. The files produced for some AIPs are sufficiently large that further processing on the data is extremely slow and memory intensive. We are working with Artefactual to optimise the data model for AIP metadata, removing duplication and significantly reducing the size of the files produced.

## Objective

Better preservation of our digitised and born-digital collections

## Measures

- Does Archivematica produce smaller metadata files?

- Do these smaller files still contain the same scope of data?

- Has the new format been reviewed by the PSP?

## Initiatives

- Define a new data model for AIP metadata

- Produce both old and new formats in Archivematica

- Create report identifying known issues and next steps

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/5027157

**Comment by alexwlchan** [comment]
Closing as stale; we're now processing the METS in iiif-builder and it doesn't seem excessively large.
