### ISSUE TITLE
Storage replication to a second provider

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4640]
## Description

To further secure the long term preservation of our digitised and born-digital collections, we want to keep a full replica of all data in a second cloud provider. Whilst we already store two replicas in AWS, adding a second provider insulates us from any potential issues with AWS and gives us a copy of the data with a completely different disaster threat. This is intended as a disaster recovery copy of last resort, so will be in cold storage only.

## Objective

Better preservation of our digitised and born-digital collections

## Measures

- Has all existing content been replicated to a second provider?

- Is new content replicated to a second provider during ingest?

## Initiatives

- Replicate new content on ingest

- Replicate all existing content

- Verify replication of existing content

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4912368

**Comment by alexwlchan** [comment]
🎉 🎉 🎉
