### ISSUE TITLE
Users are kept informed of website changes

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4653]
# Objective

Build trust and reduce barriers for online and in-venue audiences

# Initiatives

- Investigate options for 'release notes' for regular updates on new functionality, improvements, fixes

- Investigate options for public roadmap

- One Website comms (as led by Marketing & Audiences)

# Measures

- Comms plan put into motion

- Monthly updates from product teams

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4959719

**Comment by jennpb** [comment]
Last thing to do is to update the Release Notes page with links to Roadmap, Stacks and User Panel page.
