### ISSUE TITLE
Decide a long-term plan for dealing with Azure auth

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4658]
Following https://github.com/wellcomecollection/platform/issues/4582

We can create SAS URIs that let a service in AWS write to Azure. We need to think about things like:

* How often should we refresh those credentials?
* Restrict the generated URIs to the Elastic IPs for our NAT Gateways

**Comment by alexwlchan** [comment]
What it we just mint perpetual credentials, but restricted to the Elastic IP for the storage VPC? Nobody can use them unless they're running inside our infra, and if they're inside our infra we've already lost.

**Comment by kenoir** [comment]
I think the IP restrictions are the quickest easiest thing to do and are sufficiently secure. I'm happy to go with that.

**Comment by alicefuzier** [comment]
Sounds good to me. Quick and simple
