### ISSUE TITLE
Decide how we store and display Azure locations

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4664]
Within S3, bucket names are globally unique. This means a (bucket, key) pair uniquely identifies an object.

The same is not true for containers (“buckets”) in Azure. Within the root Wellcome account, we have storage accounts. Those storage accounts in turn have containers. Those container names are unique *within a storage account*, but there's no guarantee that a given container name is unique:

* Within Azure as a whole
* Within the Wellcome Azure account

So given a (container, blob) pair, you can't uniquely identify a container. Given (root Azure account ID, storage account, container, blob) you can.

We can probably assume the root Azure account is unlikely to change soon. Do we need the storage account?

Pros:

* More explicit
* Less ambiguity for future users

Cons:

* Requires a change to the DisplayLocation model
* If we choose bucket names carefully, a collision is very unlikely

On the other hand, although the S3 bucket names are unambiguously unique, you need the implicit knowledge "which of our AWS accounts is the bucket in" to go retrieve content from it. So it's not like our S3 locations are completely usable as-is either.

So we're probably fine with the existing display Location model (albeit with the internal S3/Azure disambiguation in https://github.com/wellcomecollection/platform/issues/4596).

![azure_containers](https://user-images.githubusercontent.com/301220/87522009-04163f80-c67d-11ea-90f9-252cf82754f8.png)

**Comment by kenoir** [comment]
> you need the implicit knowledge "which of our AWS accounts is the bucket in" to go retrieve content from it. 

This isn't really true - you need permission, but you do not need the account id to access them.

**Comment by kenoir** [comment]
I think as nothing is intended to read from the Azure locations right now we can push this problem down the road.

**Comment by alexwlchan** [comment]
Just throwing in another data point from my own experiments: it seems like storage account names might be globally unique? I've just tried to create several that, AFAIK don't exist elsewhere in Wellcome's estate, but are taken _somewhere_.

**Comment by alexwlchan** [comment]
We have something, good enough for now.
