### ISSUE TITLE
Investigate alternatives to managed NAT Gateway

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4666]
Currently our Azure replicator and verifier are both in private subnets, which means all their traffic to/from the public Internet is going to go via Amazon's [managed NAT Gateway](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html).

In Ireland, that's an eye-wateringly expensive $0.048/GB processed in either direction. If we want to replicate 60TB to Azure, that's nearly **$2900** in NAT Gateway charges alone – not accounting for AWS egress costs. If we want to replicate it back, it costs the same again. ($6k if we verify from AWS.)

Looking ahead to the 100GB of data we'll be ingesting for the A/V digitisation, that's another **$4800**. ($10k if we verify from AWS.)

I can think of two options that might be worth exploring:

* Slightly break networking best practices, and run the Azure replicator/verifier in a public subnet (easy). We can't associate Fargate tasks with an Elastic IP without a load balancer (boo), so it's harder to tie our SAS URIs to a fixed IP address.
* Run our own NAT instances. It's a bit more work to set up initially (although Amazon have tutorials), and I think we'd have to get a second Elastic IP address to associate.

Given the potential savings are between $8k and $16k, depending on how we run the verifier, it seems worth spending at least a day or two to investigate. (Put another way: 4–8 months of the storage service’s current running costs.)

Part of https://github.com/wellcomecollection/platform/issues/4598

**Comment by kenoir** [comment]
Running our own NAT instances sounds like the best of those two options.
