### ISSUE TITLE
Restart services when Sentinel file updated

### ISSUE THREAD

**Issue by donaldgray** [wellcomecollection/platform#4670]
The background dlcs-job processor runs in a continuous loop, with a slight delay between runs. At the start of each iteration it checks to see if the sentinel file exists, if not it will stop processing and exit the loop.

We need a 'nice' way to restart the service when things are good to go again. This could be a separate service (lambda?) that monitors for that S3 key being created and restarting the task. Or it could be part of the dlcsjobProcessor project.

For now we would need to go in and restart the service via AWS Console or CLI.

**Comment by alexwlchan** [comment]
When the sentinel file is updated, the processor stops. It sounds like another sentinel file change is used to tell the process to restart. Is it something to do with the contents of the sentinel file?

**Comment by donaldgray** [comment]
No - I'll tidy the wording as what I have put is confusing. It's the existence of a file that signifies go/not go, rather than the contents.

**Comment by donaldgray** [comment]
Plan is to rewrite this to use postgres to store go/no-go flag. 

The usage of file based sentinel doesn't make sense in the cloud like it did when the services were server based.

**Comment by donaldgray** [comment]
PR with changes - https://github.com/wellcomecollection/iiif-builder/pull/142
