### ISSUE TITLE
Investigate use of Wellcome deploy tool

### ISSUE THREAD

**Issue by donaldgray** [wellcomecollection/platform#4685]
Look to see whether the wellcome deploy tool is suitable to use for iiif-builder.

See: https://github.com/wellcomecollection/weco-deploy
Example: https://github.com/wellcomecollection/catalogue/blob/master/.wellcome_project

**Comment by tomcrane** [comment]
Going to move this to milestone 4 if that's OK

**Comment by tomcrane** [comment]
Taking this off Critical path, we can move to buildkite later. We have a Jenkins-based build (alongside DLCS). We can adapt this later.

**Comment by kenoir** [comment]
Closing as outdated (deploy tool no longer exists).
