### ISSUE TITLE
Refactor DDS dashboard to live entirely under /dash

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4687]
To comply with #4603, requests for iiif.wellcomecollection.org/dash are routed to dashboard.
Which means it can't have any content that isn't under this path.

**Comment by tomcrane** [comment]
This is working but it has resulted in some ugly /dash/dash/ URLs which we can fix over time.

**Comment by donaldgray** [comment]
Deployed to staging environment. E.g. the following are the same paths (`.test.` has yet to be updated).

 * https://iiif-stage.wellcomecollection.org/dash/Queue
 * https://iiif-test.wellcomecollection.org/dash/dash/Queue
