### ISSUE TITLE
Stop using uk.ac.wellcome as the namespace for our Scala apps

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4690]
Wellcome is moving away from the ac.uk-branding, so we should follow suit.

This is an opportunity to rationalise some of our namespaces – maybe:

```
org.wellcome.sierra_transformer.transformers
wellcome.sierra_transformer.transformers
weco.sierra_transformer.transformers
```

**Comment by warrd** [comment]
I like these 2 best:

```
weco.sierra_transformer.transformers
wellcomecollection.sierra_transformer.transformers
```

**Comment by kenoir** [comment]
https://search.maven.org/search?q=weco

Looks ok.

**Comment by tomcrane** [comment]
We can do this in the iiif-builder too - but I'd hold off refactoring namespaces there until we have finished the migration, so we can compare like for like as we migrate.

**Comment by alexwlchan** [comment]
Done!
