### ISSUE TITLE
Path Alias feature for DLCS Orchestrator + Thumbs

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4694]
Creating this issue as a successor to #4603, but it's really an issue for DLCS so I'll make a fuller one in there and link to it.

https://github.com/dlcs/protagonist/issues/19

**Comment by tomcrane** [comment]
This might be quite a chunky piece of work - we want to update the DLCS Orchestrator for .NET Core and rewrite some of it - see https://raw.githubusercontent.com/dlcs/protagonist/master/docs/c4-container-diagrams/DLCS-2020-l2.png - but that's a big piece.

Can we get away with doing this entirely in NGINX for _old_ orchestrator, for now? Purely rewrite rules.

**Comment by donaldgray** [comment]
Updated title as logic will need applied to thumbs handler to correctly render `@id` element of iiif

**Comment by donaldgray** [comment]
Updated both thumbs-service and wider DLCS to handle `X-Forwarded-Host` header. This will be set in CloudFront (as part of #4997).

Thumbs has already been updated - when requesting via dlcs.io or iiif.wc.org (or environment specific variation of) it sets the `"@id"` property of info.json accordingly.

Updated DLCS Orchestrator to return `"@id"` in info.json for audio, video and image dependant on incoming host. Id for auth services also updated in info.json to reflect iiif.wc.org version.

**Comment by donaldgray** [comment]
Update handling of auth requests that can use different redirects based on incoming `X-Forwarded-Host` header. Default will be current behaviour (redirect to wl.org).

* `iiif.wellcomecollection.org` -> `https://iiif.wellcomecollection.org/roleprovider/dlcslogin`
* `iiif-test.wellcomecollection.org` -> `https://iiif-test.wellcomecollection.org/roleprovider/dlcslogin`
* `iiif-stage.wellcomecollection.org` -> `https://iiif-stage.wellcomecollection.org/roleprovider/dlcslogin`
* _default_ -> `https://wellcomelibrary.org/iiif/dlcslogin`
