### ISSUE TITLE
Use PostgreSQL to back IDistributedCache on iiif-builder

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4701]
The only place the DDS needs this kind of persistence is when it acts a roleprovider for the DLCS.
Here, and only here, it needs to maintain sessions for users, and release the roles of a user with an active session to the DLCS.

https://github.com/wellcomecollection/iiif-builder/pull/34 currently uses the default IMemoryCache impl of IDistributedCache, which is not actually distributed; this should be replaced with a pgsql impl.

We could use Redis or NCache but we aren't using them anywhere else in IIIF-Builder, and we already have PostgreSQL, so keep things simple and use that.

 - TODO - process for clearing out stale cache entries from the pgsql db - how does that happen?

**Comment by tomcrane** [comment]
https://www.nuget.org/packages/Extensions.Caching.PostgreSql/

**Comment by donaldgray** [comment]
Used https://github.com/leonibr/community-extensions-cache-postgres nuget package to iif-builder. This is a slightly more up to date fork of the above lib.

Setup to create table `__dist_cache` table in dds database, used double underscore prefix to align with EF migration table to signify it's system managed.

Configured to create required routines and tables automatically for non production environments - Production environments will need to be manually updates with tables.
