### ISSUE TITLE
Narrow search by filtering and sorting results

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4724]
## Catalogue search

- "More filters" modal
- Filter by format, date, location, contributor, subject, genre, language

## Image search

- Filter by contributor, genre, colour, license

**Comment by jtweed** [comment]
Link to subfeature: https://wellcomecollection.productboard.com/feature-board/planning/features/5161323

**Comment by ishouty** [comment]
@jtweed Speaking to @jamieparkinson , the contributor aggregation is not available but I should be able to work with the rest such as     
*  genres
*  languages
*  subjects

**Comment by jamesgorrie** [comment]
We have two types of label data at the moment, exhaustive (enumerated) and non-exhaustive.

The interface we have only caters for the former, which include `workType`, `languages` etc. `subjects` and genres are more complicated as the lists are incredibly long, and can become infinitely longer.

We wouldn't only want to show the top 10, which is what the API returns now, as that obscures what's else is in the API and it would make it seem as though that is all we have.

We'd probably want some sort of sub-search/autocomplete for that.

**Comment by jtweed** [comment]
Right now we do want to show the top X, even though it is non-exhaustive. It's still useful for someone who searches for a specific term and wants to make sure that they are then filtering for it correctly. Ie, it's not perfect, but it is still a requested feature and better than not having it, whilst we work on a longer term approach to taxonomy based discovery.

**Comment by jtweed** [comment]
> @jtweed Speaking to @jamieparkinson , the contributor aggregation is not available but I should be able to work with the rest such as
> 
> * genres
> * languages
> * subjects

Let's start with those - we'll want to add contributors as part of this wider piece of work.

**Comment by jamesgorrie** [comment]
@jtweed Apologies, I didn't realise that - assuming then we might want to label it as "Top 10" or whatever?

**Comment by jtweed** [comment]
Yeah we do need to work through that aspect of things. I want to get something starting to take shape to help inform that.

**Comment by ishouty** [comment]
FYI and a chat with @jamieparkinson 

* Looking at current subject and genres labels api, we can only request singular at this moment in time.
- from a ui perspective if we did this then we would be only allowed to select one per filter.
 
* Languages is possible to deal with multiple. e.g filter by english and french

**Comment by jamesgorrie** [comment]
An example of what the single genre/subject search can do:
https://weco.works/search

This is something to bare in mind with the details page too as currently we just do a `query` search on the subject/genre, where recall is larger than using the `subjects|genres.label` filter.

**Comment by jtweed** [comment]
Reopening as this isn't fully complete - it also covers additions to image search that haven't been looked at yet.

**Comment by pollecuttn** [comment]
Waiting for user testing results before closing.
