### ISSUE TITLE
Dump full text and annotations to S3?

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4742]
In the current DDS impl, the Search Within is backed by serialised Text Maps. We're porting this functionality to iiif-builder; these text maps will now live in S3 rather than network fileshares.

The are _currently_ serialised binary .NET objects, so they are only readable by the DDS.

These text maps also yield the full text, like this:
https://wellcomelibrary.org/service/fulltext/b2931625x/0?raw=true

You can grab the full text per-manifest from a URL (with some light computational overhead to transform it), but you couldn't walk straight up to the S3 bucket and get the full text. For example, if you were a Wellcome dev writing a Python script to feed text to a machine learning project and wanted to hoover up the text directly.

It's a few extra lines of code to dump the raw text to S3 while the text map is being made.
is it worth doing this?

Balance extra storage costs in S3 vs having the raw text as plain .txt files in S3 for everything

**Comment by tomcrane** [comment]
Similar question for these two:

https://wellcomelibrary.org/iiif/b2931625x/images
(all the OCR-identified images/figures)

https://wellcomelibrary.org/iiif/b2931625x/allcontent
(line-by-line anno for whole work)

**Comment by tomcrane** [comment]
Decision - save them - and if they look too huge and incurring too much S3 storage, get rid of them.

**Comment by tomcrane** [comment]
Decision - which can be revisited later if it proves to be the wrong decision.

IIIF 3 (W3C Annos)
 - Per-manifest all annotations: save to dds S3 and proxy from there
 - Per-manifest images only: save to dds S3 and proxy from there
 - Per-canvas all annotations: save to dds S3 and proxy from there

METS-ALTO
 - Proxy from storage service
Raw text
 - per manifest: save to dds S3 and proxy from there

IIIF 2 (Open Annotation)
 - Per-manifest all annotations: save to dds S3 and proxy from there
 - Per-manifest images only: save to dds S3 and proxy from there
 - Per-canvas all annotations: **load P3 (W3C) version and dynamically convert** (on the fly)

The trade-off is between keeping millions of files in S3 vs in some other form (e.g., Dynamo blobs).
These anno blobs might not be used at all from week to week. Then someone does some text-harvesting and requests millions of unique ones. S3 + light proxy is essentially a static content approach. 
Also allows for other use cases by Wellcome directly against S3 text.
It is expensive to dynamically produce a per-manifest annotation list.
But it is not expensive to dynamically transform a page of W3C JSON to OA JSON. This is a mere blip of CPU and RAM. So, only keep _one_ of the per-page anno forms; and that one should be the newer W3C version.

**Comment by tomcrane** [comment]
@jtweed the above feels the right way to go to me.

**Comment by jtweed** [comment]
Agreed

**Comment by tomcrane** [comment]
IIIF 3 (W3C Annos)

- [x] Per-manifest all annotations: save to dds S3 and proxy from there
- [x] Per-manifest images only: save to dds S3 and proxy from there
- [x] Per-canvas all annotations: save to dds S3 and proxy from there

METS-ALTO

- [x] Proxy directly from storage service

Raw text

- [x] Per manifest: save to dds S3 and proxy from there

IIIF 2 (Open Annotation)

- [ ] Per-manifest all annotations: save to dds S3 and proxy from there
- [ ] Per-manifest images only: save to dds S3 and proxy from there
- [ ] Per-canvas all annotations: load P3 (W3C) version and dynamically convert (on the fly)

**Comment by tomcrane** [comment]
Here's the an original, Open Annotation page on wl.org:

![image](https://user-images.githubusercontent.com/1443575/107353176-a76ced00-6ac4-11eb-98fc-89465a06a52a.png)

And here's the new W3C annotation version:

![image](https://user-images.githubusercontent.com/1443575/107353270-c66b7f00-6ac4-11eb-876f-991513534f9f.png)

This is simply proxied from S3

And here's the new open annotation version, which apart from `id` differences, is identical to the first picture:

![image](https://user-images.githubusercontent.com/1443575/107353456-f7e44a80-6ac4-11eb-962a-a9083a50ac44.png)

This page is created on the fly, by loading the same S3 key as the W3C version, then parsing the JSON and writing out an Open Annotation version.

This additional parsing and reserialising adds ~500 microseconds (**micro** not milli).

So. It's OK!

**Comment by tomcrane** [comment]
@jtweed all of the checkboxes in https://github.com/wellcomecollection/platform/issues/4742#issuecomment-775250688 are done!

Will get this deployed today or tomorrow.
