### ISSUE TITLE
Transform IIIF3 to IIIF2 for existing consumers

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4749]
We're replacing the package model with IIIF3 directly. IIIF3 is the internal model.

We have a IIIF Library to build the Presentation 3 (https://github.com/wellcomecollection/iiif-builder/tree/master/src/Wellcome.Dds/IIIF).

We also have a Presentation 2 library that current DDS uses (https://github.com/digirati-co-uk/iiif-model)

We'll need to transform P3 to P2, but do we use this library to do it?

Or make new P2 model classes in the new .NET Core library? In a different namespace?
Or have a fluent interface that you pass a version to, so that something like .AddLabel(..) produces different internal models
Or emit P2 JSON directly as you traverse the strongly-typed P3?

Or, quickest (probably), adapt existing DDS IIIFConverter and related code to convert from IIIF3, rather than from Package.

(note - no AV "IxIF" pseudo-IIIF placeholders will be available from the new DDS - time-based resources will only have v3 representations.)

**Comment by tomcrane** [comment]
> Or emit P2 JSON directly as you traverse the strongly-typed P3?

One argument, possibly, in favour of this is that there are a few bits of the P3 Manifests that can be directly lifted as JSON.
Image Services and Auth Services are not Presentation3, so they are the same in the new Manifests as they were in the old.

This is why the "pure" Presentation 3 IIIF library has these extras:
https://github.com/wellcomecollection/iiif-builder/tree/master/src/Wellcome.Dds/IIIF/LegacyInclusions

**Comment by donaldgray** [comment]
As mentioned in yesterday's meeting we need to handle converting AV to pseudo-2.1 format

**Comment by donaldgray** [comment]
Will need thorough testing as part of #4751 but basic implementation is in https://github.com/wellcomecollection/iiif-builder/pull/86
