### ISSUE TITLE
Write a IIIF2 comparison tool

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4751]
This is the ultimate test of the migration from old DDS to new iiif-builder.

Take the IIIF2 manifest that iiif-builder has converted from IIIF3, which in turn was built from catalogue API and METS.
Compare it to the old DDS manifest for the equivalent manifestation.

They should be structurally identical.

Some things will differ - URL patterns for linked resources will have different forms, but they are checkable because they are deterministic.

Also, some catalogue data transformed to metadata might be different, if we decide to map Catalogue API descriptive metadata differently.

But we can still have a verifier that can tell us that all b numbers are working.

**Comment by donaldgray** [comment]
PR: https://github.com/wellcomecollection/iiif-builder/pull/91

The output P2 version manifests are not identical between new and old systems. The comparer tool has a set of rules to ensure that there are no breaking changes. We may need to revisit as we add Born Digital and AV but closing for now.
