### ISSUE TITLE
IIIF Search Infrastructure

### ISSUE THREAD

**Issue by donaldgray** [wellcomecollection/platform#4754]
Infrastructure for implementing IIIF search. 

Consider having as separate service rather than embedded into the current application (this is how DDS-current works). Having a separate service would enable us to scale independently of current app.

Related to #4741 and #4740

**Comment by tomcrane** [comment]
Feeling more strongly now that text services should be a distinct application/service.
IIIF Presentation resource serving is then extremely simple, robust, and unaffected by load variations from text harvesting/search ops.
This makes little difference to development, just needs more terraform to spin them up.

**Comment by tomcrane** [comment]
A refinement of this.

Split the controllers into two (or more) camps:
https://github.com/wellcomecollection/iiif-builder/tree/master/src/Wellcome.Dds/Wellcome.Dds.Server/Controllers

Operations that are mostly proxying prepared JSON from S3 are not sent to the same running service as dynamic operations that are spikily memory- or compute-intensive, like search.

Can we split at the controller level or do we need to be more granular within controllers?

**Comment by donaldgray** [comment]
Deployed and tested - `/search*` and `/text*` paths are handled by a separate instance that can be scaled independently. I've not added any autoscaling etc for now but assigned more memory to new text-services instance.

PRs:
https://github.com/wellcomecollection/iiif-builder-infrastructure/pull/36
https://github.com/wellcomecollection/iiif-builder/pull/122
