### ISSUE TITLE
Invalidate Cloudfront cache based on b number

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4759]
Cachebusting - the internal-to-DDS aspect of that is replaced by the simpler straight-to-IIIF model - just remake the b number from the dashboard. No need to remove package files.

For the web caches (reverse proxy), atm if you trigger a cachebust the DDS puts a notification on SNS.
A small utility runs on the DMZ reverse proxy boxes, that picks up these messages (the body is just the b number I think).
It uses the IIS API (ARR extensions) to invalidate path patterns that match the b number.

That is directly equivalent to this:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html

If we're going to be running behind Cloudfront, we can do that.

.NET SDK:
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=CloudFront/MCloudFrontCreateInvalidationCreateInvalidationRequest.html

**Comment by tomcrane** [comment]
![image](https://user-images.githubusercontent.com/1443575/112959986-e0782400-913b-11eb-8224-d2829d073d17.png)

These aren't wired up at all yet.

* The first option needs to queue a workflow job with options `RefreshFlatManifestations`, `RebuildIIIF`
* The second needs to queue a workflowJob with `RebuildTextCaches`, `RebuildAllAnnoPageCaches` (although it might as well do a null options and do everything).

We could be selective about cache invalidation, but an acceptable first iteration would be that for both of these, we clear Cloudfront of _anything_ matching the manifestation identifier - (e.g., b12312312 or b12312312_0003).

We need to work out how to do that.

The dashboard can't make a direct call as it's running in a different account.

It could call a service in that account (a lambda?) that does the cache invalidation.

**Comment by tomcrane** [comment]
The messages "No cached package on disk yet" etc need to be updated.

This instead checks the artefacts in S3 - the collection/manifestation JSON blobs, and the Text object, for this manifestation.

**Comment by tomcrane** [comment]
@kenoir @aray-wellcome 

How do you want to handle this? An action performed in the dashboard results in _something_ using the Cloudfront API to invalidate all entries that match a pattern.

The dash can't do this directly, it's in a different account.
And there is a cost involved in these invalidations. Although, it's a human action, so there won't be millions of them.

Worst case scenario is *b19974760* which would invalidate millions of entries (literally millions if not 10s of millions).

**Comment by aray-wellcome** [comment]
I'm not sure I can speak to the how we should handle this but I know we need the option to clear cache and rebuild a bnumber. In the old DDS I'd do this when changes were made to an item's METS and it was still showing old info, I had to delete something for a take down request and it was still showing, if I needed to update the images and they were still showing old ones, or if there was an error on the UV that had no obvious cause. I imagine that in new DDS I will probably need it for the same things.

I'm not sure how much it will cost but you're right, the invalidation would be done manually and probably on the magnitude of ones a month normally. It'd be more more if I am doing a big error clean up project.

**Comment by kenoir** [comment]
> How do you want to handle this? An action performed in the dashboard results in something using the Cloudfront API to invalidate all entries that match a pattern.

I think a lambda would be pretty straightforward, but called from SNS rather than directly (and share the topic cross account). We'd write that code/infra in the `platform` account, an put it in https://github.com/wellcomecollection/platform-infrastructure. So someone needs to write that PR. I'm not sure how to prioritise/assign that work though Paging @aray-wellcome.

**Comment by tomcrane** [comment]
> someone 

Wellcome or Digirati?

**Comment by aray-wellcome** [comment]
@tomcrane Is that something Digirati could do?

**Comment by tomcrane** [comment]
Yes, we'll write it up.

**Comment by tomcrane** [comment]
Implementation idea:

On UriPatterns class:

`string[] GetCacheInvalidationPaths(string identifier)...`

broadcast that list to SNS, rather than just the b number
lambda that picks up the message invalidates the provided list
Gives more flexibility and control for later changes
If we need to tweak it's a DDS deploy only

**Comment by tomcrane** [comment]
^ allows for finer grained ops if required... just the images, just the text, whatever... even if initially for MVP, everything that matches a b number is zapped.

**Comment by donaldgray** [comment]
PR for adding invalidation lambda + SNS topic: https://github.com/wellcomecollection/platform-infrastructure/pull/153

**Comment by donaldgray** [comment]
Previously triggering a cache-invalidation immediately removed data which was rebuilt on next request.

However, we don't build on demand anymore - everything is pre-built and served from S3. Due to this the cache invalidation process will:

* Queue the job for reprocessing, with a 'clear-cache' flag.
* This job will be marked as priority so that it doesn't need to wait on any existing items being processed.
* Once the job has been completed, the workflow-processor will detect the 'clear-cache' flag and trigger a CloudFront invalidation.

**Comment by donaldgray** [comment]
Pull requests for this:

https://github.com/wellcomecollection/iiif-builder-infrastructure/pull/37
https://github.com/wellcomecollection/iiif-builder/pull/141

> Reminder: This contains a DB migration which will need to be run for instrumentation db
