### ISSUE TITLE
Sequential ordering in archives

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/platform#4762]
One more for @warrd 

Here's an instance where the numbering is preceded by a letter, and the sequence is non-numerical 
https://wellcomecollection.org/works/xvgk6ws8
Order goes:
/A1
/A11
/A12
/....

**Comment by pollecuttn** [comment]
@warrd This issue is closed but the sequence is still:
/A1
/A11
/A12

Am I missing something?

**Comment by warrd** [comment]
@pollecuttn it's not deployed yet but the PR is merged, I can deploy it today
