### ISSUE TITLE
Improve the reliability of Snapshot Generator for Catalogue.

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4778]
The snapshot generator is required for large scale analysis of catalogue API data - it does not work at present and impedes the build of other projects.

**Comment by alexwlchan** [comment]
Link to discussion in Slack: https://wellcome.slack.com/archives/C3TQSF63C/p1600249814037600

**Comment by kenoir** [comment]
The snapshot generator looks to have been working up until September 10th - the lambda / service have been triggering and working since then without issue.

The infrastructure is outdated (still uses old style single_container task defs) so logs are not visible.

Queue metrics look like it is failing to process the message when it is received and then is returned to the queue after the visibility timeout (30 minutes)  is exceeded.

**Comment by kenoir** [comment]
Deployment of catalogue API must be linked to deployment of snapshot generator. This coupling can be acheived by updating the `.wellcome_project` file to make the snapshot generator a part of the catalogue api deployment group.

**Comment by kenoir** [comment]
Closing as dupe of https://github.com/wellcomecollection/platform/issues/4813
