### ISSUE TITLE
Add workType to nested works included in `parts`

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4782]
Problem:

Given https://api.wellcomecollection.org/catalogue/v2/works/vaj43uvm?include=identifiers,items,subjects,genres,contributors,production,notes,parts,partOf,precededBy,succeededBy

vaj43uvm clearly maps to a IIIF Collection.
In converting it, I can see that this has `parts`, but I don't know what kind of things those parts are.

In projecting this into IIIF, I want to know whether those children:

1. have a digital location and are archive-item, in which case they are Manifests in my Collection.items
2. are further container levels, and hence are Collections in my Collection.items

**Comment by tomcrane** [comment]
Another way of looking at it - if rendering as a tree in a Finder/Explorer -style UI, are these `parts` folders or are they files?

**Comment by tomcrane** [comment]
The work page knows this though (with the tree toggled on). How does it know...?

**Comment by tomcrane** [comment]
To clarify then, I'm asking for _two_ extra pieces of info.

 - the workType - which is fairly small and won't make it look too horrible
 - location information - which is not small and might make it look very horrible

The latter would allow you to "list the contents of a folder" and mark the handful of items within that are digitised.
If it were a query (like https://github.com/wellcomecollection/platform/issues/4752#issuecomment-692929100) then you could filter results.
But it's not a query, it's a single work - that has nested works returned in its representation.
If you could apply a filter on the single work, that applies to the items returned in `parts` and friends, you could ask for all items and then ask again for only items with digital locations. This gets a bit weird though, don't want to mess up your API design.

**Comment by gestchild** [comment]
> The work page knows this though (with the tree toggled on). How does it know...?

For the tree prototype, we're actually having to go and get each of the nested works to determine whether they each have parts and thus display the appropriate controls.

But @warrd is in the process of adding `totalParts` and `totalDescendantParts` to the works so that this won't be necessary.

**Comment by tomcrane** [comment]
Thanks @gestchild, that's also our temporary solution for generating the IIIF representation - not surprising really has they have similar ends.

The ideal (for me) would be to also combine with the location filter and workType, so that you know:

* This node has 1473 descendants (but might include intermediate archive levels)
* This node has 1450 archive-item descendants (i.e., leaves only, things that could be held and looked at rather than descriptive abstractions)
* This node has 921 archive-item descendants that have a digital location (i.e., 64% of the archive below this point in the tree has been digitised - by item count at least, not by physical scale)

**Comment by tomcrane** [comment]
For the IIIF representation, the last bit would allow us to hide paths that cannot lead to any digitised leaves.

**Comment by tomcrane** [comment]
The context here is someone loading the root collection into a IIIF compatible browse tool.

**Comment by tomcrane** [comment]
In the old DDS, we can compute the latter (number of digitised items below a path), and could still do so, but I'd rather not, because:

1. It would be slow at runtime; for every visible node (e.g., 50 children) you'd have to count each of its descendants
2. We want to store as little as possible, the DDS shouldn't store anything that the Catalogue API might know about too, it should lean on the Catalogue API wherever it can.

**Comment by tomcrane** [comment]
There is much more that could be added to IIIF collections and manifests to improve hierarchical navigation in third party tools, but I think that https://github.com/wellcomecollection/iiif-builder/pull/89 gives us enough for launch.
