### ISSUE TITLE
Legacy Travis repositories

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4795]
The following repositories still build in Travis and should be moved to Buildkite ad-hoc as any work is done in those projects.

- [x] https://github.com/wellcomecollection/stacks-service (https://github.com/wellcomecollection/stacks-service/pull/87)
- [x] https://github.com/wellcomecollection/archivematica-storage-service (https://github.com/wellcomecollection/archivematica-storage-service/pull/20)
- [ ] https://github.com/wellcomecollection/aws_utils
- ~https://github.com/wellcomecollection/loris-infrastructure~
- ~https://github.com/wellcomecollection/sierra-streams-source~
- [ ] https://github.com/wellcomecollection/archivematica
- ~https://github.com/wellcomecollection/loris~

**Comment by harrisonpim** [comment]
is it worth adding [data-science](https://github.com/wellcomecollection/data-science) to this list? the weco-datascience package is currently built by a github action (not travis so less of a rush), but moving that over to buildkite is on my personal todo list.

**Comment by alexwlchan** [comment]
We don’t actually run Travis in https://github.com/wellcomecollection/loris – it’s inherited from the upstream repo that we forked from.

We also don’t have any interesting code in the fork, so I’ve deleted it.

**Comment by alexwlchan** [comment]
aws_utils has been archived; Archivematica is now done in Buildkite per https://github.com/wellcomecollection/archivematica-infrastructure/pull/98; data_science is migrated to GitHub Actions.
