### ISSUE TITLE
Use Internal-Sender-Identifier for the Archivematica UUID

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4799]
Part of https://github.com/wellcomecollection/platform/issues/4794

Currently Archivematica only exposes the RefNo/AltRefNo in the External-Identifier. We should add the AIP UUID to the Internal-Sender-Identifier field, so it can be exposed in the reporting cluster.

Backfilling it to existing bags would be pretty easy – we ingest a bunch of shallow bags with an updated `bag-info.txt` and `fetch.txt` pointing to everything in the previous version. We don't need to resend them through Archivematica.

- [x] Update the Archivematica code to write the Internal-Sender-Identifier for new bags
- [x] Update Archivematica infrastructure to allow weco-deploy deployment (https://github.com/wellcomecollection/archivematica-infrastructure/pull/64)
- [x] Deploy your new Archivematica code to staging, then prod
- [x] Send a test bag to verify your change
- [x] Add the Internal-Sender-Identifier to all the existing bags

**Comment by alexwlchan** [comment]
Notes for somebody who picks this up:

### How to write the Internal-Sender-Identifier for new bags

Archivematica talks to the Wellcome storage service through an application called the Archivematica Storage Service (AM-SS https://github.com/wellcomecollection/archivematica-storage-service).

The AM-SS acts a bit like the adapters in the catalogue pipeline: it presents a common interface to a variety of storage backends. The rest of Archivematica can make requests like _“Please write package X to location Y”_ or “Please retrieve package A from location B”_, and the AM-SS does the work of talking to those backends.

![Screenshot 2020-10-01 at 10 14 36](https://user-images.githubusercontent.com/301220/94790966-eed4c580-03ce-11eb-9418-4aeef74c0ea6.png)

You can see all the backends that the AM-SS supports here: https://github.com/wellcomecollection/archivematica-storage-service/tree/wellcome-storage-service/storage_service/locations/models

And here's the code for talking to the Wellcome Storage Service: https://github.com/wellcomecollection/archivematica-storage-service/blob/wellcome-storage-service/storage_service/locations/models/wellcome.py

By default, Archivematica writes a UUID as the External-Identifier for a bag. Yuck! We use the RefNo (e.g. `PP/CRI/1`) as the External-Identifier for the storage service, so bags aren't so strongly tied to Archivematica.

How we do that:

* Archivematica creates a bag, and compresses it as a `tar.gz` archive.
* It passes it to the code in `wellcome.py` to put it in the storage service: https://github.com/wellcomecollection/archivematica-storage-service/blob/83061311e30ae861172e96bbdef149b3d64af163/storage_service/locations/models/wellcome.py#L356-L487 (the method names are a bit confusing, granted)
* We call out to a second function, which uncompresses the archive, reads the METS file to work out what the new identifier should be (and which space to store it in), updates the `bag-info.txt` and repacks the bag. https://github.com/wellcomecollection/archivematica-storage-service/blob/83061311e30ae861172e96bbdef149b3d64af163/storage_service/locations/models/wellcome.py#L130-L263

You'll need to modify this second function to store the original AIP UUID alongside the External-Identifier.

**Comment by alexwlchan** [comment]
### How to deploy your new Archivematica code

Our fork of the AM-SS repo is set up to automatically build new Docker images and push them to ECR. This is happening through Travis CI.

(You may want to update this repo to use BuildKite while you’re here, per https://github.com/wellcomecollection/platform/issues/4795)

Archivematica runs in the workflow account, and is defined in Terraform in the repo [weco/archivematica-infrastructure](https://github.com/wellcomecollection/archivematica-infrastructure).


There are seven directories in the [`terraform` directory](https://github.com/wellcomecollection/archivematica-infrastructure/tree/development/terraform), following a similar pattern to the storage-service.

* `modules` – reusable Terraform modules
* `users` – some IAM users for the archivists to upload stuff; I may roll this into platform-infrastructure instead
* `infra` – shared infra, ECR repos and ACM certificates
* And the four interesting ones:

     - `critical_{prod, staging}` are persistent databases, S3 buckets, EBS volumes, etc.
     - `stack_{prod, staging}` are the ECS services, load balancer config, etc. All the ephemeral stuff.

Our Archivematica services don't use weco-deploy; they just use whatever the latest image in ECR is. You can deploy the newest images by doing a plan/apply in the appropriate `stack_{prod, staging}` Terraform directory.

**Comment by alexwlchan** [comment]
### How to send a test bag to verify your change

We have a staging and prod version of Archivematica, available at https://archivematica-stage.wellcomecollection.org and https://archivematica.wellcomecollection.org, respectively. They feed the staging and prod storage service.

Archivists send packages to Archivematica by uploading them to "hot folders" in two S3 buckets. The buckets are in the digitisation account. Specifically:

- `s3://wellcomecollection-archivematica-staging-transfer-source/born-digital[-accessions]` (staging)
- `s3://wellcomecollection-archivematica-transfer-source/born-digital[-accessions]` (prod)

The `born-digital`/`born-digital-accessions` folders determine the space used in the Wellcome storage service. The "born digital" packages are ones which have already been catalogued; the "born digital accessions" packages are ones which haven't been catalogued yet. (An [_accession number_](https://en.wikipedia.org/wiki/Accession_number_(library_science)) is the identifier for each new acquisition.)

You can test your change by downloading a transfer package from a hot folder, then reuploading it to that bucket. The bucket is watched by a Lambda, which triggers a "transfer" in Archivematica when it sees new files uploaded. (It's also possible to create your own transfer packages, but that's more work than I want to explain right now.)

You can follow a transfer in the Archivematica dashboard by going to https://am[-stage].wc.org. Once a transfer is completed (i.e. Archivematica has done all its processing, thumbnails, checksums, etc.), it moves to the "Ingest" tab, and on the penultimate step of this tab it gets uploaded to the Wellcome storage service.

You need a user account to log in to Archivematica. Both I and Alexandra Eveleigh in C&R know how to create accounts.

What you need to do:

- [ ] Deploy your new code to staging Archivematica
- [ ] Get a user account for staging + prod Archivematica
- [ ] Upload an Archivematica transfer package to a hot folder in staging
- [ ] Watch the transfer package move through the Archivematica dashboard, until it reaches the "Store AIP" stage
- [ ] Check the package has been stored in the Wellcome storage service
- [ ] Check the correct I-S-I has been written to the metadata in the reporting cluster

**Comment by alexwlchan** [comment]
### How to add the Internal-Sender-Identifier to all the existing bags

This is a one-off migration step that can be done without touching Archivematica. I’ll write up more instructions once you've done the first three steps (or I can do this myself; it's less of a liability).

**Comment by kenoir** [comment]
Closing as done.
