### ISSUE TITLE
Migrate Miro images to storage service

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4809]
## Description

When we completed the initial migration from Wellcome Images to Wellcome Collection, we hadn't settled on a long-term approach to preservation storage or image delivery. As we now have the storage service and have decided to continue to use DLCS, we need to move the images and data from Wellcome Images out of their current, temporary home.

## Objective

Better preservation of our digitised and born digital collections

## Measures

- Are all Miro images in the storage service?

- Are we serving Miro images through DLCS?

- Have we decommissioned Loris?

## Initiatives

- Ingest Miro images into the storage service

- Register Miro images with DLCS

- Update Catalogue API and decommission Loris

## Done

- Ingest Miro data into the storage service

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4912373

**Comment by alexwlchan** [comment]
Here are some initial notes on what we need to think about: https://wellcome.slack.com/files/T0442CG7E/F01B1JTCEKG?origin_team=T0442CG7E

**Comment by alexwlchan** [comment]
Additional notes from a call with @alicefuzier just now:

* The reporting cluster has an index called `miro_inventory` which has a list of where every Miro ID ended up – cold store, Tandem Vault, etc. It also points to a *second* copy of all the images in the `wellcomecollection-images` bucket (some of which are duplicated).

* There's a *third* copy of all the images in `wellcomecollection-miro-images-public`, which will presumably be deleted when we turn off Loris.

* Whoever does this work should coordinate with Holly – she uses the Miro inventory to find images, and she'll need to be able to find them once we've cleared out the S3 buckets.

**Comment by alexwlchan** [comment]
Alice's notes on DDS and the DLCS APIs: https://wellcome.slack.com/archives/C3TQSF63C/p1602493113006800?thread_ts=1602492284.004800&cid=C3TQSF63C

**Comment by alexwlchan** [comment]
Registering a single image with the DLCS CLI on master:

```console
$ python3 dlcs.py ingest image test1 https://alexwlchan.net/images/2020/quick_look_1x.png
{
  "count": 1,
  "completed": 0,
  "id": "https://api.dlcs.io/customers/2/queue/batches/751722",
  "context": "https://api.dlcs.io/contexts/Batch.jsonld",
  "type": "vocab:Batch",
  "error_images": "https://api.dlcs.io/customers/2/queue/batches/751722/errorImages",
  "images": "https://api.dlcs.io/customers/2/queue/batches/751722/images",
  "completed_images": "https://api.dlcs.io/customers/2/queue/batches/751722/completedImages",
  "test": "https://api.dlcs.io/customers/2/queue/batches/751722/test",
  "submitted": "2020-10-12T09:22:43.8069475+00:00",
  "errors": 0,
  "finished": "0001-01-01T00:00:00",
  "superseded": false
}
```

which is available at https://dlcs.io/iiif-img/wellcome/7/test1/full/880%2C/0/default.jpg 🎉

**Comment by alexwlchan** [comment]
It looks like the DLCS CLI doesn't support ingesting images from anything except http URLs – that may be an issue for us.

**Comment by tomcrane** [comment]
> It looks like the DLCS CLI doesn't support ingesting images from anything except http URLs 

@fmcc I assume that's easily fixed?
https://github.com/dlcs/dlcs-cli/tree/feature/dlcs_api_rewrite

The API itself accepts s3 and ftp origins (it's done 80m so far...)

**Comment by alexwlchan** [comment]
It looks like the ingest command isn't wired up in the dlcs_api_rewrite branch, because if it did I'd definitely use it!

**Comment by tomcrane** [comment]
Yeah that cli is a bit of a WIP, to round up various bits of client code for the API.
The fullest client imp is in the DDS / IIIF-Builder, but that's probably not much use to you there.

**Comment by alexwlchan** [comment]
The API docs in https://dlcs-book.readthedocs.io/ have plenty of pieces too, so I'm sure we can cobble something together.

**Comment by tomcrane** [comment]
also for ref...
https://github.com/wellcomecollection/iiif-builder/blob/master/src/Wellcome.Dds/DlcsWebClient/Dlcs/Dlcs.cs

**Comment by alexwlchan** [comment]
Following the example at [the bottom of this page](https://dlcs-book.readthedocs.io/en/latest/walkthroughs/registering_images_via_the_api.html), I got a snippet of code that I think should create a collection, but instead returns a 500 Error:

```python
import httpx

from settings import *

resp = httpx.post(
    f"https://api.dlcs.io/customers/2/queue",
    auth=(DLCS_API_KEY, DLCS_SECRET),
    data={
        "@type": "Collection",
        "member": [
            {
                "space": "7",
                "origin": "s3://wellcomecollection-storage/testing/test_bag/v18/data/boops_boops.png",
                "tags": []
            },
            {
                "space": "7",
                "origin": "s3://wellcomecollection-storage/testing/test_bag/v17/data/boops_boops.png",
                "tags": []
            },
            {
                "space": "7",
                "origin": "s3://wellcomecollection-storage/testing/test_bag/v16/data/boops_boops.png",
                "tags": []
            }            
        ]
    }
)

print(resp)

from pprint import pprint
pprint(resp.json())
```

**Edit:** Ah, so I had to pass `json=` instead of `body=`.

🤔

**Comment by alexwlchan** [comment]
Here's some code which does put some images on the queue:

```python
import httpx

from settings import *

resp = httpx.post(
    f"https://api.dlcs.io/customers/2/queue",
    auth=(DLCS_API_KEY, DLCS_SECRET),
    json={
        "@type": "Collection",
        "member": [
            {
                "space": "7",
                "origin": "s3://wellcomecollection-storage/testing/test_bag/v18/data/boops_boops.png",
                "id": "boops_boops_v18"
            },
            {
                "space": "7",
                "origin": "s3://wellcomecollection-storage/testing/test_bag/v17/data/boops_boops.png",
                "id": "boops_boops_v17"
            },
            {
                "space": "7",
                "origin": "s3://wellcomecollection-storage/testing/test_bag/v16/data/boops_boops.png",
                "id": "boops_boops_v16"
            }            
        ]
    }
)

print(resp)

from pprint import pprint
pprint(resp.json())
```

and I can poll <https://api.dlcs.io/customers/2/queue/batches/751734> to track their progress, apparently.

🎉

**Comment by alexwlchan** [comment]
Notes from a call with @jtweed and @kenoir:

* The point of this work is to ensure **better preservation of these images.** That's the lens through which we should view decision about what we keep, how we store it, where we put it, etc.

    If we've kept something until this point, we should be keeping it now.

    The images might be reingested through Goobi at some point, at which point they'd "replace" these images from the point of view of DLCS/the catalogue API, but that might be years in the future.

* **The structure of our bags should mirror the decisions already made about an image.** Images have been previously copied to three places: cold store, Tandem Vault, the catalogue (some more than one location). We should make it possible to filter by the destination of an image.

   ❓ What if an image went to multiple locations?
   ❓How should the images be organised? 
   ✨ Cycle objects that went to cold store to Glacier

    One suggestion: `miro/<destination>/A images`.

* **The JPEG derivatives are redundant, but we should double-check they're not the only copy of an image.**

* **We should keep the XML metadata.** All the information they contain form part of the collections. We should keep the metadata and images separate.

* **We should consider using Archivematica to ingest the bags.** This would give us the same provenance and bag format as our other born-digital bags, but we'll need to make sure the bags go to a separate space.
