### ISSUE TITLE
Apply for a library membership

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4811]
## Description

Before we can support requesting physical items and access to restricted digitised content, library users need to be able to sign in on wellcomecollection.org. We will support sign in using existing library accounts, as well offer online pre-registration that can be upgraded to a full library account in-person. We will also provide an administration tool for library staff to manage accounts.

## Objective

Researchers engage with a broader range of our collections

## Measures

- Existing library members can sign in to their account

- New library members can register for an account

- Up-to-date information available about membership

## To do

- Sign in to an existing account

- Manage an existing account

- Sign up for a new account

- Account admin tool for staff

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4870169

**Comment by alexwlchan** [comment]
Closing as done – we've implemented sign-in for existing members and sign-up for new members, and administration occurs through Sierra, as per the previous workflows.
