### ISSUE TITLE
Update snapshot_generator infrastructure

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4816]
In order the achieve https://github.com/wellcomecollection/platform/issues/4813 we need to ensure the currently "broken" snapshot_generator uses the latest ECS service modules to provide visibility on metrics & availability of logs.

The snapshot_generator should be deployed alongside the catalogue_api using the weco-deploy tool to ensure that the model used remains in sync.

**Comment by alexwlchan** [comment]
We've said this is done at standup at least twice, and then I did some more work to bring it into line with our current best practices. Pretty sure it's actually done now.
