### ISSUE TITLE
Daily report on snapshot generator in Slack

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4817]
In order to achieve https://github.com/wellcomecollection/platform/issues/4813 we should provide daily reports generated by the snapshot_generator in the style of the Slack Storage Service reporting tools.

These reports should indicate the success of a snapshot (validating the current display models) and provide useful information on the number of works (possibly further breakdown).

- [x] Change the input to the snapshot generator to reflect the "snapshotJob" format below
- [x] Record the S3 ETag, snapshot size, and 
- [x] Change the output of the snapshot generator to reflect the below
- [x] Write a Lambda that records the output from the snapshot generator
- [x] Write a Lambda that posts a message to Slack
- [x] Document the current snapshots architecture

**Comment by alexwlchan** [comment]
I can pair with someone who works on this – I've built a fair number of our Slack reporting tools.

**Comment by kenoir** [comment]
In conversation with @alexwlchan we worked out the following structure that the snapshot_generator should produce to provide data to a reporting tool:

```
{
  "snapshotJob": {
    "s3Location": "S3ObjectLocation",
    "apiVersion": "ApiVersions.Value",
    "requestedAt": "iso_date"
  },
  "snapshotResult": {
    "indexName": "index_name",
    "documentCount": 123,
    "displayModel": "???",
    "startedAt": "iso_date",
    "finishedAt": "iso_date",
    "s3Etag": "etag",
    "s3Size": 123,
    "s3Location": "S3ObjectLocation"
  }
}
```

**Comment by alexwlchan** [comment]
Per discussion with @kenoir, we want to record the output of the snapshot generator somewhere persistent (i.e. not SQS).

The snapshot reporter should be able to find the record of the last snapshot, even if the snapshot generator hasn't run for a couple of days.

We discussed putting it in S3; I suspect putting it in the reporting cluster might be even more useful.

(And record the elapsed time in the snapshot result.)

**Comment by kenoir** [comment]
> We discussed putting it in S3; I suspect putting it in the reporting cluster might be even more useful.

I like this idea.

**Comment by kenoir** [comment]
> The snapshot reporter should be able to find the record of the last snapshot, even if the snapshot generator hasn't run for a couple of days.

A snapshot/catalogue reporter lambda would be triggered by a CloudWatch "cron" event  - so the flow would be something like:

cloudwatch cron -> snapshot_generator lambda -> reporting cluster ES index
cloudwatch cron -> catalogue_reporter lambda (reads from reporting/catalogue ES cluster) -> slack webhook

Rather than the snapshot_generator lambda triggering a report being pushed into slack.

**Comment by alexwlchan** [comment]
Ah, I see it slightly differently.

snapshot_generator
-> posts message to SNS of snapshot done
-> SNS triggers snapshot_recorder Lambda
-> Lambda writes message to reporting cluster

cloudwatch cron
-> triggers catalogue_reporter Lambda
-> Lambda reads from the reporting cluster
-> sends message to Slack webhook

So info about snapshots is available in reporting almost immediately, but not alerted on until the next cron job pops.
