### ISSUE TITLE
Update ID minter and merger to use intermediate pipeline storage

### ISSUE THREAD

**Issue by warrd** [wellcomecollection/platform#4828]
- [ ] Update `id_minter` / `merger` code (https://github.com/wellcomecollection/catalogue/pull/914)
- [ ] Investigate AWS Elasticsearch cluster
- [ ] Deploy AWS Elasticsearch cluster, or set up credentials for Elasticsearch Cloud
- [ ] Deploy new pipeline connected to Elasticsearch, and test

**Comment by alexwlchan** [comment]
This is applied.
