### ISSUE TITLE
How should the bags of Miro images be structured?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4840]
See notes from a call on 13 October 2020: https://github.com/wellcomecollection/platform/issues/4809#issuecomment-707658258

A proposal from that call: top level "folders" for destination (=externalIdentifier prefixes), and per-collection bags within each folder.

```
miro
 ├── cold_storage
 │    ├── A images
 │    │   ├── A001.jp2
 │    │   ├── A002.jp2
 │    │   └── ...
 │    └── ...
 │
 ├── tandem_vault
 │    ├── A images
 │    │   ├── A001.jp2
 │    │   ├── A002.jp2
 │    │   └── ...
 │    └── ...
 │
 └── ...
```

We should work out how big each of these individual bags would be – this will inform our decision.

- [x] How do we organise the bags?
- [x] What if an image went to multiple destinations?

**Comment by alexwlchan** [comment]
Having done some quick analysis, these are our biggest bags:

![Screenshot 2020-10-13 at 12 25 11](https://user-images.githubusercontent.com/301220/95854672-29374e80-0d4f-11eb-83ad-3ef110e2ea70.png)

50k is at the upper limit of what Archivematica can handle – but _might_ be doable. We'd have to test in staging first (and possibly then just copy that bag to prod).

**Comment by alexwlchan** [comment]
What if we kept the per-thousand image prefixes?

```
miro
 ├── cold_storage
 │    ├── A0000000
 │    │   ├── A0000001.jp2
 │    │   ├── A0000002.jp2
 │    │   └── ...
 │    ├── A0001000
 │    │   ├── A0001001.jp2
 │    │   ├── A0001002.jp2
 │    │   └── ...
 │    └── ...
 │
 ├── tandem_vault
 │    ├── A0000000
 │    │   ├── A0000001.jp2
 │    │   ├── A0000002.jp2
 │    │   └── ...
 │    ├── A0001000
 │    │   ├── A0001001.jp2
 │    │   ├── A0001002.jp2
 │    │   └── ...
 │    └── ...
 │
 └── ...
```

Each bag would be small enough to ingest through Archivematica, we're not inventing our own grouping, you can find all the images that went to a given location.

**Comment by kenoir** [comment]
> What if we kept the per-thousand image prefixes?

This sounds like a good compromise.
