### ISSUE TITLE
Client Secret for Archivematica Azure App is expiring soon (31/10/20)

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4841]
The "client secret" which allows users to sign in using their Wellcome Active Directory identity to Archivematica is due to expire on the 31st of October. 

We must update it in Archivematica before then for it to continue to work. It would be nice if we could automate this process, or have a mechanism to remind us this is necessary for next time.

At present only @kenoir can update this secret - another developer should have access in Azure to do so.

This will involve creating a new secret in Azure and updating the correct SecretsManager secret with the new value.

- [ ] Create new secret and move Archivematica to use it.
- [ ] Look at mechanism to "auto-roll" new secrets / set a reminder that secret is going to expire.
- [x] Allow other developers to update client secrets for apps in Azure.

**Comment by alexwlchan** [comment]
If we want to do this in Terraform, https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_password looks promising.

**Comment by alexwlchan** [comment]
Link to discussion in Slack, including the relevant part of the Azure portal: https://wellcome.slack.com/archives/CN56BRQ5B/p1602594530015900

**Comment by alexwlchan** [comment]
Looking at this app again, it looks like I have permissions for a.chan@wellcome.ac.uk, but that account can no longer log into Azure.
