### ISSUE TITLE
Titles from Sierra missing subfield c

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4857]
We current have incomplete titles for some works, which is preventing them from being found in search. This is a particular problem for the MOH reports.

Eg compare:

https://search.wellcomelibrary.org/iii/encore/record/C__Rb2972304

To:

https://wellcomecollection.org/works/sx5gyrem

This is because we are using the `title` property in the Sierra API, which is only taking into account field `245` subfields `a` and `b`. Instead we should be creating the title ourselves by joining `245` subfields `a`, `b` and `c` with a space.

Note that it appears in most (all?) records, that subfield `a` is not explicitly defined, but it is implied from the text content with no explicit subfield. This is the case in this example:

`245 10 [Report 1973] /|cMedical Officer of Health, Leeds City.`

Which should come out as `[Report 1973] / Medical Officer of Health, Leeds City.`

**Comment by alexwlchan** [comment]
> Note that it appears in most (all?) records, that subfield a is not explicitly defined, but it is implied from the text content with no explicit subfield. This is the case in this example:
>
> ```
> 245 10 [Report 1973] /|cMedical Officer of Health, Leeds City.
> ```

I wonder if this is a MARC formatting thing? Lots of lines in the MARC record on b2972304 don't have ǂa explicitly labelled, but when you look at the JSON from Sierra, it's there. e.g.

```json
    {
      "fieldTag": "t",
      "marcTag": "245",
      "ind1": "1",
      "ind2": "0",
      "subfields": [
        {
          "tag": "a",
          "content": "[Report 1973] /"
        },
        {
          "tag": "c",
          "content": "Medical Officer of Health, Leeds City."
        }
      ]
    },
```

**Comment by jtweed** [comment]
Thanks @alexwlchan that's exactly what I couldn't easily see! It must be how it's rendered in the MARC output from Encore, as you say.
