### ISSUE TITLE
Merging should account for suffixes on Miro IDs

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4858]
Image merging is not always taking into account suffixes on Miro IDs. This occurs when the full ID is in 962, but only the ID without the suffix is in 089. This is apparently a thing...

The result of this is that we have a works with two images, when in fact there should be two works with one image each.

Examples:

V0036036EL and V0036036ER
https://wellcomecollection.org/works/ux4zdvpt
 
V0003654EL and V0003654ER
https://wellcomecollection.org/works/uj5yyz5c

Currently, we take IDs from 089 and 962. We should check if the IDs from 962 are the same but with a suffix, and if so, take them over the IDs from 089.

Over time, the plan is still to remove 962, at once point the suffixes will be added to 089. This change will hopefully work in the meantime.

It would also be good to get a list of works where the IDs from 089 and 962 do not match (accounting for zero padding), to determine the scale of this problem and consequently how long it would take Collections Information to fix the IDs in 089.

**Comment by alexwlchan** [comment]
> It would also be good to get a list of works where the IDs from 089 and 962 do not match (accounting for zero padding), to determine the scale of this problem and consequently how long it would take Collections Information to fix the IDs in 089.

I'm running a quick script to dump this data for us.

**Comment by alexwlchan** [comment]
I did a quick run through the Sierra data, and I found 6291 records cases where the Miro IDs we extract from 089 and 962 don't match: [results.xlsx](https://github.com/wellcomecollection/platform/files/5429953/results.xlsx)
