### ISSUE TITLE
Fix the broken certificate on wellcomeimages.org

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4860]
I discovered this when I followed an external link to a wellcomeimages.org page, and got a Cert Expired error from my browser.

- [x] Get the site working again (https://github.com/wellcomecollection/wellcomeimages/pull/2)
- [ ] Set up some monitoring so we'll know if it breaks again (https://github.com/wellcomecollection/wellcomecollection.org/pull/5722)

**Comment by alexwlchan** [comment]
Looking in Certificate manager, this Certificate is marked as "Ineligible" for renewal, so we know why it broke:

![Screenshot 2020-10-26 at 08 19 22](https://user-images.githubusercontent.com/301220/97149025-01d77d00-1764-11eb-8b61-52eebddaec89.png)

(Experience account)

**Comment by alexwlchan** [comment]
To fix this, we'll need to be able to update certs in the wellcomeimages.org hosted zone. We don't currently have access to this – I'll raise a ticket with D&T.

**Comment by alexwlchan** [comment]
This is tracked as ticket REQ0019309

**Comment by kenoir** [comment]
Suggest monitoring is done via updown (which will notify you of certs expiring soon). Should be in code ala the PR on Wellcome collection.org right now.

**Comment by alexwlchan** [comment]
The infra for this site is in its own repo: https://github.com/wellcomecollection/wellcomeimages

A fact I only know because I cleaned up my local copy of the repo yesterday. 🙈

**Comment by jamesgorrie** [comment]
> A fact I only know because I cleaned up my local copy of the repo yesterday. 🙈

Where would you like this listed to make it more discoverable?

**Comment by alexwlchan** [comment]
>>A fact I only know because I cleaned up my local copy of the repo yesterday. 🙈
>
> Where would you like this listed to make it more discoverable?

I think it's fine where it is, possibly too much emphasis on “only”.

I knew immediately *“the infra is in repo X”* rather than having to look around for it.

**Comment by kenoir** [comment]
I've fixed this temporarily, because we got access to do so and I could do it quickly in the console. I can't see where we provision this in terraform - we should, and we should encode an updown check next to where that code is.

**Comment by alexwlchan** [comment]
It's in the wellcomeimages repo; I already have a patch written pending permissions. Will sort out properly on Friday.
