### ISSUE TITLE
Add totalParts and totalDescendentParts to denormalised work relations

### ISSUE THREAD

**Issue by warrd** [wellcomecollection/platform#4861]

**Comment by tomcrane** [comment]
Any chance of this also including totalDescendantPartsThatHaveADigitalLocation? (might want to think of a nicer name).

Scenarios - 

 - building IIIF collections for archival hierarchy as a relatively simple proxy of the catalogue API
 - being able to avoid taking a path through a tree that cannot lead to a viewable (i.e., digitised) object
 - Conveying the relative proportion of digitised stuff across archive collections

... and more.

**Comment by warrd** [comment]
Potentially can do that, @jtweed do we want to add this? :point_up:

**Comment by jtweed** [comment]
I think I'd rather handle those cases by working out how to combine this with location filtering, rather than adding another property. But it's a nice to have for now, not something I can prioritise spending a lot of time on.
