### ISSUE TITLE
Add ISSN from Sierra

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4865]
We need to add ISSN (MARC 022) as a kind of identifier from Sierra, like we currently do for ISBN (MARC 020). Note that like ISBN, ISSN is repeatable.

Identifier type should be `issn`. By adding it as a kind of identifier, it will automatically be searchable like other identifiers.

As part of this ticket, ISSN also needs added to work pages. It should be included in the Identifiers section, in the same way as ISBN.

- [ ] Add ISSN to the catalogue API (https://github.com/wellcomecollection/catalogue/pull/1005)
- [ ] Add ISSN to the works pages (https://github.com/wellcomecollection/wellcomecollection.org/pull/5686)

**Comment by alexwlchan** [comment]
This code is merged, but it needs to be deployed and a reindex run before they appear in the API.
