### ISSUE TITLE
Add digcodes from Sierra

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4867]
Sierra e-bibs contain a Wellcome-specific identifier called a digcode that identifies the digitisation project under which the item was digitised. These are used by staff to quickly locate, for example, all the MOH reports or everything digitised from a partner institution.

We want to add the digcode as a kind of identifier, with an identifier type of `wellcome-digcode`. They are obviously non-unique, as all works digitised under the same project will share a digcode.

Digcodes are in MARC 759, which is repeatable:

```
b22474262

759    digrcs 
759    digukmhl 
```

The value of the digcode should only be the contiguous alphabetic string that starts with `dig`. In the following example the digcode should be `digmoh`:

```
b29500783

759    digmoh(Channel) 
```

These should NOT be added to work pages, they should only be in the API. As they are kind of identifier, they should be automatically picked up by search, as an identifier search.

**Comment by alexwlchan** [comment]
This code is merged, but it needs to be deployed and a reindex run before they appear in the API.
