### ISSUE TITLE
Unrecognised accessConditions in the data coming to the METS transformer

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4871]
We have a handful of source records which are failing in the METS transformer (based on the 2020-11-12) pipeline.

Some of these are caused by accessconditions in the METS that the transformer can't recognise:

**&lt;mods:accesscondition type="dz">A</mods:accesscondition>**

*   b16774073: [s3://wellcomecollection-storage/digitised/b16774073/v1/data/b16774073_0001.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb16774073%2fv1%2fdata%2fb16774073_0001.xml&region=eu-west-1)
* b1665836x: [s3://wellcomecollection-storage/digitised/b1665836x/v1/data/b1665836x.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb1665836x%2fv1%2fdata%2fb1665836x.xml&region=eu-west-1)

**<mods:accesscondition type="dz">B</mods:accesscondition>**

* b18022406: [s3://wellcomecollection-storage/digitised/b18022406/v1/data/b18022406.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb18022406%2fv1%2fdata%2fb18022406.xml&region=eu-west-1)

**<mods:accesscondition type="dz">J</mods:accesscondition>**

* b17222333: [s3://wellcomecollection-storage/digitised/b17222333/v1/data/b17222333.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb17222333%2fv1%2fdata%2fb17222333.xml&region=eu-west-1)
* b1616006x: [s3://wellcomecollection-storage/digitised/b1616006x/v1/data/b1616006x.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb1616006x%2fv1%2fdata%2fb1616006x.xml&region=eu-west-1)
* b17222527: [s3://wellcomecollection-storage/digitised/b17222527/v1/data/b17222527.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb17222527%2fv1%2fdata%2fb17222527.xml&region=eu-west-1)
* b16159949: [s3://wellcomecollection-storage/digitised/b16159949/v1/data/b16159949.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb16159949%2fv1%2fdata%2fb16159949.xml&region=eu-west-1)
* b16160083: [s3://wellcomecollection-storage/digitised/b16160083/v1/data/b16160083.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb16160083%2fv1%2fdata%2fb16160083.xml&region=eu-west-1)
* b18194448: [s3://wellcomecollection-storage/digitised/b18194448/v1/data/b18194448.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb18194448%2fv1%2fdata%2fb18194448.xml&region=eu-west-1)

**<mods:accesscondition type="dz">creativecommons.org/licenses/by/4.0</mods:accesscondition>**

* b20456645: [s3://wellcomecollection-storage/digitised/b20456645/v6/data/b20456645_0001.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb20456645%2fv6%2fdata%2fb20456645_0001.xml&region=eu-west-1)
* b20456645: [s3://wellcomecollection-storage/digitised/b20456645/v7/data/b20456645_0002.xml](https://console.aws.amazon.com/s3/object/wellcomecollection-storage?prefix=digitised%2fb20456645%2fv7%2fdata%2fb20456645_0002.xml&region=eu-west-1)

We should either fix these in the METS source data, or update the transformer to handle them.

**Comment by tomcrane** [comment]
@alexwlchan I don't know if this is useful or not but here's what DDS makes of these:

https://github.com/wellcomecollection/iiif-builder/blob/master/src/Wellcome.Dds/Wellcome.Dds.Repositories/Presentation/LicencesAndRights/LicenceCodes.cs

and 

https://github.com/wellcomecollection/iiif-builder/blob/master/src/Wellcome.Dds/Wellcome.Dds.Repositories/Presentation/LicencesAndRights/LicenceMap.cs#L18

**Comment by alexwlchan** [comment]
Thanks Tom. I suspect we'll just fix these up at source, given there's so few of them, rather than perpetuate these license codes into another system.

**Comment by aray-wellcome** [comment]
@alexwlchan Most of these are items that we no longer want and I've "deleted" them from the storage service so I guess they need removed from the pipeline somehow but I'm not sure how that needs to be done. 

**Deleted**

b16774073 is a film that needs re-ingested but it's corrupted. I've "deleted" it from the storage service until it can be re-digitized.

b1665836x is a film that needs re-ingested but it's corrupted. I've "deleted" it from the storage service until it can be re-digitized.

b18022406 has been deleted from Goobi and the Storage Service

b17222333 has been deleted from Goobi and the Storage Service

b1616006x has been deleted from Goobi and the Storage Service

b17222527 has been deleted from Goobi and the Storage Service

b16159949 has been deleted from Goobi and the Storage Service

b16160083 has been deleted from Goobi and the Storage Service

b18194448 has been deleted from Goobi and the Storage Service

**Updated license**

b20456645_0001 and b20456645_0002 have had their licenses updated to CC-BY now

**Comment by alexwlchan** [comment]
> they need removed from the pipeline somehow but I'm not sure how that needs to be done

That happens automatically when something gets updated in the storage service, so your changes should have fixed it. Thanks!

I'll double-check they came through the pipeline correctly, then close this ticket.

**Comment by aray-wellcome** [comment]
A majority of the deleted ones were deleted a while ago, not today, so I'm not sure they'll remove themselves if they haven't already.

**Comment by alexwlchan** [comment]
Huh, weird. We may need to reindex, okay.

**Comment by alexwlchan** [comment]
Closing in favour of https://github.com/wellcomecollection/platform/issues/4893
