### ISSUE TITLE
Disable merging for audiovisual works from Sierra

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4876]
Audiovisual works are catalogued as multiple bib records in Sierra, one for each physical format and another for the digitised version, where available.

Unlike for other material types, these bibs routinely contain different data and so it's not possible to consider one of them canonical, like we do for other physical/digitised bib pairs from Sierra. This is causing incorrect and missing data for AV material on wellcomecollection.org.

Longer term, Collections Information are going to look again at how AV is catalogued and based on that, we will come up a solution that lets us merge or otherwise group AV works.

In the meantime, we need to disable merging of audiovisual works from Sierra. This should apply to all AV work types (video, audio, film, e-sound, e-videos).

**Comment by alexwlchan** [comment]
List of AV works from the latest catalogue snapshot; firing these IDs into the merger should trigger the necessary reindex:

[av.txt](https://github.com/wellcomecollection/platform/files/5770887/av.txt)

**Comment by alexwlchan** [comment]
This is done and in the live index. 🎉
