### ISSUE TITLE
Change noteType label for lettering note

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4877]
The noteType label for lettering note is currently "Lettering".

As there is already a lettering property, we should disambiguate the note by changing the noteType label for lettering notes to "Lettering note".

**Comment by alexwlchan** [comment]
I was going to suggest doing something similar for the language note.

**Comment by jtweed** [comment]
Yes that's a good point, let's do that one too.

**Comment by alexwlchan** [comment]
Lettering note is fixed: https://wellcomecollection.org/works/nkmdzt8q

<img width="653" alt="Screenshot 2020-11-19 at 09 08 18" src="https://user-images.githubusercontent.com/301220/99645179-cd936b80-2a46-11eb-9169-e88cd262b841.png">

As is language note: https://wellcomecollection.org/works/m6pm7b7g

<img width="518" alt="Screenshot 2020-11-19 at 09 08 51" src="https://user-images.githubusercontent.com/301220/99645232-dd12b480-2a46-11eb-8fe8-2deee037f94e.png">
