### ISSUE TITLE
Rename locationType aggregation to items.locations.type

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4899]
The location type aggregation used for online and in the library filtering does not follow the naming convention for filters and aggregations.

It is currently implemented as `locationType` when it should be `items.locations.type`. The corresponding filter is correctly named `items.locations.type`.

This change will need to be made in conjunction with updating the front end to support the new name.

**Comment by jamesgorrie** [comment]
@jtweed there is two filters here:
1. `items.location.type` => values: `DigitalLocation` | `PhysicalLocation` (used on the frontend)
1. `items.location.locationType` => [Populated with these values](https://github.com/wellcomecollection/catalogue/blob/master/common/internal_model/src/main/resources/location-types.csv)

I imagine what we should be doing as I thought we were going to remove those values from the API is deprecate no 2?

**Comment by jtweed** [comment]
I'm talking about the aggregation that goes with filter 1. It doesn't follow the naming convention of it being named the same as its corresponding filter.

**Comment by alexwlchan** [comment]
The new filter is deployed, but the output needs some tweaking – the aggregation result is still called `"locationType"`.

**Comment by jamieparkinson** [comment]
I believe this is resolved by https://github.com/wellcomecollection/catalogue/pull/1435/files
