### ISSUE TITLE
What happened to https://search.wellcomelibrary.org/iii/encore/record/C__Rb1048224?lang=eng?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4902]
Following Victoria's query in Slack: https://wellcome.slack.com/archives/C8X9YKM5X/p1606737111024800

Also https://wellcome.slack.com/archives/C8X9YKM5X/p1606832023037000

**Comment by jamieparkinson** [comment]
Same issue with this https://search.wellcomelibrary.org/iii/encore/record/C__Rb1110923?lang=eng

The problem will be in the transformer (the merger can't make things invisible). The Sierra transformer makes invisible works when either:
- No bib data is available
- The record is suppressed or deleted
This doesn't seem to be the case for these records - perhaps it didn't come through right?

**Comment by alexwlchan** [comment]
Both this and Jamie's link are working now. These were both a victim of an over-zealous MARC parser disliking the repeated subfield b in MARC 245. https://github.com/wellcomecollection/catalogue/pull/1285
