### ISSUE TITLE
Secure monitoring dashboard: Add OIDC to Kibana

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4909]
`monitoring.wellcomecollection.org` runs Grafana as in ECS task, with an EC2 host instance using a mounted EFS volume to provide persistent storage storage, this is all in a private subnet in the monitoring VPC in the platform account.

Grafana is accessible via a load balancer (in a public subnet in the monitoring VPC) with security group rules that restrict access to Wellcome internal IPs. The current strategy for accessing Grafana (poking security group holes for home IPs) is insecure and inefficient. We should use Grafana's capability to authenticate users via OIDC, using an Azure AD registered applications following the pattern of other staff facing apps on the platform.

A guide to configuring Grafana can be seen here: https://grafana.com/docs/grafana/latest/auth/azuread/

We use the docker hub provided base image for grafana (https://github.com/wellcomecollection/platform-infrastructure/blob/master/monitoring/terraform/stack/grafana/main.tf#L37). 

To add our own configuration and mitigate against docker hub rate limiting we should layer our OIDC config onto the docker hub image and push that into ECR as we do with other images (https://github.com/wellcomecollection/platform-infrastructure/tree/master/images).

**Comment by alexwlchan** [comment]
Grafana is now protected with Azure AD, so we can close this ticket as done.
