### ISSUE TITLE
Public container images: Use ECR public, not private where appropriate

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4910]
Following the Docker Hub rate limit changes breaking automated builds, we moved to using ECR to store our container images - these are now pushed into _private_ ECR repos in the platform account.

Now that [ECR Public](https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-ecr-public-and-amazon-ecr-public-gallery/) is available we should move to pushing out images into public repositories.

We should define these infrastructure to host these common images and their builds in the [platform-infrastructure](https://github.com/wellcomecollection/platform-infrastructure) repository.

**Comment by alexwlchan** [comment]
We should also use ECR Public for our weco-deploy images.

Should we use ECR Public for everything? 🤔

**Comment by alexwlchan** [comment]
It looks like ECR public might only be available in us-east-1, which sucks if true: https://github.com/hashicorp/terraform-provider-aws/issues/18047

**Comment by andormarkus** [comment]
Hi @alexwlchan 

ECR public are created and hosted in `us-east-1` but available globally without issue.

See details in my other comment: https://github.com/hashicorp/terraform-provider-aws/issues/18047#issuecomment-815542537

**Comment by alexwlchan** [comment]
Done.
