### ISSUE TITLE
Investigate NAT Gateway costs in the pipeline

### ISSUE THREAD

**Issue by alicefuzier** [wellcomecollection/platform#4927]

**Comment by alexwlchan** [comment]
We still have some NAT Gateway costs from the catalogue VPC; I'd guess logging and the adapters are probably what's left? See https://github.com/wellcomecollection/platform/issues/5002

**Comment by alexwlchan** [comment]
Closing as done – we've done plenty of costs investigation and got it to a much more manageable level. If we do want to do more investigation, let's open a new ticket.
