### ISSUE TITLE
Remove the last uses of big_messaging

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4935]
Looking through the codebase, the only remaining uses I see are:

* inference manager -> palette inferrer
* images merger -> images ingestor

Those are both sending images, which to my eyes can be sent directly over SNS, and don't need big messaging.

I'd like the pipeline to be a little more stable (i.e. deployable) before we look at this. It will simplify the codebase, but I don't think it will have any impact on pipeline performance.

**Comment by alexwlchan** [comment]
As well as taking out the Scala code, we need to expunge it from the Terraform.

**Comment by alexwlchan** [comment]
We still have some S3 buckets in the Terraform.

**Comment by warrd** [comment]
Ah :+1:
