### ISSUE TITLE
Batcher should modify batch interval based on number of messages in relation embedder queue

### ISSUE THREAD

**Issue by warrd** [wellcomecollection/platform#4938]

**Comment by alexwlchan** [comment]
This has sat in “to do” for three months, and I don’t think the batcher has been a major pain point.

I’m going to leave the ticket open, but remove it from “to do” for now.

**Comment by alexwlchan** [comment]
I'm going to close this for now – the batcher does sort-of do this, in Terraform.

When we're reindexing (and the relation embedder queue is likely to be big), it waits a long time and has a big queue.

When we're not reindexing (and the relation embedder queue is likely to be small), it doesn't wait as long and has a smaller queue.
