### ISSUE TITLE
Fix use of namespace/path in our DynamoDB tables

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4944]
We currently have two location models floating around in our DynamoDB tables:

```
ObjectLocation(namespace: String, path: String)   // old
S3ObjectLocation(bucket: String, key: String)     // new
```

We have a custom DynamoFormat decoder so that our apps can read the old model and parse it as the new model, but it's fiddly and annoying whenever I'm running scripts against the tables.

I want to do a one-off migration that rewrites all instances of the old model as the new model, then delete the custom decoder.

**Comment by alexwlchan** [comment]
This should all be fixed in the storage account. All but one record (can you guess which one*?) was already in the new format.

*Hint: it rhymes with “Flemist and Bruggist”

**Comment by jamesgorrie** [comment]
Someone who is into Flemmish specifically from Bruges?

**Comment by alexwlchan** [comment]
Something like that.

(Chemist & Druggist has been a persistent thorn in the storage service.)
