### ISSUE TITLE
Determine relationships that will be added to the pipeline and produce stats

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#4970]
In order to ensure that the catalogue pipeline will scale to accommodate relationships that will be added to the catalogue pipeline in the next 2 quarters we need to understand the nature of that data.

We should find out what those relationships will be from @jtweed and run an analysis on the likely depth & breadth of the and number of graphs that need to be stored, alongside what data should be denormalized onto works.

**Comment by alexwlchan** [comment]
We think this is probably fine for journals; we need to look at series data in Sierra to confirm this isn't going to be an issue.

**Comment by kenoir** [comment]
Closing as done/not useful anymore.
