### ISSUE TITLE
Decide how we're going to model holdings data

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4992]

**Comment by alexwlchan** [comment]
Here's a quick sketch of how the data is modelled in Sierra:

<img width="581" alt="Screenshot 2021-01-26 at 14 46 24" src="https://user-images.githubusercontent.com/301220/105860235-44b82380-5fe5-11eb-8dd2-1fea496172b2.png">

A holding can link to bibs and items. In practice, almost all of our holdings link to a single bib (the exceptions are 1071627 and 1083326). A holding can link to any number of items.

An item can link to any number of bibs, and the same bib may be linked from multiple items.

**Comment by alexwlchan** [comment]
Can we make a Work from a holding record?

Not on its own – we rely on a bunch of Sierra varfields to construct a Work from a bib record, most of which aren't present on holdings records. I did some analysis of all the non-deleted holdings:

<table>
<tr><td><code>&nbsp;&nbsp;&nbsp;</code></td><td>7</td></tr>
<tr><td><code>000</code></td><td>2</td></tr>
<tr><td><code>561</code></td><td>3</td></tr>
<tr><td><code>596</code></td><td>1</td></tr>
<tr><td><code>843</code></td><td>262</td></tr>
<tr><td><code>852</code></td><td>1</td></tr>
<tr><td><code>853</code></td><td>10341</td></tr>
<tr><td><code>854</code></td><td>84</td></tr>
<tr><td><code>855</code></td><td>9</td></tr>
<tr><td><code>856</code></td><td>9386</td></tr>
<tr><td><code>860</code></td><td>1</td></tr>
<tr><td><code>863</code></td><td>10344</td></tr>
<tr><td><code>864</code></td><td>85</td></tr>
<tr><td><code>865</code></td><td>7</td></tr>
<tr><td><code>866</code></td><td>31856</td></tr>
<tr><td><code>876</code></td><td>1</td></tr>
<tr><td><code>949</code></td><td>997</td></tr>
<tr><td><code>989</code></td><td>27214</td></tr>
<tr><td><code>990</code></td><td>1</td></tr>
</table>

The 8xx fields are all used for holdings information; the 9xx fields are only loosely defined in the MARC spec/OCLC and I'm not sure what they're used for. A brief glance suggests nothing useful for building Works.

**Comment by alexwlchan** [comment]
Another useful discovery: the bib/item links seem to be consistent.

That is to say: **if a holding links to a bib and an item, then the item links to the bib.**

**Comment by alexwlchan** [comment]
Tomorrow I might try actually constructing some works + items with different merging strategies.

**Comment by pollecuttn** [comment]
Something to note is that requests can only be made against items, not holdings. So if you want to request something from closed stores, there needs to be an item record to request.

**Comment by kenoir** [comment]
Can you describe what a holding is and how it relates to journals?

**Comment by alexwlchan** [comment]
> Can you describe what a holding is and how it relates to journals?

In general library science, the “holdings” are the things the library actually owns. (Because it’s what the library holds.)

At Wellcome, the “holdings records” in Sierra are used to track things which are issued in multiples – like journals or serials.

Sierra has “check-in cards” for tracking the individual issues of a journal. It records what issues of a journal we've received, predicts what we're expecting to receive, and highlights when an issue has gone missing. That’s not something we’ll use in the catalogue, but it seems to be the distinction between “items” and “holdings”. An item is received once and goes on the shelves; a holdings is something we expect to receive new issues.

See the [thread in #collections-info](https://wellcome.slack.com/archives/CGXDT2GSH/p1611673449028200) where several people explained this in more detail.

Holdings are a separate resource in the Sierra API (like bibs or items), and use a different set of MARC fields.

The discussion I’m having in this ticket – and also privately with Jonathan – is how this data fits into the Catalogue API. How do those fit into our Work/Item model?

**Comment by alexwlchan** [comment]
FWIW, my current preference would be to combine holdings/journals with our current Item model.

In our model, the Work is the intellectual entity, and the Item is the physical/digital manifestations of a Work. Both item and holdings records in Sierra feel like they‘re similar to an Item, and I don’t think the distinction is worth propagating into the Catalogue API.

**Comment by alexwlchan** [comment]
Quick note: MARC tag 843 is "reproduction note"; see https://www.loc.gov/marc/holdings/hd843.html

We already have a "notes" field on Works, so I'm going to assume for now that I can ignore that.

**Comment by alexwlchan** [comment]
Just to throw some extra fun into the mix: some of the bib records don't have associated items but do have associated holdings, e.g.

<img width="835" alt="Screenshot 2021-02-02 at 12 37 43" src="https://user-images.githubusercontent.com/301220/106601436-8865dc80-6553-11eb-9785-97b71ca2f972.png">

I think there's enough information for an instance of our Item model there; do we put holdings into the "items" field if there are no other items?
