### ISSUE TITLE
Add license aggregation to images endpoint

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#4994]
As part of the ongoing improvements to filtering, we'd like add license filtering to image search.

There is already a `locations.license` filter on the images endpoint, but to add the filter to the front end we need to add the corresponding aggregation.

This means adding support for aggregations to the images endpoint, which should be done in the same way as we do already for works.

We should end up with the following request:

`?/images?locations.license=cc-by&aggregations=locations.license`

With the response adding an `aggregations` property with the same model as for aggregations on works.

**Comment by alexwlchan** [comment]
This is done: https://api.wellcomecollection.org/catalogue/v2/images?locations.license=cc-by&aggregations=locations.license
