### ISSUE TITLE
Cloudfront => DLCS rules

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#4997]
Successor to #4603 

Some of this has been done but not all - we need to get ALL DLCS paths rewritten by Cloudfront.
@kenoir has already done some of this, e.g., Loris paths to wellcome space 8 - we should get ALL the rules in place now.

Default route => wellcome/5/*
iiif-test => wellcome/6

Need to ensure that Edge lambdas put enough info into headers for DLCS to see the original host and the original path.
DLCS will need to make info.json @ids match the client request URL.

This allows us to put iiif.wc.org image paths into the generated manifests ASAP.

**Comment by tomcrane** [comment]
Need to support this:

```
        ____
https://iiif.wellcomecollection.org/image/b28047345_0032.jp2/info.json 
   => https://dlcs.io/iiif-img/wellcome/5/b28047345_0032.jp2/info.json
                                       _^_
        _________
https://iiif-test.wellcomecollection.org/image/b28047345_0032.jp2/info.json 
   => https://dlcs.io/iiif-img/wellcome/6/b28047345_0032.jp2/info.json
                                       _^_
```

And the DLCS needs to put the correct host and path back into the `@id` of the info.json.

**Comment by donaldgray** [comment]
Opened a PR in platform-infra for this (https://github.com/wellcomecollection/platform-infrastructure/pull/117) and in iiif-builder-infra (https://github.com/wellcomecollection/iiif-builder-infrastructure/pull/30)

Initially doing stage + test environments. Will copy config for production once these have been tested.
