### ISSUE TITLE
wellcomelibrary.org CloudFront setup

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#5004]
Ref #4977

- [x] Create new CloudFront with `stage.wellcomelibrary.org` alias
- [x] Point `stage.wellcomelibrary.org` DNS to it ☝️ 
- [x] Have CloudFront rewrite the `Host` header to `wellcomelibrary.org` (all applications further down the chain require this)
- [x] Create [DDS DMZ](https://github.com/wellcomelibrary/dds-ecosystem/blob/new-storage-service/wellcome-dds/Wellcome.Dds.Server/doc/TopLevelSystems.png) origin  
- [x] Create behaviour for all traffic to forward to `DDS_DMZ_origin` ☝️ 

Once this is tested, we can:
- [x] replicate the CloudFront distro with wellcomelibrary.org alias
- [x] test with a locally set DNS change to point to this distro ☝️ 
- [x] change the public DNS

**Comment by kenoir** [comment]
Nice.

Some suggestions:
- The CloudFront distros go alongside the others here: https://github.com/wellcomecollection/platform-infrastructure/tree/master/cloudfront.
- You can do a partial redirection of traffic in Route53 (using multivalue/weighted records), which would be a safe way to approach moving public traffic.

**Comment by tomcrane** [comment]
This looks good to me.

> Have CloudFront rewrite the Host header to wellcomelibrary.org

I don't _think_ there's anything that would need the appearance of this from the client side too - e.g., cookies should be *.wl.org
And if there is, those bits can be tested ad hoc by host file modification locally.

**Comment by kenoir** [comment]
Closing as done.
