### ISSUE TITLE
Switch miro transformed works to have locations with new ID format

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5023]
Decommissioning Loris and moving to DLCS allows us to use new style ids (Miro IDs without `.jpg` on the end).

In order to do that we should update the miro transformer to reflect the new ID schema.

Depends on https://github.com/wellcomecollection/platform/issues/5007
Part of https://github.com/wellcomecollection/platform/issues/4884

**Comment by alexwlchan** [comment]
See https://github.com/wellcomecollection/catalogue/pull/1403

**Comment by alexwlchan** [comment]
This is done and deployed!
