### ISSUE TITLE
Supress |5 on notes fields

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#5024]
We should suppress subfield 5 on all notes fields as it's used for system information, which is of no use to people using our search.

**Comment by pollecuttn** [comment]
Hi @jamesgorrie , this issue was closed but I'm still seeing UkLW on https://wellcomecollection.org/works/thjctx62

**Comment by alexwlchan** [comment]
@pollecuttn This was awaiting a reindex before the change was applied; I've done that now, and it's no longer appearing on that work.

**Comment by pollecuttn** [comment]
@alexwlchan Thanks for letting me know!
