### ISSUE TITLE
Viewing suppressed digital objects

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#5044]
To build a IIIF manifest, new DDS (iiif-builder) requires that the b number has a METS file, **_and_** the b number can be found in the Catalogue API (i.e., the DDS can obtain a `Work`).

However, works that are **suppressed** in Sierra don't appear in the Catalogue API. Which means iiif-builder can't build a manifest for them.

The Digital Production Team need to be able to view suppressed works. The binary content (video, audio, images) will be protected by access control (`clinical` or `restricted`), but we still need a IIIF manifest to carry that content into a viewer, so that it can be seen in a controlled environment (like the DDS dashboard).

This means we need to be able to build a manifest without a `Work` - from METS only. And that this manifest doesn't appear in aggregations; you need to know the bnumber to see the manifest, and you need credentials to see its media content.

**Comment by tomcrane** [comment]
@jtweed shall we close this? Wontfix (for the time being).

**Comment by jtweed** [comment]
Yes, I'll do that now.
