### ISSUE TITLE
Handle multiple Provider elements for pdf-coverpage

### ISSUE THREAD

**Issue by donaldgray** [wellcomecollection/platform#5048]
Some items (e.g. b24967646 and b21478909) have multiple provider elements in the P3 manifest.

These should be handled and render multiple logos etc on the pdf coverpage.

**Comment by tomcrane** [comment]
For additional providers, don't squeeze them in next to wc,org at the bottom. Just add a simple extra field at the top - contents TBC.

**Comment by donaldgray** [comment]
Rendered additional provider under "Provider" label - this can be easily changed if need be.

e.g. [b21478909.pdf](https://github.com/wellcomecollection/platform/files/6230059/b21478909.pdf)

PR - https://github.com/wellcomecollection/iiif-builder/pull/130

**Comment by donaldgray** [comment]
#4734 has previous discussion on content
