### ISSUE TITLE
Multiple Manifestations with only one Manifestation

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#5054]
About 0.3% of image-based works (e.g., books) are represented in METS as multiple manifestations with only one manifestation.

In the old DDS, with the intermediary (and pre-IIIF API) _package model_, this becomes a single manifest:
https://wellcomelibrary.org/iiif/b30775139/manifest

In the new DDS, the path from METS to IIIF is more direct and faithful, including using identifiers from the METS for the IIIF resources. So, faithfully following the METS, b30775139 becomes a IIIF Collection, like any other multi-volume work:

https://iiif-test.wellcomecollection.org/presentation/v2/b30775139

... with only one volume in it:
https://iiif-test.wellcomecollection.org/presentation/v2/b30775139_0001

Do we want to leave it like this, respecting the METS and its identifiers, or do we want to hide this? And if we want to hide it, what is the URL of the manifest? Does https://iiif-test.wellcomecollection.org/presentation/v2/b30775139 become the manifest?

**Comment by donaldgray** [comment]
b21709087, b29326576, b22012722 and b22038991 are further examples

**Comment by tomcrane** [comment]
This will still work in the UV etc. It just has a pointless parent/child relationship.

**Comment by tomcrane** [comment]
V3 version (conneg defaulting to v3) https://iiif-test.wellcomecollection.org/presentation/b30775139

**Comment by donaldgray** [comment]
As discussed in Slack - we will leave this as-is.

Leaving this ticket open and assigning to me as I'll need to update comparer to _not_ instantly fail as `@type` differs

**Comment by donaldgray** [comment]
Closing issue - comparer tool was precursor to verifying manifests before release but everything is live now.
