### ISSUE TITLE
Redirect Library DServe URLs

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5058]
Redirect DServe URLs to https://wellcomecollection.org/works/{work_id} OR https://wellcomecollection.org/works?query={query}

* `dsqItem` can hold a RefNo.
* `dsqSearch` hold search info. It can contain a few different searches - taken from GA:

http://archives.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqDb=Catalog&dsqCmd=NaviTree.tcl&dsqField=RefNo&dsqItem=PPMEL/C

http://archives.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqDb=Catalog&dsqCmd=show.tcl&dsqSearch=(RefNo==%27PPADA%27)

http://archives.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqCmd=Show.tcl&dsqDb=Catalog&dsqPos=2&dsqSearch=%28%28%28text%29%3D%27wa%2Fhmm%27%29AND%28%28text%29%3D%27durham%27%29%29

http://archives.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqCmd=Show.tcl&dsqDb=Catalog&dsqPos=0&dsqSearch=((AltRefNo=%27MS%27)AND(AltRefNo=%27542%27))

http://archives.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqCmd=Show.tcl&dsqDb=Catalog&dsqPos=0&dsqSearch=(AltRefNo='sa/whl')

| Search | Field | Redirection 
| --- | --- | --- |
| `dsqItem=PPMEL/C` | `RefNo` | https://wellcomecollection.org/works/cbms2pg6 |
| `dsqSearch=(RefNo=='PPADA')` | `RefNo`| https://wellcomecollection.org/works/jwj9b483
| `dsqSearch=(((text)='wa/hmm')AND((text)='durham'))` | `query` | https://wellcomecollection.org/works?query=wa/hmm%20durham |
| `dsqSearch=((AltRefNo='MS')AND(AltRefNo='542'))` | `query` | https://wellcomecollection.org/works?query=MS%20542 |
| `dsqSearch=((AltRefNo='MS.532')` | `query` | https://wellcomecollection.org/works?query=MS%20542 | https://wellcomecollection.org/works/r2dtstft |
| `dsqSearch=(AltRefNo='sa/whl')` | `query` | https://wellcomecollection.org/works/fjg4s86y |

**Comment by kenoir** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/2024994-current-quarter-by-hierarchy/features/6699468/detail

**Comment by jamesgorrie** [comment]
@kenoir that URL in the comment links to an error?

**Comment by jamesgorrie** [comment]
Looks like any query text is wrapped in single quotes - `'{text}'`- I am going to match on that, and `join` with a space - ` ` - and then do a look up.

If we have an identifier that matches exactly, then we will redirect to that item, else, we will redirect to `query={text}`
