### ISSUE TITLE
Redirect CM7 (Library Content Management system) URLs

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5080]
Redirect CM7 URLs to https://wellcomecollection.org/some-page-with-content

Example URL:

https://wellcomelibrary.org/using-the-library/visiting-the-library/how-to-find-us/)

Note: This mapping will be provided by @jennpb and library support

--- 

- [x] /events URLs (https://wellcomelibrary.org/events/sex-and-the-city-jun-2013/)
- [x] Static redirects (https://github.com/wellcomecollection/platform-infrastructure/pull/127)
- [x] TBD ...

**Comment by pollecuttn** [comment]
For redirections, see wellcomelibrary.org tab on 
https://wellcomecloud.sharepoint.com/:x:/s/wcdigitalexperience/EVeHngngpGVCl16B3AzCzcsBcTCMXYVGAp9x8tK9fWCK4Q?e=6ufmxM
