### ISSUE TITLE
Redirect Library API URLs

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5081]
For URLs of the form:
- https://wellcomelibrary.org/service/{service_name}/{bnumber}
- https://wellcomelibrary.org/iiif/{bnumber}/manifest

Redirect to path issued when looked up at: https://iiif.wellcomecollection.org/wlorgp/{path}

Example URL:

https://wellcomelibrary.org/service/fulltext/b17548779
https://wellcomelibrary.org/iiif/b17548779/manifest

**Comment by tomcrane** [comment]
wellcomelibrary.org paths that should go to this service are:

```
iiif/*
service/*

ddsconf/*
dds-static/*
annoservices/*
goobipdf/*

```

**Comment by tomcrane** [comment]
All redirects issued by the CF lambda must support CORS - they must include an `Access-Control-Allow-Origin: *` header.

Otherwise, script-triggered requests can't follow the redirects.
