### ISSUE TITLE
Make our Scala libraries usable to other devs

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5106]
One of the major bars to anyone else using our code is the fact that our Scala libraries are only available from a private S3 bucket.

We should find a way to either:

1. Publish some jars to a public package repository, or
2. Make that S3 bucket available

**Comment by kenoir** [comment]
Pushing things into Maven Central was annoying as I remember (maybe it's got easier). I'd prefer that over making the S3 bucket public if it's doable. 

Obviously with public buckets, cost is a consideration - but I don't think we'd ever run into a situation where we had so many downloads to make it a problem.

**Comment by alexwlchan** [comment]
I thought it was the Scala package repo that was the issue, but I may have forgotten.

We may also be able to get around this by giving out credentials to the bucket, Digirati-style, to devs we know are working with the code, or providing instructions for building our libs locally.
