### ISSUE TITLE
London's Pulse (MoH reports)

### ISSUE THREAD

**Issue by tomcrane** [wellcomecollection/platform#5114]
- [x] Obtain backup of current MoH SQL Server instance from D&T
- [x] (not on AWS) restore this backup to a SQL Server instance of the same version
- [x] (not on AWS) upgrade this database to the latest version of SQL Server supported by AWS RDS
- [x] Create Terraform for RDS instance
- [ ] ~Create Terraform for MoH API service layer (formerly part of DDS) - .NET Core webapp~ (no need for separate app)
- [x] Create Terraform for MoH Front End application - .NET Core webapp
- [x] Create AWS RDS instance from this upgraded database
- [x] Refamiliarise with existing MoH ASP.NET WebForms application
- [x] Migrate MoH Service layer to .NET Core
- [x] Migrate MoH Web Application to .NET Core
- [x] Migrate CM7 MoH content to “static” view content (HTML in Razor views)
- [x] Migrate additional services (full text dumps etc)
- [x] Replace Flash-based “copy to clipboard” with browser API
- [ ] Determine what cookie consent banner (if any) should appear on MOH
- [x] Tests for above throughout

To be determined:

I suspect that this is _not_ part of the iiif-builder repo. Logically it's an application consuming IIIF services as well as adding its own. We'll see what dependencies it has but I think we should start assuming it's self-contained, and clearly a port of the existing site.

e.g., at https://github.com/wellcomecollection/londons-pulse

...rather than /moh or similar which might be reserved for a new (not just London) MOH app.

The MOH API was part of old DDS, but that doesn't mean the ported version has to be.

**Comment by tomcrane** [comment]
MOH will continue to live at wl.org/moh/

Which means that its traffic should be forwarded to this new app (rather than redirected to wc.org or iiif.wc.org).

Details here: https://github.com/wellcomecollection/platform/issues/4755#issuecomment-828551472

**Comment by donaldgray** [comment]
PR created in platform-infrastructure to create basic VPC infrastructure https://github.com/wellcomecollection/platform-infrastructure/pull/168

**Comment by donaldgray** [comment]
Backup restored to AWS and basic infrastructure created with deployment pipeline. PR: https://github.com/wellcomecollection/londons-pulse/pull/1

**Comment by tomcrane** [comment]
@kenoir @jamesgorrie
(and cc @donaldgray)

There is a little bit of routing work required to make the ported MOH site live.

Unlike all the other things, it will still live at the hostname `wellcomelibrary.org`. 
The application currently previewed at https://moh.wellcomecollection.digirati.io/ will handle the /moh/ path as well as few other top level paths, that will cater for embedded viewers out there on other web sites.

Here's a list of the wl.org paths that should _pass through_ to this app (copied from https://github.com/wellcomecollection/londons-pulse#paths-handled):

This application should receive all requests for `wellcomelibrary.org/xxx/`, where `xxx` is any of:

* `moh` - the web application and service API
* `spas` - single page web applications - in this case, the Universal Viewer. This keeps the same wellcomelibrary.org address as before, which means any embdedded UV instances will keep running.
* `assets` - page furniture used by the wellcomelibrary.org site (CSS, fonts, icons and images)
* `plugins` - mainly the timeline - also embeddable, therfore also preserving its wellcomelibrary.org path
* `scripts` - JavaScript used by the wellcomelibrary.org site
* `timelines` - The timeline JSON data

I'm not sure what needs to be connected together to make these routes go to the fargate service also served by https://moh.wellcomecollection.digirati.io/. To be clear, there are **no redirects** for the above paths - just routing through to the new MOH service on fargate.

I have also updated the wlorgp lookup service via https://github.com/wellcomecollection/iiif-builder/pull/167, so that the lambda redirect service knows about former MOH api paths. 

Some examples:

1. wellcomelibrary.org/moh/ - passes through to this new fargate service.
2. wellcomelibrary.org/assets/css/main.css - passes through to this new fargate service.
3. wellcomelibrary.org/service/moh/search?q=x - lambda matches /service/* as now, redirects where it's told to, which will be:
4. wellcomelibrary.org/moh/service/search?q=x - same as 1, so passes through to this new fargate service.

Why the 3 and 4 weirdness? Because all the other non-moh `wl.org/service/*` paths get redirected to various iiif.wc.org endpoints, but service/moh/* should not; what was being handled under that will now be handled by wl.org/moh/service/*. We have to flip it round to partition off moh/service under the "paths handled by wl.org" above.

This shouldn't be done immediately, there are a few more tweaks to make before wl.org stops routing to the current Euston Road load balancer and starts passing the above paths through to this new service. Should be ready by end of the week though, if not tomorrow.
