### ISSUE TITLE
Catalogue data for global manuscripts

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5118]
- [x] Implement the key fields we need for the cataloguers to be happy https://github.com/wellcomecollection/catalogue-pipeline/issues/1959
- [ ] Fix the outstanding issues on the TEI works https://github.com/wellcomecollection/catalogue-pipeline/issues/1970
- [x] Enable the toggle by default
- [x] Remove the split pipeline and the toggle
- [x] Make sure the TEI adapter uses credentials from @weco-bot, not a personal account created by Alice

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4915062

**Comment by alexwlchan** [comment]
Link to the mapping document: https://github.com/wellcomecollection/wellcome-collection-tei/blob/main/docs/frontend/draft.md
