### ISSUE TITLE
Access to subscription resources

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5120]
## Measures

- Members can sign in to access subscription resources

- Subscription resources can be viewed on and off site

- C&R can access reporting on subscription access

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4845061

**Comment by pollecuttn** [comment]
To do
- [ ] update [databases page](https://wellcomecollection.org/pages/YDaP2BMAACUAT7DS) - by Digital Editorial
- [ ] check Sierra for any remaining WAM or Shibboleth links - by Library Systems Support, due 31/1/22
