### ISSUE TITLE
Improve searching within an archive

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5123]
Searching within an archive collection, by providing a reference number or part of title as part of the query, is not working as well as expected.

Researchers will often try and find if there are things within a collection by including the collection title in their query. Reference number search is used frequently try and restrict to items that are part of a given collection, especially by staff and when trying to help users find part of an archive.

Whilst it would be great to have a full search within on archives work pages, we need to support it as part of a normal search to minimise the work required at this stage.

This is the last remaining work needed to get support from Collections Information to start redirecting archives.wellcomelibrary.org and decommission DServe.

### Part of titles

Try on both http://archives.wellcomelibrary.org and the new search:

- eugenics society annual reports

### Reference number

For the search: `wa/hmm durham`

https://wellcomecollection.org/works?query=wa%2Fhmm+durham
returns 7 results, only 1 of which is relevant

Whereas:

http://archives.wellcomelibrary.org/DServe/dserve.exe?&dsqIni=Dserve.ini&dsqApp=Archive&dsqDb=Catalog&dsqCmd=Search.tcl
returns 13 results, 10 of which are relevant

**Comment by alexwlchan** [comment]
Currently we index the `otherIdentifiers` value as a keyword:

```json
"otherIdentifiers" : {
  "properties" : {
    "value" : {
      "type" : "keyword",
      "normalizer" : "lowercase_normalizer"
    }
  }
},
```

The same is true for `sourceIdentifier`. I wonder if we'd get better results if we indexed that as a keyword with text, and threw some sort of analyser at it?

**Comment by jtweed** [comment]
We have the parent reference numbers denormalised into the partOf relations, which would be much easier than trying to analyse ids...

**Comment by jtweed** [comment]
I've updated the ticket to include looking at ancestor titles, in addition to reference numbers.
