### ISSUE TITLE
Lifecycle TIFFs to Glacier storage

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5124]

**Comment by aray-wellcome** [comment]
b19371846 was been sent to the storage staging service yesterday evening. There's 10 tiffs and 10 jp2s all at standard storage right now.

**Comment by alexwlchan** [comment]
I see the appropriate tags on the first TIFF in S3, so we're good here. Roll on the TIFF workflow!

<img width="1216" alt="S3 console showing a Content-SHA256 and Content-Type=image/tiff tag on an object" src="https://user-images.githubusercontent.com/301220/114670147-9b86ec80-9cfa-11eb-8c42-45063871e235.png">
