### ISSUE TITLE
Add information about Copies On Order to the catalogue API

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5139]

**Comment by jtweed** [comment]
## Examples

### On order

https://search.wellcomelibrary.org/iii/encore/record/C__Rb3225499?lang=eng
https://wellcomecollection.org/works/em2m8cr3

https://search.wellcomelibrary.org/iii/encore/record/C__Rb3225610
https://wellcomecollection.org/works/ztw9vv2d

https://search.wellcomelibrary.org/iii/encore/record/C__Rb3225507
https://wellcomecollection.org/works/j7yhnukg

### Being processed

https://search.wellcomelibrary.org/iii/encore/record/C__Rb3185468
https://wellcomecollection.org/works/zxvdgnxe

https://search.wellcomelibrary.org/iii/encore/record/C__Rb3219155?lang=eng
https://wellcomecollection.org/works/upjxxcm5

https://search.wellcomelibrary.org/iii/encore/record/C__Rb1680178?lang=eng
https://wellcomecollection.org/works/fuf3a37s

**Comment by jtweed** [comment]
For how we model this, I think the most obvious route is to add a new `locationType` of `on-order` that works like the existing `on-exhibition`.

The text in the Encore examples above is not the current version, which is the version as seen in the OPAC. That looks like:

- Ordered for Wellcome Collection on [date].
- Being processed for Wellcome Collection.

It's possible we may want to tweak those slightly when we get this on the page and see it in situ, but let's start with those for now as they are the currently agreed text.

**Comment by jtweed** [comment]
As for where the data comes from, there are separate order objects in Sierra, but looking at the reporting, it's possible that everything we need is already denormalised onto the bib.

There are certainly fields on there for orders, including order date and number of copies. They will also I think all have the same location code in Sierra of `acql`.

**Comment by alexwlchan** [comment]
### On order

Running a query against the bibs data in the reporting cluster for bibs with the `orders` field populated turns up 141 results:

```http
GET /sierra_bibs/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "exists": {
            "field": "orders"
          }
        }
      ]
    }
  },
  "size": 10000
}
```

That includes your examples that are on order, but not processing. I need to dig around a bit more to find those.

Of those, 140 have the location code `acql` and one has the code `whml` (Open Shelves) – but that item has a suppressed bib (b1561122x). So I think we ignore the value of that location code for now.

Of those 141 examples, none of them have any associated items yet – presumably because the items won't be created until the thing actually arrives.

The text currently visible on wellcomelibrary.org (e.g. *"1 copy ordered for Wellcome Library on 28-02-2020."*) is dynamically generated by Encore. The underlying bib record breaks out the number of copies and the data as structured data, so we can change it as part of this work.

### Proposal

For every entry in the `orders` field on a bib, we create an unidentified Item. The item will have a single location, with fields populated as follows:

- The "label" will be a sentence *"X copies ordered for Wellcome Collection on 20 April 2021."*

    - It's on the Wellcome Collection site, not Wellcome Library
    - That date format is a little more friendly, and matches what we do on stories
    - Plural-aware, obviously

- The "locationType" field will be a new physical location type `on-order`.

**Comment by alexwlchan** [comment]
There's a [thread in Slack](https://wellcome.slack.com/archives/CGXDT2GSH/p1619008186183900) where I got some useful information from Nicola and Alexandra.

We will need to bring in the Order records, oh well.

So here's the proposed procedure:

* If a bib has no items, but it has an `order` directly on the bib record, we put _"X copies ordered for Wellcome Collection on 20 April 2021."_

    - Collection, not Library
    - A friendlier date format to match our style guide for stories
    - Plural aware, obviously

* If a bib has no items, but it has an associated `order` with STATUS (FF20) of `a` ("fully paid"), we put _"X copies awaiting cataloguing."_ on the works page.

    - A less Americanised term
    - Doesn't imply we're actively attending to something
    - Gives staff a visual clue that something is happening
    - When a book arrives it's "received" and the RDATE (FF17) on the order record gets populated. We don't expose the received date publicly on the old site; I'm not going to change that in the initial implementation. Unfortunately this causes the order to drop off the bib, so we will need to bring them in.

* If a bib has _any_ items, we ignore all the attached order records.

Note: bringing this data into the Sierra adapter will add it to the reporting cluster, so it'll be easier for us to look for anomalies (e.g. bibs that have outstanding order records and also items).

**Comment by alexwlchan** [comment]
Straggling issues:

- We should de-duplicate items, e.g. https://api.wellcomecollection.org/catalogue/v2/works/j7yhnukg?include=items
- 323 works are dropping some sort of error, which we should investigate:

    ```
    {'order has unrecognised STATUS Some(z).  How do we handle it?': 13,
     'order has unrecognised STATUS Some(1).  How do we handle it?': 4,
     'order has unrecognised STATUS Some(2).  How do we handle it?': 1,
     'order has unrecognised STATUS Some(f).  How do we handle it?': 3,
     'order has unrecognised STATUS Some(c).  How do we handle it?': 1,
     "order has STATUS 'a' (fully paid) but no RDATE.  Where is this item?": 301}
    ```
