### ISSUE TITLE
Fetch the status of multiple items in a single Sierra API request

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5165]
Right now, we fetch the item statuses in serial:

```scala
items.foreach { item =>
  SierraService.getItemStatus(item.id)
}
```

That makes one HTTP request per item, yuck. I reckon you could query for multiple items at once.

**Comment by kenoir** [comment]
The III API documentation indicates how to do this: https://sandbox.iii.com/iii/sierra-api/swagger/index.html#!/items/Get_a_list_of_items_get_1

**Comment by kenoir** [comment]
Closing as done.
