### ISSUE TITLE
Do users understand how to scroll vertically through pages

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/platform#5170]
**What is the problem to solve?**
Navigation was changed from lateral to vertical on 13/1/21. This research is to determine whether this change has affected users' ability to navigate a document.

**What stage of research is it? (discovery/general usability testing/post release)**
general usability testing

**What are the objectives?**
measure % of users who view page.query.canvas > 1 of total users who view non-image items

**What are the assumptions?**
users with page.query.canvas > 1 for any of their views are able to navigate away from page 1 
all other users are unable to figure out how to navigate the document

**What research technique is required?**
data analysis in Python

**Acceptance criteria**
Chi-squared testing for users during a 2-week period before and after 13/1/21

**Comment by taceybadgerbrook** [comment]
This research builds on findings from manifest usage analysis:
https://github.com/wellcomecollection/wellcomecollection.org/issues/6385

**Comment by kenoir** [comment]
Closing as outdated,
