### ISSUE TITLE
In the Visual Collections, use 001 as a reference number, not a shelfmark

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5172]
Spun out from https://github.com/wellcomecollection/platform/issues/5147

Items in the Visual Collections have iconographic identifiers (e.g. `778151i`). This is stored in field 949 ǂa on the Sierra item record, which we currently map to the "shelfmark" field in the API.

It's arguably correct to call them shelfmarks. These identifiers can printed on the call slips when an item is requested, and the LE&E team use them to find objects in the stores. (There's probably limited scope for changing the Sierra data – we don't want to break the LE&E requesting process.)

These identifiers have also been used in external references. They need to be searchable and visible in the catalogue – we can't just memory-hole them.

Fortunately, these identifiers are also available on field 001 of the bib record.

If an item is in the Visual Collections (material type `k`/Pictures or `r`/3D Objects) and has a non-empty value in the 001 field, we will:

* Not show a shelfmark in the item location
* Put the value in 001 in the referenceNumber field

## Why not use the value from 949 ǂa?

The iconographic numbers in 949 ǂa are everything on a single physical item, which might encompass multiple bibs.

e.g. suppose we have three pictures that have been mounted on the same board:

<img width="502" alt="Screenshot 2021-05-12 at 13 39 18" src="https://user-images.githubusercontent.com/301220/117976241-7603f780-b327-11eb-83b9-96c27ebd3280.png">

The three bibs each have their own iconographic number (in field 100), but link to the same item because all three pictures get requested together. For our reference number field, we should be using the more specific bib-level number.

## Questions

* Do we also put these numbers in the `"identifiers"` field?
* If so, what identifier type do we use?

**Comment by jtweed** [comment]
I'd say yes we do. We do for Calm references, which are also put in referenceNumber. For me, I see identifiers as the place for a complete set of disambiguated, machine-readable identifiers used for cross-referencing between systems.

Possibly `iconographic-number` as a starter for ten?

**Comment by alexwlchan** [comment]
> Possibly `iconographic-number` as a starter for ten?

Works for me. As part of this work, pull out the iconographic numbers from the Miro `wellcome-library-reference` identifiers as well?

**Comment by jtweed** [comment]
My only concern with that is that the Miro data can’t be updated, so what do when the ID is wrong?

I’m not saying we shouldn’t, but any icon number from Sierra should trump anything from Miro and we should be very careful about ever using this for linking.

Ie, we should treat everything in Miro as unreliable. Like how we never take a Sierra ID from Miro as the source of a link to Sierra, it always has to come the other way round.

I can’t remember, do we take the Sierra IDs from Miro and put them in as Sierra IDs? If so, what you suggest above would be consistent with that, which should be fine.

**Comment by alexwlchan** [comment]
> I’m not saying we shouldn’t, but any icon number from Sierra should trump anything from Miro and we should be very careful about ever using this for linking.

I have no plans to use the iconographic numbers for linking.

> I can’t remember, do we take the Sierra IDs from Miro and put them in as Sierra IDs? If so, what you suggest above would be consistent with that, which should be fine.

Yes, for example: https://api.wellcomecollection.org/catalogue/v2/works/y85dq7a2?include=identifiers

To be clear, the proposal is that we'd replace:

```json
{
  "identifierType": {
    "id": "miro-library-reference",
    "label": "Miro library reference",
    "type": "IdentifierType"
  },
  "value": "Iconographic Collection 580113i",
  "type": "Identifier"
}
```

with:

```json
{
  "identifierType": {
    "id": "iconographic-number",
    "label": "Iconographic number",
    "type": "IdentifierType"
  },
  "value": "580113i",
  "type": "Identifier"
}
```

We already put the identifier on the Work; my suggestion is that we'd just use the identifier type we're creating for this work.

**Comment by jtweed** [comment]
Sounds good 👍
