### ISSUE TITLE
Update licence data for Miro images

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5176]
## Problem

There are a number of Miro images that are known to have incorrect licences. This includes a large number of images which should have more permissive licenses, as well some that after analysis should be marked as in copyright.

With the increased prominence of images, the recent addition of licence filtering and to ensure we are meeting our obligations to rights holders, we need to find a way to update the licenses of the affected images. No additional images will be made available at this time.

## Proposed solution

- As the Miro data can't be updated, we need to find a way to overlay the updated licenses.
- However, we don't want/need the complexity of an entire additional data source and associated merging.
- Therefore, we should probably generate a static dataset that we use to update data as it is read by the adapter or transformer.

## Affected images

There is Word doc that provides an overview of two spreadsheets, each of which contains several lists of affected images. Together these can be used to generate a list of Miro IDs and the corresponding correct licence. Where the ID is a b number, the new licence applies to all Miro images that are related to that b number. These docs can't be made public for obvious reasons, but @aray-wellcome or I can send them to whoever picks this up.

**Comment by jtweed** [comment]
Link to subfeature: https://wellcomecollection.productboard.com/feature-board/planning/features/7344380

**Comment by alexwlchan** [comment]
These changes are applied and should be visible on wellcomecollection.org.

In addition, we have a much more robust set of tools for tracking any licenses we override in the Miro data, so it should be easier to apply any clean-ups or future changes to this data.
