### ISSUE TITLE
Support open ranges for journal production dates

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5178]
## Problem

Production date ranges for ongoing serial publications, eg journals, are listed with an end dated of 9999. These should be displayed as open ranges, with no value for the end date.

For example, Nature currently has the date range `1869-9999`. This should be displayed as `1869-`

## Examples

https://wellcomecollection.org/works/awa6c6gm
https://search.wellcomelibrary.org/iii/encore/record/C__Rb1310786

https://wellcomecollection.org/works/xw9py6w5
https://search.wellcomelibrary.org/iii/encore/record/C__Rb2506296

**Comment by alexwlchan** [comment]
This is done!
