### ISSUE TITLE
Assessing effects of downtime due to reindexing on users

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/platform#5191]
**What is the problem to solve?**
We think users are adversely affected by site downtime caused by reindexing

**What stage of research is it? (discovery/general usability testing/post release)**
general usability testing

**What are the objectives?**
To assess the extent to which users are affected and provide story when reporting on quarter.

**What are the assumptions?**
All users are affected similarly

**What research technique is required?**
GA, Kibana

**Comment by taceybadgerbrook** [comment]
@jamesgorrie @harrisonpim To assess the effect of the downtime during 19 and 20 May had on users (assuming behaviour would be similar for downtime on 10/6), I found no change in behaviour in GA. Specifically:
- no drop in numbers of sessions or page views when segmented by session duration
- distribution of types of mobile/device was unchanged
- % country unchanged
- overall average time on page and exit rate unchanged
- user numbers unchanged

I found some change in behaviour in Kibana:
- large numbers of hits hours before downtime on 19/5
- increased numbers of hits around the downtime

**Comment by taceybadgerbrook** [comment]
The graph below shows hits with red arrows marking the peak period of 3pm each day. The red oval marks the hours affected by the downtime of 8am and 9am. Updown says the downtime occured 10:40- 10:42 but Kibana reports hits during this period. The only break in timestamp appears at 08:58:00 - 08:59:30. 

![image](https://user-images.githubusercontent.com/32418070/122024045-feab0300-cdbf-11eb-93fe-573d9d2a485b.png)


The fact that Kibana wouldn't be able to report on attempted hits during downtime means that far from driving users away, users continued to hit the site after the downtime.

I could do further analysis but before I do, I wonder what would you do differently with the results?

**Comment by harrisonpim** [comment]
This is really good to know, Tacey, thanks for looking into it! 

That large block of traffic in the early hours of 19/05 stands out as odd to me - Is there anything noticeable about the type of traffic, or the things being searched for?

**Comment by taceybadgerbrook** [comment]
I agree, the activity in the early hours is strange. But then I thought, how could this make the site crash?

**Comment by harrisonpim** [comment]
Looking into this myself, it seems like one sessionId (`07686a15-9030-4370-8b9a-b80a357a159c`) is responsible for most of that unusual spike, searching for images of `anatomy` and opening every result they could find. Looks like they went all the way to the end of page 92...
