### ISSUE TITLE
Add 561 ind 1 to Sierra notes fields

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5199]
Sierra note field 561 `Ownership and Custodial History` should be added as an `Ownership note`.

**Important:** 561 should only be added when the 1st indicator is 1 (public note). It should NOT be added when the first indicator is 0 (private note).

**Comment by pollecuttn** [comment]
@alexwlchan can this be closed now?

**Comment by alexwlchan** [comment]
Done. 🥳
