### ISSUE TITLE
Get an instance of the storage_service running in the DAMS prototype account

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5206]
The goal here is to get a Terraform configuration in which somebody can run `terraform apply` and get a working instance of the storage service.

**Comment by alexwlchan** [comment]
Here's the first version of it, up and running:

<img width="1136" alt="Screenshot 2021-06-29 at 18 07 46" src="https://user-images.githubusercontent.com/301220/123847515-91928400-d90e-11eb-8a0c-be5e6627931d.png">

Rough edges I'd like to fix:

* We need to allow cross-account ECR access to our fluentbit and nginx images. These are static images published into private ECR repos, but I think we could move them into public repos.
* We need to allow cross-account ECR access to our storage service images. This is a bit harder – we'd need to get that working with weco-deploy – but it's not impossible, it just needs a bit more work.
* This service discovery toggle causes a massive faff when spinning up a new stack: https://github.com/wellcomecollection/terraform-aws-ecs-service/blob/master/modules/service/main.tf#L2-L6

    You get an error:

    > The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the for_each depends on.

    I'm pretty sure we do need service discovery (so the bag register can talk to the bags API); we should find a way not to hit this error when spinning up the module.
* I'm not sure the API Gateway deployment got created correctly.
* There are still some hard-coded "wellcomecollection" values – S3 buckets, I should search the state file to find the rest. They should all be expunged!

**Comment by kenoir** [comment]
+1 to also publishing the images to public repos. I think we'd want to publish to private then have another pipeline/build step managing publishing things to public ECR.

**Comment by alexwlchan** [comment]
> I think we'd want to publish to private then have another pipeline/build step managing publishing things to public ECR.

Why? Is there a reason not to publish directly to public ECR?

**Comment by alexwlchan** [comment]
I did wonder about rate limits, but I don't think it's possible for somebody to prevent us from pulling images by pulling heavily themselves (from the [ECR Public service quotas](https://docs.aws.amazon.com/AmazonECR/latest/public/public-service-quotas.html)):

> An authenticated image pull is one that includes an authentication token from Amazon ECR and are per account.

**Comment by kenoir** [comment]
> Why? Is there a reason not to publish directly to public ECR?

Even when pulling from within AWS there are stricter limits on how fast you can get images. We also want to keep an avenue to change our own services apart from those used by others.

**Comment by alexwlchan** [comment]
…okay yeah you can do 2000 BatchGetImage requests per second in ECS, okay 😅 

It occurs to me that might make it a bit easier – we don't need to add public ECR support in weco-deploy, just dual-publish them.

**Comment by alexwlchan** [comment]
Okay, so here's what's changed:

* All our images are now dual-published to ECR Public as well as ECR, and the DAMS prototype account is using them. 🎉 

* The hard-coded `wellcomecollection-` values in the working storage bucket names have been deleted. 🎉 

* We have a new issue with creating the stack from scratch: this line in our `secrets` module will only work if the secrets already exist: https://github.com/wellcomecollection/terraform-aws-ecs-service/blob/main/modules/secret_arns/main.tf#L29-L32

   If you're creating the secrets at the same time as the task, that doesn't work. I think we can fix this is we revert to the old behaviour when we're not looking up a specific key within a JSON secret.

* You get an error when you create the API Gateway the first time, which is annoying. I think it's https://github.com/hashicorp/terraform-provider-aws/issues/2918

* When you destroy the stack and recreate it, some of the secrets management goes wonky: because Terraform doesn't delete secrets, just schedules them for deletion.

**Comment by alexwlchan** [comment]
This is done.
