### ISSUE TITLE
Improvements to the item data based on design review 24 June

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5210]
* [x] Add a "note" field to the item model. We're not removing the note on the access condition, instead we're adding a new field.
* [x] Why can't we populate status and method all the time? e.g. by appointment => manual request (https://github.com/wellcomecollection/catalogue-pipeline/pull/1711)
* [ ] Do by appointment/donor permission always have terms associated?
* [ ] Consider adding terms that explain what's happening for all statuses
* [ ] Consider removing generic terms for a fixed status (e.g. a link to the access policy for restricted)
* [x] Distinguish between access terms/notes. e.g. "in copyright" = terms, "at digitisation/with a reader" = note
* [x] Use the copy number if there's no item title – "Copy 1", "Copy 2", "Copy 3", … (https://github.com/wellcomecollection/catalogue-pipeline/pull/1707)

**Comment by kenoir** [comment]
Part of: https://github.com/wellcomecollection/platform/issues/4643
