### ISSUE TITLE
Update catalogue-api thumbnails URL to use iiif.wc.org/thumbs

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5232]
Part of: https://github.com/wellcomecollection/platform/issues/5213

Currently thumbnail URLs in the catalogue-api are of the format:

https://dlcs.io/thumbs/wellcome/5/b1575215x_0001.jp2/full/!200,200/0/default.jpg

They should look at iiiif.wellcomecollection.org:

https://iiif.wellcomecollection.org/thumbs/b1575215x_0001.jp2/full/!200,200/0/default.jpg

**Comment by tomcrane** [comment]
The DDS uses this to pick the right asset to use for the thumbnail property of the IIIF Manifest or Collection; it parses out the identifier.

Updated to handle both old and new URL patterns:
https://github.com/wellcomecollection/iiif-builder/pull/172
