### ISSUE TITLE
Create list of annotations for conversion metrics

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#5248]

**Comment by taceybadgerbrook** [comment]
@jamesgorrie @harrisonpim  I've found [this listing that Natalie has been compiling](https://github.com/wellcomecollection/wellcomecollection.org/wiki/Key-events-or-changes-on-wc.org) of all the changes to the site. Maybe we could just add to this instead of creating something new?

**Comment by harrisonpim** [comment]
To me, those all look like changes to user-facing features... I think 'gaps in our reporting data' is a sufficiently different category of thing to make the maintenance of a separate list worthwhile

**Comment by taceybadgerbrook** [comment]
Ok, as long as the creation of the new list isn't a barrier to @jamesgorrie  pulling this all together. I'm thinking the last thing you need is extra work at this point.
