### ISSUE TITLE
Identity AWS Account Access Review

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5256]
Currently anybody with access to the Digital Platform AWS accounts has access to the identity account.

This account will eventually include:

- the requesting service (which makes holds in Sierra)
- the requesting reporter (which will involve user data, see https://github.com/wellcomecollection/platform/issues/5208)
- Sierra API credentials to look up patron information

This shouldn't be part of our default access – it should be a pre-approved list of devs working on requesting.

All developers should have access to the read_only and billing roles, but not developer or admin. (Note: the read-only role can't read secrets.)

**Comment by kenoir** [comment]
A reminder for anyone picking this up: Following this we should also be making sure that what ends up in CloudWatch logs in the Identity account is anonymised.

**Comment by alexwlchan** [comment]
> Following this we should also be making sure that what ends up in CloudWatch logs in the Identity account is anonymised.

Which is being tracked in https://github.com/wellcomecollection/platform/issues/5166

**Comment by kenoir** [comment]
Call it done for now!
