### ISSUE TITLE
Present a consistent title in the list of requests when an item appears on multiple works

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5268]
Sierra allows a single item to appear on multiple works – for example, multiple works or images that have been bound together.

We want to link to a work from the list of holds, to give context to requests. When an item appears on multiple works, we should be consistent about which work we link to.

Until we have a better way to choose works to link to, we should use the matching work with the lowest b-number. This is the oldest bib and probably the "parent" bib.

See also: #5267

**Comment by kenoir** [comment]
Closing as done.
