### ISSUE TITLE
What's up with the ECR images in uk.ac.wellcome/buildkite?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5277]
In last month's bill, we spent ~$300 in the Experience account on storing ECR images – for approximately 3TB of stored images.

My guess it's probably the uk.ac.wellcome/buildkite repository, which has over 6000 images going back to March: https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/130871440101/uk.ac.wellcome/buildkite?region=eu-west-1 It looks like we're pushing an image on every build.

Questions:

* What are these images for?
* Could we apply an ECR Repository Policy to purge all images, rather than keeping every image around forever? https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html

**Comment by kenoir** [comment]
These images are in-build caching for temporary images. They do not need to persist beyond the lifetime of a build (we may want to keep them around for a short time to enable re-running build jobs in buildkite).

We should apply an ECR lifecycle policy and cycle them away within ~ 7 days (a week is probably long enough to allow for wanting to re-run a build job).

I do not believe that we currently terraform the `uk.ac.wellcome/buildkite` repository (or at least I haven't found where we do). We should bring this into terraform here: https://github.com/wellcomecollection/platform-infrastructure/tree/main/builds/terraform and add the lifecycle policy.

**Comment by alexwlchan** [comment]
Note: you can find where this ECR repository is defined by clicking "Tags" in the sidebar.

<img width="1639" alt="Screenshot 2021-08-31 at 12 08 56" src="https://user-images.githubusercontent.com/301220/131492356-2936afe6-793d-4178-9357-4423bbf9d1d1.png">
