### ISSUE TITLE
Handle double-writing the *same* manifest in the storage service

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5287]
This is the cause of yesterday's failure: https://wellcome-ingest-inspector.glitch.me/ingests/35a445ac-4c36-438d-a01e-d4c44e44e7d9

As best I can tell, here's what happened:

- The bag register wrote the manifest `digitised/b17735270/v2`, but for some reason didn't delete the message from the SQS queue or mark the ingest as succeeded. We see the following log messages in the bag register:

	```
	14:46:18.942 INFO w.s.b.client.AkkaBagTrackerClient - CREATED for POST to /bags with digitised/b17735270/v2
	14:46:18.943 INFO w.s.b.client.AkkaBagTrackerClient - CREATED for POST to /bags with digitised/b17735798/v2
	14:46:18.960 INFO w.s.s.m.IngestStepWorker$$anon$1 - Successful: location=PrimaryS3ReplicaLocation(s3://wellcomecollection-storage/digitised/b1773521x/v2), space=digitised, externalIdentifier=b1773521x, version=v2, ingestId=fd5a6b1f-721c-42b1-8593-5acbc93e2b2b, duration=PT2.203149S, durationSeconds=2
	14:46:19.045 INFO w.s.s.m.IngestStepWorker$$anon$1 - Successful: location=PrimaryS3ReplicaLocation(s3://wellcomecollection-storage/digitised/b17735798/v2), space=digitised, externalIdentifier=b17735798, version=v2, ingestId=b0fa3bb0-da07-43f1-8167-3cdfd51a466d, duration=PT2.480333S, durationSeconds=2
    ```

    but then nothing else from that task. It was doing a lot of work, and the bag register metrics show spikes in CPU around this time:

    <img width="707" alt="Screenshot 2021-09-07 at 07 19 05" src="https://user-images.githubusercontent.com/301220/132294153-67b3d5e0-2c01-4566-9ea8-39d64b4ee7f5.png">

    I wonder if the task crashed?

- SQS waits for the queue visibility timeout, then makes the message visible again. The bag register picks it up, and discovers there's already a storage manifest with this version. It fails the bag.

Proposed changes:

- [x] Increase the CPU available to the bag register; currently it only has 0.5 vCPUs.
- [x] Improve the error logging from the storage libraries; seeing `java.lang.Error: null` is seriously unhelpful. You have to poke through a stack trace to find the actual error. (https://github.com/wellcomecollection/scala-libs/pull/138)
- [x] Support idempotent writes in `VersionedStore` (which is what the bag register uses). If I try to write the same object twice to the same version, that should be okay – writing _different_ objects is the issue. (https://github.com/wellcomecollection/scala-libs/pull/136)
- [x] Add a test that the bag register is idempotent.

**Comment by kenoir** [comment]
I think making idempotent writes acceptable is a good plan. 👍

**Comment by alexwlchan** [comment]
Done.
