### ISSUE TITLE
Always using the latest version of Elasticsearch for the pipeline cluster can break CCR

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5295]
We haven't had any updates since Tuesday night. What's up with that?

I applied a Terraform change to the pipeline stack on Tuesday night. This change triggered an inadvertent upgrade of the pipeline cluster from v7.14.0 to v7.14.1. You can see these changes in the [activity log for the pipeline cluster](https://cloud.elastic.co/deployments/29a51082b7e83a8121767edeffb08014/activity):

<img width="1344" alt="Screenshot 2021-09-09 at 09 30 54" src="https://user-images.githubusercontent.com/301220/132651563-ce1e76cc-0d04-4a1a-8f5d-d2b957686340.png">

This is because we always pick the latest available version of Elasticsearch: https://github.com/wellcomecollection/catalogue-pipeline/blob/main/pipeline/terraform/stack/elastic_pipeline.tf#L17

The API cluster is still at v7.14.0. It reports that CCR is all fine, but this is [definitely not the case](https://www.elastic.co/guide/en/elasticsearch/reference/current/xpack-ccr.html):

> the cluster containing follower indices must be running the same or newer version of Elasticsearch as the remote cluster

My change inadvertently broke this rule, so CCR stopped working.

Suggested changes:

- [ ] Upgrade the catalogue-api cluster to v7.14.1 and hope that CCR resumes. If not, we'll need to reindex.
- [ ] Sort out the pipeline Terraform so it doesn't produce ridiculous diffs, and changes like this can be caught at plan time
- [ ] Don't automatically pick the latest Elasticsearch version
- [ ] Double the number of nodes in the pipeline cluster

**Comment by jamesgorrie** [comment]
Some notes as we have seen versioning challenges previously.
[Here is there policy](https://www.elastic.co/guide/en/cloud/current/ec-version-policy.html#ec-version-policy-available).

Given that, I feel we should make sure we have a way of staying up to date, as the more versions you need to update, the harder it is to tell if something is breaking.

Could we somehow couple the leader & follower in terms of provisioning and link the versions?

Are we certain that we don't have CCR issues as we should have alerts on CCR failing.
![Screenshot 2021-09-09 at 09 47 41](https://user-images.githubusercontent.com/31692/132654163-902fc5a6-ccf9-4932-afa1-e5ce57e6b027.png) - I'd like to look into why they haven't triggered.

[Annoyingly the logging cluster stack monitoring](https://logging.wellcomecollection.org/app/monitoring) is giving us 2 `catalogue-api` clusters, I'd also like to dig into why this is the case as we've seen it previously.
![Screenshot 2021-09-09 at 09 48 52](https://user-images.githubusercontent.com/31692/132654456-22d9553d-bd45-4c1b-9817-edba368da4e9.png)

**Comment by alexwlchan** [comment]
> I feel we should make sure we have a way of staying up to date, as the more versions you need to update, the harder it is to tell if something is breaking.
>
> Could we somehow couple the leader & follower in terms of provisioning and link the versions?

Yeah, I was thinking maybe we export the version from the catalogue-api Terraform, then load that in the pipeline Terraform.

If Elasticsearch tells you it can't deploy that version any more, you know you have to update the API cluster first or pin an older version, rather than jumping straight to latest.

> Are we certain that we don't have CCR issues as we should have alerts on CCR failing

I'm reasonably certain we do have CCR issues because the replication between the pipeline and API clusters has stopped, I just can't find where Elastic Cloud is telling us this.

**Comment by jamesgorrie** [comment]
> It reports that CCR is all fine

Made me think that we don't have CCR issues - there's definitely a problem with observability of CCR stuff between pipeline and API that needs sorting.

**Comment by alexwlchan** [comment]
> there's definitely a problem with observability of CCR stuff between pipeline and API that needs sorting

TBH I am tempted to eschew Elastic alerting for this entirely because it seems a bit dodgy, and measure the _effect_ of CCR instead.

Query the works index in the pipeline cluster and the API cluster, sorting by indexedTime and taking the max value. If they differ by more than ten minutes, something has gone bang.
