### ISSUE TITLE
The items API isn't returning notes on access conditions

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5305]
e.g. https://wellcomecollection.org/works/bgxhrvjr

The catalogue API includes an access note, but the items API doesn't, so the effect is that the note disappears momentarily after loading the page. 

It appears this issue was caused by the sierra-libs requesting insufficient fields from Sierra when retrieving items. 

The fix will require:
- [x] Update to scala-libs to request the correct fields from Sierra (https://github.com/wellcomecollection/scala-libs/pull/145)
- [x] Use the latest version of scala-libs (https://github.com/wellcomecollection/catalogue-api/pull/278)

**Comment by kenoir** [comment]
This has been deployed to production, I can see that the notes field is now available.

<img width="1101" alt="Screenshot 2021-09-16 at 15 27 55" src="https://user-images.githubusercontent.com/953792/133630397-8cd806f9-034f-456e-a4e0-b06d8bbb2e9e.png">
