### ISSUE TITLE
One neat trick to make our builds run twice as fast

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5317]
Currently our Scala build pipelines go something like:

- run autoformat, wait
- build libraries, wait
- build apps

This is a holdover from when we built things in Travis and we had limited concurrency. Running builds we knew would fail was really bad – it wasted a worker and pushed other builds back.

Now we run in Buildkite with our own instances, we're no longer limited by concurrency. What if we built libraries and apps at the same time (once we knew autoformatting was okay)?

Pros:

* Slice build times in half, less time waiting for builds and deployments. Currently the minimum build time is $(max library build time) + $(max app build time), depending on how jobs are assigned. Now the minimum would be $(max library/app build times).

Cons:

* Potentially more expensive – we'd be running jobs we might already know couldn't possibly succeed, because an earlier job had failed. (Although you can configure [fast fail for Buildkite](https://buildkite.com/blog/fail-fast).) Our current Buildkite instance bill is ~$75/mo, so not exorbitant.

What do other devs think of this?

**Comment by jamieparkinson** [comment]
I would be pro- this, it's not as expensive as all of us sitting around twiddling our thumbs waiting for builds to pass...

**Comment by jamesgorrie** [comment]
@alexwlchan we could use a plugin like [this](https://github.com/uber-workflow/bail-early-buildkite-plugin) to avoid using resource when we know it's going to fail?

**Comment by alexwlchan** [comment]
> we could use a plugin like this to avoid using resource when we know it's going to fail?

Yup, although I'd prefer an approach that doesn't require us to annotate every build pipeline.

Although tbh the Buildkite bill is sufficiently small right now I don't care much about cost reduction measures.

**Comment by alexwlchan** [comment]
Done!
