### ISSUE TITLE
Consider mapping request statuses to controlled list

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5328]
### What

We should look at mapping the Sierra hold statuses to a controlled list that better matches the language we use on the site for requesting.

As a first step we need to see what statuses are in use. Then we can look at whether it would be possible to map them, or whether we should talk to LE&E/CI about changing the labels in Sierra and continue to pass them through directly.

UX should be across the language here too to make it makes sense to users and is consistent with the rest of the site.

### Examples

* `on hold.` should probably be something like `Requested`
* `item hold ready for pickup.` should probably be more like `Ready for pickup`

### Where

These are used on the account page, in the item requests table.

**Comment by alexwlchan** [comment]
Yeah, we're doing this in the front end.
