### ISSUE TITLE
Ensure deliverability of Auth0 emails

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5334]
### Background

We use Amazon SES to send emails from Auth0. Before putting sign in and requesting live, we need to make sure that everything is configured to ensure the maximum deliverability of account-related emails.

### Approach

There are four parts to this:

* [x] Check we have requested SES production access
   * https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html
* [x] Check that we're happy with the Auth0/SES integration
    * https://auth0.com/docs/brand-and-customize/email/smtp-email-providers/configure-amazon-ses-as-external-smtp-email-provider
* [x] Modify the SPF record for the wellcomecollection.org DNS to include SES
  * https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-authentication-spf.html
* [x] Set up DKIM authentication to prove SES can send emails from the Library Enquiries email address
  * https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-authentication-dkim.html

**Comment by alexwlchan** [comment]
There's also some discussion here: https://wellcome.slack.com/archives/C3TQSF63C/p1648730771823929
