### ISSUE TITLE
Handover 

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/platform#5346]
## Runthroughs 
- [x] the frontend (@alexwlchan , @wellcomecollection/js-ts-reviewers) saying complete in favour of smaller bits of it
- [ ]  [conversion analytics](https://github.com/wellcomecollection/reporting/tree/main/conversion_analytics), including [Segment](https://segment.com/) (@harrisonpim, @taceybadgerbrook) - will talk to @jamieparkinson about this
- [x]  [rank](https://github.com/wellcomecollection/catalogue-api/tree/main/rank) (@harrisonpim) worked through this on the team and others are now owrking on it
- [ ]  [toggles](https://github.com/wellcomecollection/wellcomecollection.org/tree/main/toggles) walked through toggles and added [some functionality and docs](https://github.com/wellcomecollection/wellcomecollection.org/pull/7238) reflecting how they should work
- [ ]  Prismic (@cbowskill, editorial team). In progress
- [x]  Redirects (this might or might not fall to me dependant on the Prismic work)
- [x] `partOf` - shared how this works across Prismic and created [a document](https://www.notion.so/wellcometrust/Prismic-relationships-3f21e5bf9634437088c3af7289537772) explaining it
- [x] ~Google Tag Manager~ I personally have never seen what tag manager gives us that a programmatic approach in GA would do better, but this could because I might not understand the issues we are having with GA.
- [x] ~annotation list for conversion metrics~ It's a suggested feature so nothing to handover. We only got so far as talking about it. There is some literature [here](https://www.elastic.co/blog/time-series-annotations-and-anomalies-with-kibana)

## General details
* Updown creds
* Auth0

**Comment by jamesgorrie** [comment]
@taceybadgerbrook I have updated the list to reflect those things, but not much I can add in terms of GTM and annotations.

@jamieparkinson I'll set some time aside to run you through the Segment pipeline.

**Comment by taceybadgerbrook** [comment]
Re GTM it was only to know whether we had disconnected this entirely from wellcomecollection.org.
