### ISSUE TITLE
Is there a better way to handle inter-library loans?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5354]
Sierra creates virtual records for inter-library loans, which are identified in a different way to regular Sierra items – they get a six-digit transaction number, followed by the ILL department code, e.g. `101339@illd`.

These aren't regular Sierra items and so we shouldn't display them in the list of user holds on wc.org/account.

For now I'm just going to hide them – it'll be as if they don't exist – but displaying inter-library loans on wc.org/account is out there as a possible future enhancement for staff users in the future…

See https://documentation.iii.com/sierrahelp/Default.htm#sgcir/sgcir_ill_virtualrecs.html

**Comment by kenoir** [comment]
Closing as in-need-of-product-motivation.
