### ISSUE TITLE
Include punctuation from 245 subfield $h

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5362]
We don't want to include the full contents of $h (it's a legacy field), but we would like to include any punctuation at the end.

See this Slack thread for context: https://wellcome.slack.com/archives/C8X9YKM5X/p1636454727037400

**Comment by pollecuttn** [comment]
Nic: "the punctuation belongs to the subfield in front (so : before |b rather than any relation to |h. It's just [format] in that subfield that we don't want to surface, i.e.:
Ethics & medicine|h[electronic resource] :|ba Christian perspective on issues in bioethics."

**Comment by pollecuttn** [comment]
@alexwlchan Can this be closed now? It looks like the record https://wellcomecollection.org/works/kgrnmm9m is updated "Ethics & medicine : a Christian perspective on issues in bioethics." although the PR above is still open?

**Comment by alexwlchan** [comment]
@pollecuttn No, I found an issue with the rule – we need to omit punctuation if it's the last thing, e.g. the trailing period on https://wellcomecollection.org/works/kf8mzy3p. That's fixed by the PR above, which is awaiting review.

**Comment by pollecuttn** [comment]
@alexwlchan After today's reindex I can see that the trailing full stop has gone from https://wellcomecollection.org/works/kf8mzy3p.

Can this be closed now?

**Comment by alexwlchan** [comment]
Yes!
