### ISSUE TITLE
Decide how to handle TEI contributors with no type=original

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5380]
For https://github.com/wellcomecollection/platform/issues/5118

Here's an error we're getting from a lot of the Arabic manuscripts:

```
Unable to transform /Users/alexwlchan/repos/wellcome-collection-tei/Arabic/WMS_Arabic_498.xml:
java.lang.RuntimeException: No persName nodes with type=original in author

<author key="person_f6247" xmlns="http://www.tei-c.org/ns/1.0">
  <persName xml:lang="ar-Latn-x-lc">ʿAlī ibn  al-Sayyid ʿAbd Allāh</persName>               
  <persName facs="#i0002" xml:lang="ar">الاستاذ السيد الشيخ على ابن السيد عبد الله</persName>
</author>
```

We have the original Arabic name and the Latinisation. We could come up with a heuristic for deciding (I'm thinking probably the non-Latinised version?) and put that in the pipeline.

I wonder if there's a way to put both names on the contributor and get the human-written Latinisation.

**Comment by paul-butcher** [comment]
Looking at https://github.com/wellcomecollection/wellcome-collection-tei/blob/e5e34c9247b506a7ce027fe02ee2ba4fd7f0c484/Arabic/WMS_Arabic_24.xml#L47-L49, which has this same issue.

Within that msItem, there is a textLang element with @mainLang="ar"

https://github.com/wellcomecollection/wellcome-collection-tei/blob/e5e34c9247b506a7ce027fe02ee2ba4fd7f0c484/Arabic/WMS_Arabic_24.xml#L224

Perhaps that can be the key - the "original" persName is (cascading):
* The only one
* The one with @type="original"
* The one with a matching xml:lang to the mainLang of the msItem

If we are really desperate, then maybe 
* The first in document order.

But I don't like that last one.  I'd rather see if it can be dealt with at source.

**Comment by paul-butcher** [comment]
In the current model, I don't think there is a sensible way to add multiple names to a Contributor.  A Contributor consists of the contributing Agent (who has one name) and their roles.

Were we to change the model to accommodate different renditions of names, then, for completeness, we would add a list of alternative names to an agent.  Alternative names could then be also each be given their own purpose.

e.g. This chap: https://en.wikipedia.org/wiki/Hafez has four renditions of his name on his Wikipedia page, 

1. his full name, transliterated
2. his full name, original script
3. his pen name, transliterated
4. his pen name, original script

**Comment by alexwlchan** [comment]
Have we talked to anybody who works on TEI about this? I realise I jumped in with a suggestion for how we should handle this in the original ticket, but I don't think I'd checked with them, sorry.

**Comment by paul-butcher** [comment]
It looks like these are in error.  https://wellcome.slack.com/archives/CS4G8SAG3/p1655111331727969 Lara and Stephanie are adding in type="original" where needed.
