### ISSUE TITLE
Determine how we'd add auth in front of Loris

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#539]

**Comment by alexwlchan** [comment]
Possibly useful: https://github.com/loris-imageserver/loris/pull/316

**Comment by jtweed** [comment]
Thanks, that's really great to see that IIIF Auth is almost implemented in Loris. We should definitely all take a good read of http://iiif.io/api/auth/1.0/ as part of this investigation.

So my question then is really how we do IIIF Auth in combination with Cloudfront?

When we log in a user, we can set the cookies needed for Cloudfront, so if the image is cached, it'll get returned.

But what if it's not in Cloudfront and it has to go back to Loris? How does Cloudfront tell Loris that the user is logged in?

Can we get Cloudfront to pass on the IIIF auth cookie or token to Loris if it's in the request to verify access? Is that even what we should do?

**Comment by azaroth42** [comment]
@jtweed We will have the same question in a few months. If you solve it, please let me know! And if you don't, I'm sure that our almost-in-position AWS Cloud Architect will look forwards to helping.

**Comment by jtweed** [comment]
@azaroth42 Will do. We're going to whiteboard something here, then will put it in the ticket. We're not planning on doing anything with this for a few months (all the initial images are CC licensed), just wanting to make sure we're not painting ourselves into a corner with a potential move from DLCS to Loris+Cloudfront.

**Comment by alexwlchan** [comment]
Closed by https://github.com/wellcomecollection/platform/issues/4884
