### ISSUE TITLE
pass rank tests based on total score, not known failures

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/platform#5392]
At the moment, our suite of search relevance tests passes because we failures are marked as 'known failures'; tests which we know don't pass with the current query. 

Rank outputs a relevance score for each test, and was conceived with the idea that the suite would pass above a threshold on the total score. 

We should use that score to pass rank instead of the known failures, based on the candidate query's score being greater than or equal to the production query (and/or another threshold).

**Comment by alexwlchan** [comment]
I watched a talk from the Buildkite conference ["The future of CI/CD"](https://youtu.be/v6SmFZbUkug) which talked about moving past simple pass/fail; I wonder if tracking a metric is something they've considered.
