### ISSUE TITLE
Github/Gitbook sync needs re-synced

### ISSUE THREAD

**Issue by aray-wellcome** [wellcomecollection/platform#5393]
Wellcome Collection's Gitbook has sections for both Collections and Production. At some point last year, James Gorrie said he set up this Gitbook to back up both sections to our Github. Due to an update on Gitbook, the connection seems to have been severed. 

When Alexandra  tries to sync the Transcribe Wellcome section, she gets the following error messages though it should be syncing to https://github.com/wellcomecollection/transcribe-wellcome:
•	‘Your Git synchronization is based on an older version of GitBook. You content is still synchronized, but we recommend that you upgrade to the new version for a better experience.’
•	‘The latest synchronization failed with “Unexpected error”. Please try again or contact support for assistance.’

The other sections, I am not sure what repositories they should be backing up to on our Github. Can anyone else tell where these sections are backing up to? And if not, can we get a new sync started?

Collections Information is at https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/c/-MYnYZnJiMrmVjHaC8bE
Digital Production is at https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/c/-MYdLJdqh8cpl-15s6bk
Photography (which is empty at the moment) is at https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/c/AnB4rMyCOInu4ewe0uCU 

Additionally, Alexandra pointed out that it seems part of her spaces under Collections Information seem to have split from themselves, into main and 1.0.0, for example. Did this article get forked somehow? Is there a way to merge it back together?
![image](https://user-images.githubusercontent.com/49983203/148073673-d6d50be3-e193-4d2b-812b-d5e9f53a9700.png)

**Comment by alexwlchan** [comment]
How do you grant access to those Gitbooks? I can't seem to view them.

**Comment by aray-wellcome** [comment]
Sent you an invite to be an admin but since the Gitbook update the permissions on user accounts are so messy. Let me know if you can't access something after that and I'll try to fix it.

**Comment by alexwlchan** [comment]
Think I've got it; how do you trigger a sync?

**Comment by aray-wellcome** [comment]
If you go to the Transcribe Wellcome section, there will be a three dot hot dog menu in the top right next to the Edit button. Synching with Git is on that menu. That's where you will find the error messages Alexandra saw. I think Transcribe Wellcome was on Github first then moved to Gitbook so that's why the sync is in place. 

If you go to any other section, like mine which is Digital Workflow Documents and click the sync with Github, it looks like it's not hooked up to Github at all. So I don't know if James never actually synced it to Github or if it's just come undone.

**Comment by alexwlchan** [comment]
It looks like I have to completely reconfigure the sync – I wonder if this was originally connected through James’s personal account?

Which is the most up-to-date version currently? Is the GitHub or the Gitbook version canonical?

<img width="588" alt="Screenshot 2022-01-05 at 10 37 55" src="https://user-images.githubusercontent.com/301220/148203856-7928ecbf-f82b-405e-85bd-bb789818cdfc.png">

**Comment by aray-wellcome** [comment]
It could've been! The Gitbook version is canonical for everything.

**Comment by alexwlchan** [comment]
> The Gitbook version is canonical for everything.

Okay, well I've kicked off a synchronisation. I also have a local copy of the GitHub repo, so 🤞

**Comment by alexwlchan** [comment]
Okay, I think it's working. I've done an initial sync – can you try it to see if the transcribe-wellcome sync is working for you now?

**Comment by aray-wellcome** [comment]
If I go to Transcribe Wellcome's sync button, it tells me it's syncrhonizedand has a check mark saying it'll keep everything in sync. I compared the file it said it updated in Github with what's in Gitbook and all seems well!

**Comment by alexwlchan** [comment]
Woohoo! Happy to close this then?

**Comment by aray-wellcome** [comment]
Transcribe Wellcome's sync is fixed so happy to close this ticket. But I was under the assumption from James' work that our entire Gitbook was being backed up to Github and it doesn't seem to be the case now. Perhaps we could put another ticket on the backburner to get this all backed up to Github at some point?

**Comment by alexwlchan** [comment]
> Perhaps we could put another ticket on the backburner to get this all backed up to Github at some point?

I might as well sort it all out while I'm here. Let's go see if any of the other content is being backed up somewhere.

**Comment by aray-wellcome** [comment]
I'm good with it if you're up for it! I dug around in my old convo with James on Slack and he said Dig Prod's stuff should be here https://github.com/wellcomecollection/digital-production-docs-glossary but that's defunct

**Comment by alexwlchan** [comment]
Okay, this has fallen off my list, so going to keep this ticket around to backfill the backups.

**Comment by aray-wellcome** [comment]
I've just had a meeting with CI about Gitbook today and we have some more Gitbook/Github sync issues that we need sorted before CI can start using it to put all their documentation on. 

Collections needs a repository on Gitbook so they can consolidate and move everything around where they need it. Some things have been duplicated and put in the wrong spots, possibly due to a prior sync that no longer exists. Would it be better for them to erase what they don't need and move things before or after the sync? 

Additionally, the syncs we do have for TEI and Visual Material both have a warning message on them and need updated. They both give us this message but I don't think we have the power in Github to make the sync update:
![image](https://user-images.githubusercontent.com/49983203/159018724-7c70df0d-12ce-49b6-8357-9fcd4e7eda6a.png)

I think this is one of those tickets that might benefit from a quick in person meeting with me, you, and maybe Toni and Adrian because pointing out what needs done in person is so much easier than trying to write it.

**Comment by aray-wellcome** [comment]
As per Toni:

> > In terms of what we want to sync with what:
> •	[https://github.com/wellcomecollection/collections-information](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwellcomecollection%2Fcollections-information&data=04%7C01%7CA.Ray%40wellcome.org%7C6e9483be6fb84958a1c908da08ed8a86%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637832113578061268%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w%2BsKG1vAtD%2F2UJHjA0x3k6zVV9ynHSPPZFEcE2sBu9k%3D&reserved=0) should be synced to all spaces within Collections Information [https://app.gitbook.com/c/-MaCyZe0q1CUexeaRgr6](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.gitbook.com%2Fc%2F-MaCyZe0q1CUexeaRgr6&data=04%7C01%7CA.Ray%40wellcome.org%7C6e9483be6fb84958a1c908da08ed8a86%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637832113578061268%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Moe7leEIWlqLU1sjJ5lEJgIKv9Y5VQ9YSpjtp%2F7%2BtI4%3D&reserved=0)
> •	[https://github.com/wellcomecollection/collections-information-inventory](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwellcomecollection%2Fcollections-information-inventory&data=04%7C01%7CA.Ray%40wellcome.org%7C6e9483be6fb84958a1c908da08ed8a86%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637832113578218257%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e4Q8c2i5Q9qgDZJl%2BAVAnLpmmwP5OqI7YaEqIz7iAdY%3D&reserved=0) should be synced to all spaces within Collections Information Inventory [https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/c/-Mgjvi2MWgBW-bCdzb4u](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.gitbook.com%2Fo%2F-LumfFcEMKx4gYXKAZTQ%2Fc%2F-Mgjvi2MWgBW-bCdzb4u&data=04%7C01%7CA.Ray%40wellcome.org%7C6e9483be6fb84958a1c908da08ed8a86%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C637832113578218257%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kmgS8SZmMNuDDbcLmFstZAsixAGf%2BMIyKGsNHXSZZnM%3D&reserved=0)




Toni and I also don't have access to the inventory repository on Github, we get a 404.

**Comment by aray-wellcome** [comment]
Couldn't use one repo to sync multiple spaces so created new repositories for all spaces. Still need to fix Programme Information as it wasn't syncing correctly.

**Comment by aray-wellcome** [comment]
We will also need to add the users to the private repos on Github so they can see that their content is successfully being backed up on Github.

**Comment by alexwlchan** [comment]
> Still need to fix Programme Information as it wasn't syncing correctly.

I deleted the repo, created a new repo, and reconfigured the sync, and now it's working. 🤷‍♀️ 

> We will also need to add the users to the private repos on Github so they can see that their content is successfully being backed up on Github.

Yup, done.

Is there anything else we need to do here, or can we close this?
