### ISSUE TITLE
Create a list of "interesting" works

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5394]
See also: https://github.com/wellcomecollection/platform/issues/5312

We should create a list of works that are "interesting" from the pipeline point-of-view, for example:

* A work from each of the different sources
* Different merging combinations
* Works with different combinations of source fields populated

This could go into the diff tool used by the API, or maybe be documented somewhere else.

**Comment by kenoir** [comment]
Closing as context lost.
