### ISSUE TITLE
Render items on exhibition properly in the item status on wc.org

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5401]
When an item is on exhibition, there's information in the catalogue record to tell readers where the item is on exhibition, and when it's likely to be returned. We don't expose this information in the API or on the website, but we should.

e.g. https://wellcomecollection.org/works/gzgzm2sf

Compare the new site:

<img width="1209" alt="Screenshot 2022-01-14 at 11 38 02" src="https://user-images.githubusercontent.com/301220/149509579-6af0dbb4-e7fb-45a2-a0eb-9e857353519b.png">

To the old site:

<img width="814" alt="Screenshot 2022-01-14 at 11 38 19" src="https://user-images.githubusercontent.com/301220/149509614-2f3b0017-8b1f-4c08-9b30-abbaa68c8395.png">

**Comment by paul-butcher** [comment]
Oh yes, matching the "On Exhibition" Location

varFields is a List, so we'd have to filter the list for fields with tag 'r' (rather than copy the same techniques used for fixedFields)

https://github.com/wellcomecollection/scala-libs/blob/main/sierra/src/main/scala/weco/sierra/models/data/SierraItemData.scala

**Comment by alexwlchan** [comment]
Yup.

We have some helpers for filtering var fields that you might find useful: https://github.com/wellcomecollection/scala-libs/blob/ec821ac48edcf9bdd653473ffc5c1e8673fdf950/sierra/src/main/scala/weco/sierra/models/SierraQueryOps.scala#L74-L82

(If you haven't come across it already: var/fixedfields are short for "variable-length fields" and "fixed-length fields", respectively. It's part of the MARC design that's very space-efficient.)

**Comment by paul-butcher** [comment]
When there are multiple 'r' fields, how should they end up? 
It seems like the wrong place to fully format something like an HTML UL, but the output field is a string, so there isn't much choice - either format it up here, or leave it as just a text list.

**Comment by alexwlchan** [comment]
> When there are multiple 'r' fields, how should they end up?

Good question!

Maybe join them with an HTML line break? The front-end will render whatever HTML we put in here, because the Catalogue pipeline/API is a trusted source (in turn because Sierra/our source systems are trusted).

**Comment by paul-butcher** [comment]
Yes, I think that's right in the context of this ticket.

We can look at improving the layout in the future, but this ticket is simply a matter of getting the information out of the source database in whatever way makes sense. 

Without being able to see and refine the eventual styling, I'd be reluctant to do something like a UL that could cause weird formatting errors.

**Comment by paul-butcher** [comment]
Looking at the example, there are two 'r' fields.  It looks like the first one is irrelevant - it's from a long time ago, and it's for the Reading Room.

I suspect that the correct thing, therefore, is to only return the last reservation.  Can we rely on the order being meaningful?

```
    {
      "fieldTag": "r",
      "content": "02-04-15 ON RESERVE FOR Reading Room"
    },
    {
      "fieldTag": "r",
      "content": "27-09-21 ON RESERVE FOR Diseases: Curse of the past, threat to the future, Roemer- und Pelizaeus-Museum, Hildesheim, Germany, 1 October 2021 - 5 June 20"
    },
```

**Comment by alexwlchan** [comment]
Hmm. I don't know if that's true in the general case. (We do have tools for exploring the Sierra data in bulk, which I can show you if it'd be useful.)

In this case I'd err on displaying both of them – it's more confusing to staff if we only display _some_ of the record, because the rule may not be obvious to them. If there's a data quality issue we ask somebody in Collections & Research to correct the underlying record rather than working around it in our code.

**Comment by alexwlchan** [comment]
> what should happen in the absence of such a note - should it fall through to the "cannot be requested online" message, or should the note field be left blank?

Fall through to the default message; I think it's more useful than leaving an empty note.

**Comment by paul-butcher** [comment]
Given the further requirement to filter out the ON/OFF RESERVE and CIRCED information, I notice that this could theoretically cause the output to have two identical lines, e.g.

```
2022-01-31 ON RESERVE FOR some exhibition
2022-02-01 OFF RESERVE FOR some exhibition CIRCED 2 TIMES
```
would become 
```
some exhibition
some exhibition
```

Obviously, if it is off reserve, then it will not be on exhibition, so this branch won't be triggered.

However, I was concerned about things being exhibited multiple times. e.g.

```
2022-01-31 ON RESERVE FOR some exhibition
2022-02-01 OFF RESERVE FOR some exhibition CIRCED 2 TIMES
2022-01-31 ON RESERVE FOR some other exhibition
```

I have had a bit of a browse through the data for records with CIRCED (N>1) TIMEs, but in the ones I saw, I only discovered one each of ON and OFF reserve, implying that the upstream system replaces on and off reserve entries, rather than appends them.

However, I did discover at least one item that could suffer this problem in real life: 

item 1704412 is marked as On Exhibition, and has both an ON and OFF RESERVE entry.  This means that it would get an access condition note that looks like this

```
Beauty and Belief: Crossing Bridges with the Arts of Islamic Culture. Brigham Young University, Provo. 24 February 2012 - 29 Sep.
Beauty and Belief: Crossing Bridges with the Arts of Islamic Culture. Brigham Young University, Provo. 24 February 2012 - 29 Sep. 
```
I suspect that this is a data quality problem. It appears to have come off reserve in 2013, and it is has status.display: AVAILABLE, so it is probably caught by a case higher up in the match (not looked yet).

**Comment by paul-butcher** [comment]
Actually, 2 out of 2 records I have just looked at are ON EXHIBITION with both ON and OFF RESERVE (1665446 looks like dummy data)

**Comment by alexwlchan** [comment]
Yeah, so the data in the reporting cluster is imperfect in this regard – Sierra records can be suppressed (all the data is populated, but not available publicly) or deleted (gone forever).

Currently there's no way to tell if a record is suppressed from the varFields index – you need to look in the sierra_bibs index. That's how you can tell if it really is placeholder data.

**Comment by paul-butcher** [comment]
It's live now. 

<img width="1300" alt="Screenshot 2022-02-03 at 14 55 28" src="https://user-images.githubusercontent.com/64621/152367418-6044557c-3928-45eb-ab88-69621fb5e04e.png">

I think we may wish to revisit this logic at some point in the future after we have seen it in action in a few records (and consulted with C&R). The implementation matches the behaviour of the old site, but I suspect that the reserves notes may be a partial historical record in chronological order, and anything other than the last note is probably not very informative for an end user (and may be misleading - in the case of gzgzm2sf, there is an implication that it is both in the Reading Room and in Germany). That said, it may simply be something to be handled in the source data.
