### ISSUE TITLE
Library linking entries and series relationships

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5408]
## Objective

Improve the collections search journey

## Measures

- Support for linking entries and series relationships

- Increased usage of library series for browse

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4915019

**Comment by paul-butcher** [comment]
RFC (and PR with illuminating commentary) relating to how (some of?) this is to be modelled:

https://github.com/wellcomecollection/docs/blob/sierra-series/rfcs/044-sierra-series/README.md  https://github.com/wellcomecollection/docs/pull/53

I believe there is also a front-end aspect to this, however, until I know a bit more about it, I'm not sure:

- Ensure that a large series does not result in an unusable hierarchy of links
- Make name-only relationships produce links.

I'll be raising some sub-tickets this afternoon to cover various aspects of the implementation of the RFC.
