### ISSUE TITLE
More flexible location filtering

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5410]
## Background

One of the aims of the new site was to make it clearer which items were digitised, to help stop people from making unnecessary trips to the library for items they could have viewed online. As part of this, we made location filtering as simple as possible and cut it down to two clearly visible options: online and in the library.

<p></p>

Feedback has shown this to be a simplification too far, for both the online and in library use cases. Online results contain both digitised items from the collections and external resources, when users are often only looking for the former. In the library, day visitors want to find only things that are on the open shelves yet have to wade through items that need to be requested.

<p></p>

We should remove the online/in the library filter and replace it with a location filter that presents all four options: available online, databases and resources, open shelves, closed stores.

## User stories

As a library day visitor  
I want to be able to find things on open shelves  
So that I know they are things I can access straight away

<p></p>

As library desk staff  
I want to be able to find things on open shelves  
So that I can help visitors find things that don't need to be requested

<p></p>

As a member of staff  
I want to filter out third party resources  
So that I can find digitised copies of physical things in the collections

## Acceptance criteria

- Items in all locations are returned by default

- Users can restrict search results to only items on open shelves

- Users can restrict search results to only items in closed stores

- Users can restrict search results to only digitised items in the collections

- We have explored and confirmed the best and most understandable terminology for available online and databases/subscriptions/external resources.

## Measures

- Searches using location filter

- Values for location filter

- Search conversion

## Objective

Decommission search.wellcomecollection.org

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/10445278

**Comment by taceybadgerbrook** [comment]
Measuring success is going to depend largely on LED staff feedback. If someone successfully searches for something on the open shelves, we won't know whether they have found what they were looking for until they ask at the enquiries desk. 

Measuring the success of the filter for collection items available online would have to depend on how often the filter is used. I've found that serious researchers don't as a rule download material.
