### ISSUE TITLE
Automate index expiry in the logging cluster

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5429]
Currently we keep application logs in the logging cluster (logging.wellcomecollection.org) until the disk fills up, and then we go clear out the indexes by hand.

This is inefficient – we should keep logs on a rolling buffer that's automatically pruned (say, last 30 days) rather than cleaning them up by hand.

**Comment by alexwlchan** [comment]
So apparently this is already configured, but it's not working for some reason:

<img width="895" alt="Screenshot 2022-03-11 at 13 24 26" src="https://user-images.githubusercontent.com/301220/157876078-554c498d-0ef2-4ec1-a393-3a3bc1b67702.png">

🤔

**Comment by alexwlchan** [comment]
Okay, so looking for templates:

```
GET _cat/templates/firelens*
```

I found a template called `firelens-*` which was empty.

```http
GET _template/firelens-*
{ }
```

I created a new template:

```http
PUT _template/firelens
{
    "order" : 2,
    "index_patterns" : [
      "firelens-*"
    ],
    "settings" : {
      "index" : {
        "lifecycle" : {
          "name" : "expire_after_7_days",
          "rollover_alias" : "firelens"
        }
      }
    },
    "mappings" : { },
    "aliases" : { }
}
```

It seems to have cleared up the warnings, but just to be on the safe side I'll also delete some indices before I finish today.

**Comment by alexwlchan** [comment]
Checking today, indexes aren't being deleted and the error is recurring. I'll dig into this more today.

**Comment by alexwlchan** [comment]
I deleted all the indexes to the beginning of March, which kicks this down the road but will at least stop it alerting for now.

**Comment by kenoir** [comment]
Closing as done.
