### ISSUE TITLE
Link subfield $u URLs in all notes fields

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5433]
## Background

A small number of notes fields from Sierra contain URLs in subfield `$u`. For `520`, which we map to `description`, we wrap the URL in an `a` tag so that it's clickable on the site. We don't currently do this for other notes fields, but should do so.

This should be a transformer change only, as `notes` are output on the page using the same component as `description` and so should pick up the link HTML. We won't want to add a wrapping `p` tags like we do for description, just the `a`.

## Examples

There are not a huge number of URLs in notes, with only 319 in the entire catalogue. About half of those are in `520` and so are already supported.

Most of the rest are in `540`, but they also exist in `538` (which we don't expose), `545`, `533`, `510`, `506` and `542`. It should be fine to implement this generically for any notes field, supporting `$u` if present and doing nothing if it's not there.

- 540: b30173140
- 545: b32880364
- 533: b2353882x
- 510: b28707515
- 506: b32275833
- 542: b1672432x

**Comment by alexwlchan** [comment]
Done!
