### ISSUE TITLE
Fix IIIF manifests with 404'ing in the 'collections' field

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5443]
For https://github.com/wellcomecollection/wellcomecollection.org/issues/7628

There's a certain class of manifests (e.g. https://iiif.wellcomecollection.org/presentation/v2/b11533377) which don't have a "manifests" field (which breaks the front end) and the "collections" field has 404'ing entries (so we can't use that either).

If we can find a list of them, we can give them to Ashley for inspection and hopefully fixing.

**Comment by alexwlchan** [comment]
https://iiif.wellcomecollection.org/presentation/v2/b12947696
https://iiif.wellcomecollection.org/presentation/v2/b12947052
https://iiif.wellcomecollection.org/presentation/v2/b12948512
https://iiif.wellcomecollection.org/presentation/v2/b17523552
https://iiif.wellcomecollection.org/presentation/v2/b11513329
https://iiif.wellcomecollection.org/presentation/v2/b11533377

**Comment by alexwlchan** [comment]
I've passed the list to Ashley to look at.

**Comment by aray-wellcome** [comment]
And just leaving a little breadcrumb for the future in case someone finds this in Github and wonders how to fix it: I will need to re-ingest all of these items in order to fix the  "@type":sc:collection to an  "@type": manifest as these multiple manifestations were created incorrectly in Goobi at the point of loading the marc.xmls, likely by making them a copy1, volume 1 instead of just a copy 1 or a volume 1.

**Comment by pollecuttn** [comment]
@aray-wellcome I don't know how long in takes to re-ingest these. Have these been done yet?

**Comment by aray-wellcome** [comment]
I'm working on the first set for [b12947696](https://iiif.wellcomecollection.org/presentation/v2/b12947696) It has 4 manifests and I have to download them all and reupload them and get a new marc record out of Sierra and then they can only go in one at a time so they create the anchor file correctly. So this will take me a few weeks probably as I'm doing it among other things as well.

**Comment by jamieparkinson** [comment]
note: remember to remove the mitigation in https://github.com/wellcomecollection/wellcomecollection.org/pull/7827 once this is sorted

**Comment by pollecuttn** [comment]
Hi @aray-wellcome , how is this coming along?

**Comment by aray-wellcome** [comment]
It's coming...I'm on the last one, trying to figure out what is a copy or a volume of what. But there's a common error with Proquest items that I need cleared by Intranda to officially call it done.

**Comment by aray-wellcome** [comment]
These manifests are no longer giving 404s so my work here is done. 

b17523552 still isn't showing its last 2 volumes but that is a separate issue I'll deal with if they don't show up later today.

**Comment by pollecuttn** [comment]
@jamieparkinson As Ashley has now stopped the IIIF manifests from 404ing, your mitigation can be removed

**Comment by jamieparkinson** [comment]
Great!
