### ISSUE TITLE
Store data for the API in an opaque field in the format in which it is served.

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/platform#5449]
Currently, when we store data in Elasticsearch, we index all the fields in situ.  This brings some challenges:

- Deeply nested objects get flattened  
- The API code is more complex than it needs to be
- The Elasticsearch Mappings have to be updated with any changes
- The Internal Model and Elasticsearch Mappings for all stages are common to all stages in the pipeline, and also the API, regardless of what that stage needs to know.

One Elasticsearch pattern I have used in the past has been to store the entire document, in the form it is presented in the API, as an opaque block of JSON (an object field with [enabled=false](https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html)), with values copied into separate fields for indexing.

This is not dissimilar to the Elasticsearch [copyTo parameter](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/copy-to.html), but handled by the application outside of Elasticsearch instead, when creating the document to insert.

Storing the data in an opaque field, and matching that shape to the shape the API serves will:

- Simplify the API code - it simply needs to extract the opaque field and pass it on, possibly filtering unwanted fields.
- Help to break up some of the reliance on the Internal Model and its need to represent all information for all stages.

See also: https://github.com/wellcomecollection/platform/issues/5448

**Comment by paul-butcher** [comment]
Doing this (for the whole pipeline) would mean that we could only index those fields that are relevant for the corresponding stage.

This could bring with it a performance benefit

**Comment by alexwlchan** [comment]
It’s done. 🎉 

The works and images API are both rendering their responses by reading a document from the `display` field in Elasticsearch.
