### ISSUE TITLE
Consider using Plated in the id minter

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/platform#5460]
Currently, the ID minter iterates over a JSON object looking for sourceidentifiers.  There are two aspects of this that concern me.

1. it does this deep tree navigation in *our* code, meaning we have to maintain it.
2. It seems to get each bunch of nodes as a list of objects, rather than cursoring through the document, this may be memory-hungry (though I don't know what is happening under-the-hood in Circe, so it might not be).

The Circe documentation has this example of making deep recursive modifications to JSON.

https://circe.github.io/circe/optics.html#recursively-modifying-json

This would require less code on our part, and could be less memory-intensive.

One downside is that (I think) the reason the id_minter works the way it does is so that it can batch up requests to the database. Whereas the most obvious approach using Plated would likely make one request per identifier.  This may be slower.

**Comment by paul-butcher** [comment]
The reason I thought of this was that I tried to reindex METS data on its own on Friday (which I now know is not normal and prone to having memory problems).  I was wondering if there was anything that could be done to make it use less memory.

**Comment by jamieparkinson** [comment]
Funnily enough we actually already do use `Plated` for inserting canonical IDs: https://github.com/wellcomecollection/catalogue-pipeline/blob/19b8c201ffd79b921c808d244f4e156c47ac4551/pipeline/id_minter/src/main/scala/weco/pipeline/id_minter/steps/SourceIdentifierEmbedder.scala#L79

I vaguely recall that `Plated` isn't (or wasn't) tail-call-optimised, though, so I'm not sure there'd be any memory gains

**Comment by jamieparkinson** [comment]
Further interesting context: https://github.com/wellcomecollection/catalogue-pipeline/pull/454
