### ISSUE TITLE
Hierarchical Sierra Data Snags

### ISSUE THREAD

**Issue by paul-butcher** [wellcomecollection/platform#5462]
Hierarchical data from Sierra is now available.  There are a few minor flaws that would be nice to clean up.

1. The top-level document in the tree shows its reference control number. This should not be visible.
2. The child documents show membership using the series tags as well as the hierarchy. The tags should not be there.

**Comment by paul-butcher** [comment]
Actually, top-level showing the reference number is quite a nice unexpected feature.  I'm going to leave it unless someone complains.

**Comment by paul-butcher** [comment]
Blocked by https://github.com/wellcomecollection/platform/issues/5471

**Comment by paul-butcher** [comment]
In conversation with Victoria Webb, the Fallaize Collection poses a challenge:

The collection record itself has two entries - a box, and "Studio portraits of women".

https://search.wellcomelibrary.org/iii/encore/record/C__Rb3303244?lang=eng&marcData=Y

```
774 0  |tA metal and timber box (chest, trunk), once the property
       of E N Fallaize.|w540972i 
774 0  |tStudio portraits of women.|w3288731i 
```

"Studio portraits of women" is part of Fallaize Collection, and contains several individual portraits

https://search.wellcomelibrary.org/iii/encore/record/C__Rb3288731?lang=eng&marcData=Y

```
773 0  |tThe Fallaize Collection.|w3303244i 
774 0  |tA young woman posing naked, in front of a painted 
       backdrop in a photographic studio.|w534631i 
...
```

The individual portraits are part of "Studio portraits of women"

https://search.wellcomelibrary.org/iii/encore/record/C__Rb1531585?lang=eng&marcData=Y
```
773 0  |tStudio portraits of women.|w3288731i 
```

The problem is that the individual portraits do not know about the Fallaize Collection, so the hierarchy cannot be constructed as part of transforming each record.  It must be handled at a step when more data is present, e.g. the relation embedder.

However, the relation embedder must operate over a tree that contains the root node.  Otherwise examples from CALM and TEI that contain the same subpaths would be incorrectly merged (e.g. in `MYROOT/A1/B2/C1` and `OTHERROOT/A1/B2/C2`, `A1/B2` is a common subpath, `C1` and `C2` are distinct, but if we don't constrain the path search to start at ROOT, then C1 and C2 would incorrectly appear in both trees).

So we need a way to signal that, in the example above, `3288731i` is genuinely the same thing in both paths: `3288731i/534631i` and `3303244i/3288731i`.

**Comment by paul-butcher** [comment]
On this snag: 

> The child documents show membership using the series tags as well as the hierarchy. The tags should not be there.

If there is an exact match, they will now not be displayed. However, in the Basil Hood example, there is a difference in punctuation between the title of the document "Basil Hood. Photograph Album." and the title of the parent Link "Basil Hood. Photograph Album" (actually, with a trailing comma in the MARC, but that's already been removed in transformation).

**Comment by paul-butcher** [comment]
In this case, the titles are an exact match, so do not produce a duplicate series tag https://wellcomecollection.org/works/afm5xr6t

@jtweed I can easily implement something to match having removed trailing punctuation, but is this something where we would prefer the data to be updated? (b11729776: "Basil Hood. Photograph Album." -> "Basil Hood. Photograph Album")

**Comment by jtweed** [comment]
The data will be subject to standard cataloguing rules that includes the punctuation. So I think if we're removing in one place but not another, that's on us.
