### ISSUE TITLE
Remove phantom WAM links from Proquest Ebook Central records

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#5473]
On 23 March 2022 a record was reported to have an extraneous WAM link on wc.org that isn't in Sierra. This was fixed manually: https://wellcome.slack.com/archives/C8X9YKM5X/p1648038811138589

Subsequently on 29 March further problems were seen with some (not all) Proquest Ebook Central records from the same package - see https://wellcome.slack.com/archives/C8X9YKM5X/p1648546294538429?thread_ts=1648038811.138589&cid=C8X9YKM5X 

The records affected are: 
bnumber	| id
---	| ---
b32891064 | cygpd765
b32891088 | gkugpxhr
b32891222 | c3syrxrg
b32891581 | ckuxq9wm
b3289160x | vxyd6a8c
b32891635 | ra62g5wr
b32891647 | bedess5u
b32891660 | wkw7py5k
b32891672 | ua2t5g66
b32891714 | ueverayq

NB the checkins attached to:
b32891635 / c11153027 
b32891647 / c11153039
don't have 856 links. I have asked Nic to look at those again.

The above records should have no WAM links on wc.org.

**Comment by alexwlchan** [comment]
A potentially useful bit of context: normally we use the `modifiedDate` to detect changes on Sierra records, but sometimes holdings records can be updated without the `modifiedDate` changing.

We primarily see this on e-journals for the range of issues that are available – see the comment on the [update embargoed holdings Lambda](https://github.com/wellcomecollection/catalogue-pipeline/blob/main/sierra_adapter/update_embargoed_holdings/src/update_embargoed_holdings.py) – and maybe something similar is happening here. Records are changing under our feet but we're not noticing.

**Comment by alexwlchan** [comment]
I'll pick this up as a one-off task, and use it as an opportunity to update the Sierra adapter documentation.

**Comment by alexwlchan** [comment]
I've asked the Sierra holdings adapter to re-fetch all the holdings, so any stale data should be flushed out. 🤞
