### ISSUE TITLE
Can't advance beyond page 400 in image search results

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#5478]
This came from an enquirer via an email to info@wellcomecollection.org:

"In the search for pictures, although it shows up to page 806, I can't go beyond page 400, because it gives an error API Image - images attached. "

![image](https://user-images.githubusercontent.com/1446072/161516845-968ac727-0721-4879-9f34-abaec43438b9.png)
![image](https://user-images.githubusercontent.com/1446072/161517025-b73517aa-81e6-47d4-b773-34f4205002de.png)

p 400: https://wellcomecollection.org/images?query=engraved&page=400
p 401: https://wellcomecollection.org/images?query=engraved&page=401

You also cannot get beyond p400 in the catalogue, but you get more information there:
![cat-401](https://user-images.githubusercontent.com/1446072/161517380-944e6494-812b-4f29-8149-a6a0cca4abdb.PNG)

https://wellcomecollection.org/works?query=engraved&page=401

Do we need a similar message for images? Is there a snapshot of images available in the same way as there is for the catalogue?

**Comment by jamieparkinson** [comment]
https://wellcomecollection.org/images?page=401 this is now resolved
