### ISSUE TITLE
Listener for bag ingestions - that are ready for processing

### ISSUE THREAD

**Issue by donaldgray** [wellcomecollection/platform#5494]
The IIIF-Builder will need to listen for new bag registration SNS notifications for born digital material.

At the moment, Goobi informs iiif-builder via a simple GET (https://github.com/wellcomecollection/platform/issues/5495) when a b number has reached the end of the **_digitisation_** workflow and is ready for a Manifest to be made. This is a digitisation workflow step - it's not the same as a bag ingest into storage, which might happen one or more times before the end of the digitisation workflow. We don't necessarily want to process a bag every time it goes to the storage service.

It would be good to standardise the mechanism, and introduce a queue for the iiif-builder that both Goobi- and Archivematica-origin messages can be read from.

There is already a topic for the storage service itself. The model for these notifications is: [BagRegistrationNotification.scala](https://github.com/wellcomecollection/storage-service/blob/main/common/src/main/scala/weco/storage_service/BagRegistrationNotification.scala).

But this is a firehose of storage service activity. There are no attributes available to apply filtering on so we may need to implement some filtering on code (by `type`, maybe. Will need to test to confirm).

### A new SNS Topic

Ideally we have a new topic, whose messages are just "iiif-ready" notifications. The message body is really only one piece of data - the identifier that gets that bag from the storage service, so either a b number or an Archivematica guid.

* Goobi can simply place messages on this topic instead of making the HTTP call it does currently.
* The born digital messages could be placed by something listening to the firehose mentioned above and picking relevant events, or it could be something in Archivematica workflow, like the goobi call - whatever the mechanism, the logic is external to iiif-builder
* The dashboard has a simple tool to manually enqueue both kinds of objects, just as it does now with "Simulate Goobi Call" - we can get this working first to test it out, so that the first implemented notifier is neither Archivematica or Goobi but the dashboard itself.

This new topic could work in a similar way to existing:

The SNS topic is in the Wellcome platform account
The Queue the DLCS listens to is in the DLCS account
A cross-account publication allows all of Dashboard, Goobi and (Archivematica or custom adaptor) to notify topic, and for DLCS to pick up the messages.

This custom adaptor could be built by Digirati or Platform team. If an attribute is added to the Archivematica message then we could use [SNS filtering](https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html) to only get these we're interested in (but the message would be more than just the Id).

We have already tested a cross account SQS->SNS subscription (this has been successfully tested on Staging env).

NB the iiif-builder workflow would now be triggered by picking up messages from this queue rather that the Goobi call. But we won't change the way the iiif-builder maintains an internal job queue - it doesn't immediately process its jobs, it delays starting to allow for multiple calls: another event for the same object arriving before work has started doesn't cause it to be processed twice, it just resets the "buffer" time (e.g., 10 minutes, or 1 hour). This allows for the observed behaviour of a workflow being finished but occasionally reopened shortly after to tweak something. We wait for activity to go quiet before starting the iiif-building.

**Comment by alexwlchan** [comment]
> The message body is really only one piece of data - the identifier that gets that bag from the storage service, so either a b number or an Archivematica guid.

Minor nitpick: you'll need some context to tell whether this is digitised or born-digital material; you can't just retrieve bags based on their identifier. Within the storage service API we use "spaces" as a high-level grouping of content; it's probably best to have that passed by whatever's writing to this topic as they just put content in that space (Goobi, Archivematica, dashboard); iiif-builder could then pass that transparently to the storage service API.

```
GET /<space>/<externalIdentifier>
GET /<space>/<externalIdentifier>/<version>

// e.g.
GET /digitised/b12345678
GET /born-digital/PP%2FCRI%2F123
```

**Comment by donaldgray** [comment]
Although the bnumber is just an identifier, the DDS currently adds semantics to it - if it's a bnumber then digitised; else born-digital. However, I think adding a `"space"` parameter to the message body makes it more explicit and could allow for the addition of another high-level grouping to be passed transparently to the storage API (although there'd potentially be additional work elsewhere to handle!).

Based on the above comment I think a sensible message format could be:

```json
{
  "identifier": "<externalIdentifier>",
  "space": "digitised|born-digital",
  "origin": "goobi|archivematica|dashboard"
}
```

`"origin"` is optional and wouldn't have any influence on processing, it's only there as it could help to log.

**Comment by alexwlchan** [comment]
This all sounds fine to me.

Because a single queue can subscribe to multiple topics, in the past we've tended towards a single topic per source:

```mermaid
graph LR
    T1[Archivematica topic] -- cross-account publishing --> Q[queue]
    T2[Goobi topic] -- cross-account publishing --> Q[queue]
    T3[Dashboard topic] -- cross-account publishing --> Q[queue]
```

That way messages from a single source can be separated out (e.g. for testing/sampling) or turned off as necessary. But I think that's a small distinction.

**Comment by tomcrane** [comment]
Going to write something that can process and act on this message (but not the immediate bit before that picks it up off of the queue).

Just to confirm with some examples, from the conversation above, our messages will look like:

```
{
  "identifier": "b30246738",
  "space": "digitised",
  "origin": "goobi",
  "timeSent": "2022-10-04 11:26:34.67"
}
```

```
{
  "identifier": "PPCRI/D/4/5A",
  "space": "born-digital",
  "origin": "archivematica",
  "timeSent": "2022-10-04 11:26:34.67"
}
```
