### ISSUE TITLE
Determine weco:patron_role to DLCS role mapping

### ISSUE THREAD

**Issue by donaldgray** [wellcomecollection/platform#5496]
https://github.com/dlcs/protagonist/issues/278 provided a sample app for mapping patron roles to DLCS roles.

We need to determine:
* What roles we require in DLCS (currently `restrictedFiles`, `clinicalImages` and `clickthrough`).
* How the weco patrol roles are mapped to these (from `Reader`, `Staff`, `SelfRegistered` and `Excluded`), and whether these are granular enough.

The mappings configured in the demo app are visible here : https://auth-test.wellcomecollection.digirati.io/mappings

**Comment by tomcrane** [comment]
See discussion in Slack
https://digirati.slack.com/archives/CBT40CMKQ/p1664283005119249

In the experiemental Archivematica METS some assets have "Restricted" and in order to process them I have added this as a known AccessCondition. This should be removed once the final form of METS is in use.

**Comment by kenoir** [comment]
See further discussion in Slack: https://wellcome.slack.com/archives/CBT40CMKQ/p1717676657432939

Relates to: 
- https://github.com/wellcomecollection/identity/issues/400
- https://github.com/wellcomecollection/identity/pull/403
