### ISSUE TITLE
Setup for A/B testing using new DLCS

### ISSUE THREAD

**Issue by donaldgray** [wellcomecollection/platform#5497]
The updated DLCS is a ground-up rewrite using updated dotnet core framework functionality for ease of maintainability (chief of which is using [YARP](https://microsoft.github.io/reverse-proxy/) rather than nginx to have all reverse-proxy logic in 1 place in 1 language).

It's also using a new infrastructure layout and new image-server so we need to do some A/B testing to verify that performance and functionality is appropriate.

**Comment by donaldgray** [comment]
Reminder that we will need to set flag introduced in https://github.com/dlcs/protagonist/issues/325 where asset.role == "closed"

**Comment by tomcrane** [comment]
Go Live Rollout Plan

We could do this either way but we think it better to:

 - get new DLCS deployed first and run live with this before...
 - ...replace current DDS with new Born-Digital aware DDS (`develop`)

 - [ ] Required tf [iiif-stage-new](https://github.com/wellcomecollection/platform-infrastructure/pull/349) infra/routes is applied 
 - [ ] Determine testing requirements - do we need a iiif-new environment too? (see note below)
 - [ ] New DLCS works with current DDS `main`
 - [ ] New DLCS supports clickthrough pattern auth same as current Deliverator
 - [ ] Simulated live traffic loads are acceptable (i.e., way better than current!)
 - [ ] Locust load tests all look good (random selections)
 - [ ] Specific scripted tests all give same result (known edge cases, auth etc)
 - [ ] New DLCS works with current born-digital 2022 `develop` branch
 - [ ] When should we impose a workflow freeze? 
 - [ ] Can we run Old and New DLCS simultaneously against the same PostgreSQL? Do we want to do this?

# Notes

Do we need a iiif-new environment?

Yes if [front-end toggles](https://github.com/wellcomecollection/platform-infrastructure/pull/349) can pick the source of IIIF

Existing environments (only one DLCS and therefore only one DLCS DB, but we use different spaces for stage/prod:

iiif => prod storage, stage dds buckets, space 5
iiif-stage => stage storage, stage dds buckets, space 6
iiif-test => prod storage, stage dds buckets, space 6

In [PR tf](https://github.com/wellcomecollection/platform-infrastructure/pull/349)
 - iiif-stage-new => neworchestrator / stage-new dds buckets, space 6, "empty" protagonist DB

Do we need a iiif-new environment?
 - iiif-new => neworchestrator / new-api / prod storage, prod-new (?) dds buckets, space 5 - a backup and restore of the existing PG DB
We _do_ need this for true A/B switching from the front end
But practically it's going to need to serve existing Manifests from S3
These need to have their DLCS paths rewritten before being served as well as their DDS paths; currently the `RewriteDomainLinksTo` appSetting supports the latter but not the former.

# Running against a shared database

Initial testing uses an empty DLCS database
Later testing uses a fully populated **copy** of the DLCS database
If there is a content freeze for as long as there is toggle-able A/B testing then that copy is OK
If we want to re-enable workflow before switching over to all new DDS then they will need to share the same postgres database. This is possible but needs further assessing.
