### ISSUE TITLE
Upgrade to Elasticsearch 8

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5551]

**Comment by alexwlchan** [comment]
Chatting to Paul yesterday, this is the list we came up with of things that talk to Elasticsearch and might need upgrading:

<img width="888" alt="Screenshot 2022-06-10 at 09 55 31" src="https://user-images.githubusercontent.com/301220/173029848-385b0d2a-d182-4061-9959-1d636caaebbc.png">

**Comment by jamieparkinson** [comment]
Amusingly, the above diagram is missing a fairly crucial service: the API! 😬

**Comment by alexwlchan** [comment]
oops
