### ISSUE TITLE
Add the provenance/acquisition notes in the TEI transformer

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5558]
Adrian has told us that the provenance/acquisition notes from the TEI files are of particular interest to researchers; they're one of the few items not completed [from the original mapping](https://github.com/wellcomecollection/wellcome-collection-tei/blob/main/docs/frontend/draft.md).

We should add these notes to the TEI transformer, so they appear on the website.

Example: https://github.com/wellcomecollection/wellcome-collection-tei/blob/31d817a5b313aa32ff73cc009fb42c2c3f370940/Ethiopian/Ethiopian_12.xml#L155-L158

**Comment by paul-butcher** [comment]
The date attributes associated with this element: when, notAfter and notBefore.  Should these be turned into prose in the text of the note?

e.g.
 
Not before: 1855 - not after: 1868: Part of the library of Tewodros II, Emperor of Ethiopian at Maqdala.
1868-04: Taken from Maqdala during the British Expedition to Abyssinia in April 1868.

Or is that a later task?

**Comment by alexwlchan** [comment]
I think let's turn them into prose now, yeah. It doesn't have to be perfect, but once we can see it we can start to see how it might be improved.
