### ISSUE TITLE
Add the hand note in the TEI transformer

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5559]
This is one of the few fields not completed [from the original mapping](https://github.com/wellcomecollection/wellcome-collection-tei/blob/main/docs/frontend/draft.md).

We should add these notes to the TEI transformer, so they appear on the website.

Example: https://github.com/wellcomecollection/wellcome-collection-tei/blob/726a1b8f0afee08e07ad2c7f07458d92bb2f510a/Hebrew/Hebrew_A_31.xml#L100-L103

This comes after #5558.

**Comment by paul-butcher** [comment]
It looks like this is already the case.  I have added a test to show it.  The example data in the description is already visible on the site.

![image](https://user-images.githubusercontent.com/64621/175928569-97d8cec3-efb9-49ba-bf04-111df05f9a50.png)

**Comment by paul-butcher** [comment]
Having looked at the mapping document, it is not handNote that is missing, but handDesc (without handNotes).  Is that what is intended in this ticket?

The only example of this I can find is here: https://github.com/wellcomecollection/wellcome-collection-tei/blob/f5e8ee62823098d6ab8682d4c196a9d20ea16fc8/Spanish/WMS_Amer.19.xml#L92

```
$ find . -name '*xml'  -not -path '*Templates*' -not -path '*.idea*' -not -path '*docs*'| xargs -J % xml sel -B -I -N 't=http://www.tei-c.org/ns/1.0' -t -c '//t:handDesc/node()[not(local-name()="handNote")]' '%' 2>/dev/null | sort | uniq

<!-- Add or delete <handNote> elements as needed -->
<p xmlns="http://www.tei-c.org/ns/1.0">Signature, rúbrica, and insertions in author's hand.</p>

```

```
$ find . -name '*xml'  -not -path '*Templates*' -not -path '*.idea*' -not -path '*docs*'| xargs -J % xml sel -N 't=http://www.tei-c.org/ns/1.0' -t -i '//t:handDesc/t:p' -f -n '%' 2>/dev/null
./Spanish/WMS_Amer.19.xml

```
