### ISSUE TITLE
Why do we allow searching by the title of the original Miro work?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5560]
Within the pipeline, we record two source works for an image: the canonical work and the redirected work.

```mermaid
flowchart TD
     TS([title search]) -- source.canonicalWork.data.title --> CW
     TS -- source.redirectedWork.data.title --> RW
     CW[canonical work] --> I[image]
     RW[redirected work] --> I
     style RW stroke-dasharray: 5 5
```     

This is used when a Miro image is merged into something else, e.g. a Sierra work. In this case, the Sierra work is canonical and the Miro work is redirected.

We use the redirected work to search a couple of fields, in particular description and title. If you search for the title of a Miro work, you'll find the image – even if the displayed work on the site has a different title from Sierra.

It's not obvious why we allow searching on this field (or at least, neither Harrison nor Jamie nor I can remember; see [Slack discussion](https://wellcome.slack.com/archives/C016NQB58N4/p1655381761482889)).

We should find out why, write it down, then decide if it's still the best approach.

**Comment by pollecuttn** [comment]
I wonder whether things could have been cited with the title that was in Miro, so those titles would still need to turn up something when searched. Hannah worked with Miro so might be able to shed light on this.

**Comment by alexwlchan** [comment]
Jonathan has ruled; I'll open a new ticket to describe the changes we want to make.

**Comment by alexwlchan** [comment]
> I wonder whether things could have been cited with the title that was in Miro, so those titles would still need to turn up something when searched

The trouble is, there'd be no way for a user to know they were looking at the right thing – even if they got a single result for the title, that title wouldn't appear anywhere so they wouldn't know if it was what they wanted or an unlucky coincidence.
