### ISSUE TITLE
Fix issue with duplicate subject labels in aggregations

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5563]
Consider the following API request: https://api.wellcomecollection.org/catalogue/v2/images?source.subjects.label=Horses&aggregations=source.subjects.label

This is the aggregation:

```
        {
          "data": {
            "id": "zssqcytq",
            "label": "Horses",
            "concepts": [],
            "type": "Subject"
          },
          "count": 364,
          "type": "AggregationBucket"
        },
        {
          "data": {
            "label": "Horses",
            "concepts": [],
            "type": "Subject"
          },
          "count": 150,
          "type": "AggregationBucket"
        },
        ...
        {
          "data": {
            "id": "jrnfsbrf",
            "label": "Horses",
            "concepts": [],
            "type": "Subject"
          },
          "count": 12,
          "type": "AggregationBucket"
        },
```

Because the phrase "Horses" appears three times, it appears as three different entries in the front-end filter; consider https://www-stage.wellcomecollection.org/images?source.subjects.label=Horses

For aggregations it's probably sufficient to bin the IDs when we're aggregating by label, but this might point to a broader issue for subjects later on.

**Comment by alexwlchan** [comment]
You can see the same issue here for works: https://api.wellcomecollection.org/catalogue/v2/works?aggregations=subjects.label&query=horses

**Comment by jtweed** [comment]
Yeah this is a definite bug, at least in the "Do What I Mean" sense. Aggregating by label should do just that, it shouldn't also take IDs into account.

I guess we just pick the first one for returning in the aggregation, as to then go on and filter by label should return results with any of the IDs.

Once we filter by IDs, then yes we probably need to aggregate by IDs too. Concept merging should hopefully fix this problem, though it would be good to confirm why this is occurring. Are these concepts from multiple sources or are we giving an identity to strings without de-duping?

**Comment by alexwlchan** [comment]
> I guess we just pick the first one for returning in the aggregation, as to then go on and filter by label should return results with any of the IDs.

I think we should take a slightly different approach, and remove the identifiers for the purpose of aggregations – so in this case we'd have a single, unidentified aggregation with 364 + 150 + 12 = 526 entries for "horse". This is what we used to have, and it got broken in some recent index restructuring.

> Are these concepts from multiple sources or are we giving an identity to strings without de-duping?

Multiple sources.

<table><tr><th>Work ID</th><th>Sierra ID</th><th>MARC source value</th></tr>
<tr><td>
<a href="https://api.wellcomecollection.org/catalogue/v2/works/bvt9jdzf?include=identifiers%2Csubjects">bvt9jdzf</a>
</td><td> b2498582x</td><td><code>650  0 Horses.|0sh 85062160</code> (650 ind 2 = 0 ⇒ LCSH)</tr>
<tr><td><a href="https://api.wellcomecollection.org/catalogue/v2/works/y9dyqe8m?include=identifiers%2Csubjects"> y9dyqe8m</a></td><td>b11318430</td><td><code>650  2 Horses.|0D006736</code> (650 ind 2 = 2 ⇒ MeSH)</td></tr>
<tr><td><a href="https://api.wellcomecollection.org/catalogue/v2/works/uzen4bba?include=identifiers%2Csubjects">uzen4bba</a></td><td>b15439306</td><td><code>650  2 Horses.</code></td></tr></table>

**Comment by jtweed** [comment]
That sounds like a much better approach, then when we have identified filters and aggregations those can return the identified concept.

Interesting example, thanks. Shows that as part of https://github.com/wellcomecollection/docs/pull/83 we do need to match and merge concepts.

**Comment by alexwlchan** [comment]
Fixed by the latest reindex.
