### ISSUE TITLE
catalogue.wl.org redirected for external users

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5572]
## Objective

Improve the information available about works and access to digitised items

## Measures

- Redirects in place for external traffic only

- Staff able to access OPAC in-office and on VPN

- Decreased usage of catalogue.wellcomelibrary.org

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/6699469

**Comment by pollecuttn** [comment]
Include redirect from https://catalogue.wellcomelibrary.org/selfreg to https://wellcomecollection.org/signup
