### ISSUE TITLE
Remove Calm-Miro merging rules

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5576]
To support the re-cataloguing of Miro data in Calm, we were previously asked to merge Calm and Miro works so that Miro works that had been re-catalogued would be suppressed from the site.

The way this cataloguing is being done has changed and this merging is no required. It's in fact causing problems, as Collections Information are using the field the merging is based on for another purpose.

Suppressing the Miro records is now being handled by ingesting the Miro images through Goobi. We've therefore been asked to remove the Calm-Miro merging rules.

**Comment by alexwlchan** [comment]
Some discussion in Slack here: https://wellcome.slack.com/archives/C02ANCYL90E/p1658750129789039

**Comment by alexwlchan** [comment]
This has been reindexed and is live in the API. There was some discussion about whether we'd also change Calm+Miro+Sierra merging, but if that is needed we can open a new ticket. Closing as done.
