### ISSUE TITLE
246 dates in <> brackets not displaying

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5579]
Some dates in the data are enclosed in angle brackets, for example in the variant titles on b33039665:

https://wellcomecollection.org/works/ayn8y83u

```
246 1  |iIssues <March 1963-July 1967> have subtitle:|aThe 
       magazine of the Spastics Society 
```

These aren’t displaying on the works page, where the above MARC is rendered out as:

`Issues have subtitle: The magazine of the Spastics Society`

This is because the angle brackets are getting interpreted as HTML tags. We need to work out how to escape these so that they aren’t interpreted as HTML.

**Comment by alexwlchan** [comment]
Should we be escaping these in the API data or in the front-end?

**Comment by rcantin-w** [comment]
The first part I can do now, but I'll need more context to decide where we _actually_ want to use it. I'm not sure where it's being set and why there would be HTML in the first place?
In the meantime I'll have a look at where it's used within the Works page.

**Comment by alexwlchan** [comment]
> I'll need more context to decide where we _actually_ want to use it.

In general, you'll find works fields fall into two broad buckets: single-line bits of short text which should probably be HTML-free (like a contributor label) and free-form text which can (like notes).

**Comment by alexwlchan** [comment]
Okay, so I had a look through yesterday's snapshot for instances of an opening angle bracket (&lt;):

<table>
<tr><td>description</td><td>96,412</td></tr>
<tr><td>notes</td><td>32,212</td></tr>
<tr><td>succeededBy</td><td>22,301</td></tr>
<tr><td>precededBy</td><td>21,962</td></tr>
<tr><td>title</td><td>9,569</td></tr>
<tr><td>partOf</td><td>6,442</td></tr>
<tr><td>items</td><td>2,920</td></tr>
<tr><td>physicalDescription</td><td>2,691</td></tr>
<tr><td>parts</td><td>2,069</td></tr>
<tr><td>lettering</td><td>529</td></tr>
<tr><td>production</td><td>477</td></tr>
<tr><td>alternativeTitles</td><td>132</td></tr>
<tr><td>contributors</td><td>15</td></tr>
<tr><td>genres</td><td>1</td></tr>
</table>

Here's a list of work IDs they use: [brackets.json.zip](https://github.com/wellcomecollection/platform/files/9403460/brackets.json.zip)

We can drill down on these further, but for now this is an initial snapshot of fields that *might* contain HTML, and presumably we can turn off raw HTML for any fields that don't.

**Comment by alexwlchan** [comment]
* genres are already handled correctly; see https://wellcomecollection.org/works?query=ceps4uqe&page=1
* also contributors: e.g. https://wellcomecollection.org/works/htduvx7g

**Comment by alexwlchan** [comment]
This seems to be working on the site.

As part of this work, we've drastically shrunk the number of places where we render HTML unescaped from the Catalogue API – most fields shouldn't be returning raw HTML, so we won't render if if they do.

There are a few other places where we still render raw HTML (e.g. description), but I think those are fine.
