### ISSUE TITLE
Set up redirects for OPAC URLs

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5580]
### Search

	https://catalogue.wellcomelibrary.org
	https://catalogue.wellcomelibrary.org/search/X
	https://catalogue.wellcomelibrary.org/search/Y
	https://catalogue.wellcomelibrary.org/search/j
	https://catalogue.wellcomelibrary.org/search/l
	->
	https://wellcomecollection.org/collections

### Search results

	https://catalogue.wellcomelibrary.org/search/a?searchtype={any}&searcharg={health}&searchscope={any}&SORT={any}
	https://catalogue.wellcomelibrary.org/search~S12?/Y{health}&searchscope=12&SORT=D/Y{health}&searchscope=12&SORT=D&SUBKEY={health}/1%2C32000%2C32000%2CB/frameset&FF=Y{health}&searchscope=12&SORT=D&1%2C1%2C
	->
	https://wellcomecollection.org/works?query={health}

### Object number

	https://catalogue.wellcomelibrary.org/search/o{44843i}
	->
	https://wellcomecollection.org/works?query={44843i}

### Subject heading

	https://catalogue.wellcomelibrary.org/search~S12?/m{Zines.}/mzines/-3,-1,0,B/browse
	->
	https://wellcomecollection.org/works?subjects.label={Zines.}

### E-journals

	https://catalogue.wellcomelibrary.org/search/X?SEARCH=1&searchscope=7&SORT=AX&m=j
	->
	https://wellcomecollection.org/works?workType=d&availabilities=online

### Bibs

	https://catalogue.wellcomelibrary.org/record={b1191208}
	https://catalogue.wellcomelibrary.org/record={b3303991}~S12
	->
	https://wellcomecollection.org/works/{bnum-id-lookup}

### Sign in

	https://catalogue.wellcomelibrary.org/patroninfo
	https://catalogue.wellcomelibrary.org/iii/cas/login
	https://catalogue.wellcomelibrary.org/pinreset
	->
	https://wellcomecollection.org/account/api/auth/login
	

### Sign up

	https://catalogue.wellcomelibrary.org/selfreg
	->
	https://wellcomecollection.org/signup

**Comment by pollecuttn** [comment]
Noting here as I was checking with LSS, but shouldn't make a difference to what's stated above:

> The following web reports are needed internally only:

> - http://catalogue.wellcomelibrary.org/manage redirects to http://libsys.wellcomelibrary.org:4448/managerep/mainview/0//? internally (on VPN).  The redirect can’t be reached externally

> - https://catalogue.wellcomelibrary.org/iii/webrpt/app - also available externally, but presume it doesn’t need to be as staff use only

**Comment by pollecuttn** [comment]
ILL links that need to stay accessible (and will only be needed by staff internally on the VPN:

- https://catalogue.wellcomelibrary.org/screens/ill.html
- https://catalogue.wellcomelibrary.org/illb
- https://catalogue.wellcomelibrary.org/illj

**Comment by jtweed** [comment]
To just note here, all catalogue.wl.org URLs should still be accessible on the internal network/VPN, not just the ILL ones above. It's also fine for the ILL ones to not be available externally.

**Comment by pollecuttn** [comment]
Include redirect from https://catalogue.wellcomelibrary.org/selfreg to https://wellcomecollection.org/signup

**Comment by alexwlchan** [comment]
These redirects are all ready to go and could be enabled pretty quickly; we're going to deploy them on **Monday 8th August**. So we're waiting until then.

**Comment by alexwlchan** [comment]
The redirects are live. 🎉 

We had to remove a TXT record to publish the CNAME record, but (1) it's recorded in the Git history and (2) we've emailed LSS to tell them about it, in case it was important.
