### ISSUE TITLE
Only display main contributors in search results and in work header

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5582]
### Background

When it comes to describing the names associated with a work, which we consider contributors, library catalogues make a distinction between main entries  (1XX fields) and added entries (7XX fields).

Main entries are those directly responsible for creating or bringing the materials together, whilst the possible relationships are broader and more varied for added entries.

Currently we draw no distinction between main and added entries, always displaying the first contributor in search results and the work header. When there is no main entry but there are added entries, this gives undue prominence and responsibility to an added entry name.

This prominence makes the first added entry appear more responsible for the work than they actually are, which has the potential to mislead researchers. We’d like to fix this.

### User stories

As a librarian
I want to distinguish between main entry and added entry names
So that it’s clear who was directly responsible for a work

As a researcher
I want to be sure who was directly responsible for a work
So that I can understand how different people were involved

### Acceptance criteria

- Main contributors are indicated in the Catalogue API
- 1XX fields are main contributors, 7XX fields are not
- First contributor only shown in search results if it’s a main contributor
- First contributor only shown in work header if it’s a main contributor
- All contributors are shown in the full contributors list, in the existing order

**Comment by alexwlchan** [comment]
We've had a [discussion in Slack](https://wellcome.slack.com/archives/C02ANCYL90E/p1658754876199469) about how we're going to mark "main" contributors in the API.

We're going to add a boolean flag `primary` to the `Contributor` model; this is reasonably simple, has no impact on search, and we can easily remove it later if we want to. e.g.

```json
{
  "label": "Florence Nightingale",
  "primary": true,
  "type": "Contributor"
}
```

We hope that `primary` is a somewhat intuitive name that other people might understand.

**Comment by alexwlchan** [comment]
A couple of examples:

A Calm work where the only contributor has `primary: true`:
https://api.wellcomecollection.org/catalogue/v2/works/a2242545?include=contributors,identifiers

A Sierra work where the contributors are a mix of `primary: true/false`:
https://api.wellcomecollection.org/catalogue/v2/works/nbsqzbba?include=contributors,identifiers

**Comment by jtweed** [comment]
Looks great, thanks 👍 

I think the Calm example is meant to be this one (only the collection level has the contributor):

https://api.wellcomecollection.org/catalogue/v2/works/uad4jhwg?include=contributors,identifiers

And here's an example from Sierra where all the contributors are `primary: false`:

https://api.wellcomecollection.org/catalogue/v2/works/fwnjq9md?include=contributors,identifiers

**Comment by rcantin-w** [comment]
Changes deployed to production

**Search Results page**: Only main contributor is displayed below title
https://wellcomecollection.org/works?query=florence+nightingale

**Work page**: Only main contributor is displayed below title, all contributors listed in Contributors section
https://wellcomecollection.org/works/dv5jtfvs (has a main)
https://wellcomecollection.org/works/sstzhgmc (has no main)
