### ISSUE TITLE
Multi-volume work missing a volume

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5583]
https://wellcomecollection.org/works/yn8nshmc

has been reported as missing a volume (vol 3), which does appear on OPAC:

https://catalogue.wellcomelibrary.org/record=b3298733

**Comment by alexwlchan** [comment]
I'm not sure what the underlying issue was, but I see volume 3 there now.

<img width="1149" alt="Screenshot 2022-09-01 at 16 20 48" src="https://user-images.githubusercontent.com/301220/187951297-f27cb664-4922-4e30-a4cb-7c8b4b3b5e0e.png">
