### ISSUE TITLE
Find works in the collections by or about a concept

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5586]
### User stories

As a researcher
I want to see a selection of works by or a about a concept
So that I can decide if it is worth researching further

As a researcher
I want to search for all works by or about a concept
So that I can find other things that might be relevant to my research

### Measures

- Total works pages viewed
- Unique work pages viewed
- Total item pages viewed
- Unique item pages viewed

### Acceptance criteria

- Concept pages include a list of works about that concept
- People pages also include a list of works by that person
- Link to filtered searches that return all relevant works
- List items link to works

**Comment by rcantin-w** [comment]
Original mockups:

![Image](https://user-images.githubusercontent.com/110461050/185372264-dc6a16d2-4497-469f-b1be-321f6a746187.png)

This [has been integrated](https://github.com/wellcomecollection/wellcomecollection.org/pull/8283), but now waiting on updated mockups for the Tabs (what they look like on mobile, when there's more of them, etc.)

I believe these acceptance criteria are all done, we could look at analytics once designs are finalised.

**Comment by rcantin-w** [comment]
@GarethOrmerod regarding this bug we saw the other day, when an image is a landscape, it's even worse when it's really wide.
I could make it fit in the square but it doesn't look like much. Would you have an idea?

![Image](https://user-images.githubusercontent.com/110461050/189148296-907996bc-0426-44c8-8447-b86bf39fb0b0.png)
![Image](https://user-images.githubusercontent.com/110461050/189148297-fd0d4841-2523-4132-983a-6acf5325a2a6.png)

**Comment by rcantin-w** [comment]
Had a chat with Gareth, will make it look like this for now



![Image](https://user-images.githubusercontent.com/110461050/189159572-d038d361-57b6-40d7-b558-3c3bd939f465.png)

**Comment by rcantin-w** [comment]
I forgot to ask on our call, @GarethOrmerod are we happy with the mobile look?



![Image](https://user-images.githubusercontent.com/110461050/189165898-851620c5-7c11-4626-8791-059ba83f9e39.png)
