### ISSUE TITLE
Find images in the collections by or about a concept

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5587]
### User stories

As a researcher
I want to see a selection of images by or a about a concept
So that I can decide if it is worth researching further

As a researcher
I want to search for all images by or about a concept
So that I can find other things that might be relevant to my research

### Measures

- Total item pages viewed
- Unique item pages viewed

### Acceptance criteria

- Concept pages include a list of images by or about that concept
- Image list links to filtered image search that return all relevant images
- Image list items deep link to the image

**Comment by rcantin-w** [comment]
First [integration was done](https://github.com/wellcomecollection/wellcomecollection.org/pull/8283) but we're taking a step back and seeing if we can make the justified grid happen, so needs #5589 to be done first.

**Comment by rcantin-w** [comment]
A question that was raised;  Do we want the image grid in Concepts to open modal boxes like it does in image search, or should it behave differently?

cc @jtweed @GarethOrmerod

**Comment by jtweed** [comment]
That is an interesting question, which is think is best answered by thinking about the broader issues that we currently have around image context and also the other places that we use the same kind of image grid.

I think the risk to not displaying the modal is that researchers would have no context as to what the image is, even after clicking on it. That's the major driver for changing how the viewer is included on works pages, but even then there's an argument that you should have more context before clicking through.

I think given that current low-context state of the image result -> item -> work journey and for consistency with other uses of the component (ie search), that we should at least start with it opening the modal and then iterate from there as we improve the broader image search journey.
