### ISSUE TITLE
Increase number of search results to 25

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5593]
Looks like we had a regression on the number of search results returned, from 25 back to the default 10.

Let's change back to 25 for both works and image search, then we can look at increasing image search further when we have a justified grid.

Relevant Slack thread:

https://wellcome.slack.com/archives/C8X9YKM5X/p1660899338245379

**Comment by alexwlchan** [comment]
I introduced this regression; I'll fix it.
