### ISSUE TITLE
Point libsys external DNS to III hosted Sierra

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5594]
### Background

Sierra is being migrated from on-premises to hosting from III. This is happening on Tuesday 30th August. I have confirmed that there will be no IP whitelisting for the REST API and so the only change we need to make is to point the external DNS for libsys.wellcomelibrary.org to the new hosted server from III.

### Details

- This should not be done until we have had the notification from LSS that the migration has started.
- External DNS for libsys.wellcomelibrary.org should CNAME to welli.iii.com
- Once Sierra is back up, we should check the adapter is working. This will likely be the next working day due to time zone differences.

**Comment by alexwlchan** [comment]
Done, and tested as working. 💪
