### ISSUE TITLE
Test new colour palette under a toggle

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/platform#5595]
Based on [this conversation](https://wellcome.slack.com/archives/C3TQSF63C/p1660841958122929), we want to try replacing existing colours with the tones from the new one. The accents that don't currently make up part of our palette will have to be tested differently, but in the meantime we could explore the possibility of already using new tones. E.g. the greens are similar, could we just go ahead with those?

[New palette here](https://www.sketch.com/s/ed142de8-6268-4e7f-bb19-b93b834af421/a/rb84njE#Inspect)

Will hide it behind a toggle so the website as a whole can be explored.

**Comment by rcantin-w** [comment]
@GarethOrmerod currently the red and green have a darker shade, I believe it's for hover behaviour. Would you still want specific ones?

**Comment by rcantin-w** [comment]
This was deployed and is ready for QA-ing/adjustments.

**Comment by GarethOrmerod** [comment]
Collections Activities section title to be #fff

https://wellcomecollection.org/collections

![Image](https://user-images.githubusercontent.com/36885440/189135256-d82426b4-2802-4690-99b3-243c318db53b.png)

**Comment by GarethOrmerod** [comment]
It might be worth considering removing the green element from this kind of text link in order to keep them compatible with any future colours they could appear with. 

![Image](https://user-images.githubusercontent.com/36885440/189136444-fc841448-6069-4cfa-893d-0b17f9ac9d48.png)

**Comment by rcantin-w** [comment]
@GarethOrmerod as discussed I created [a ticket](https://github.com/wellcomecollection/wellcomecollection.org/issues/8444) for that last comment.
