### ISSUE TITLE
Upgrade our ElastiCache instances

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5599]
Quoting an email from AWS:

<blockquote>
You are receiving this message because you have one or more Amazon ElastiCache for Redis clusters running version 3.x.x in the EU-WEST-1 Region.

ElastiCache for Redis version 3, originally released in October 2017, will reach its End Of Life (EOL) on July 31, 2023. We are providing you this notice to give you sufficient time to upgrade your Redis cluster(s). We recommend that you upgrade your cache cluster(s) to the latest available ElastiCache for Redis version before July 31, 2023. At this time, the latest version is 6.2, and it contains features including: JSON support, Redis Streams, performance improvements (including Enhanced IO), and data tiering as well as a various security and reliability updates.

You can initiate the upgrade of your cluster(s) immediately using the AWS Console, CLI or API. The upgrade process is fully managed and will upgrade each Redis node in the cluster to the new version. Depending on the cluster configuration, the upgrade process may lead to brief interruptions to application availability. Prior to upgrading, we recommend taking a snapshot of your cluster [1] during a scheduled maintenance window. See the upgrade guide for more information [2]. While most applications will not require any modification because of this upgrade, we recommend you check the version behavior compatibility page [2] and test your application with the new version before upgrading. To learn more about upgrading ElastiCache for Redis major cluster versions, review the Upgrading Redis Versions page [3].

Amazon ElastiCache for Redis instances using Version 3:
archivematica
archivematica-staging

We want to make you aware of the following milestones associated with ElastiCache for Redis Versions 3.x.x that are reaching EOL:

* From July 31, 2022 until July 31, 2023 - You can initiate upgrades of ElastiCache for Redis Version 3 instances to Redis 6.2 or higher at any time [3].
* From May 1, 2023 - you cannot create new ElastiCache for Redis 3.x.x instances from the AWS Console.
* From July 31, 2023 - Redis Version 3 will not be available in the ElastiCache Console, CLI, API or CloudFormation. We will automatically upgrade all ElastiCache for Redis 3.x.x clusters to Redis 6.2 within the next maintenance window after July 31, 2023.

If you have any questions or concerns, please reach out to AWS Support [4].

[1] https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/backups-manual.html
[2] https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/VersionManagementConsiderations.html
[3] https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/VersionManagement.html
[4] https://aws.amazon.com/support
</blockquote>

**Comment by kenoir** [comment]
Closing as no longer applicable (we're past Redis v3).
