### ISSUE TITLE
Add additional publication fields for serials

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5600]
### Background

There are three additional publication fields that are missing from works pages, which are often used for journals and other periodical/serials. We should add these to make sure that our descriptions are complete and as useful as possible for these works.

### Fields

| MARC field | API property     | Label             |
| ---------- | ---------------- | ----------------- |
| 310        | currentFrequency | Current frequency |
| 321        | formerFrequency  | Former frequency  |
| 362        | designation      | Designation       |

### Example

An example with all three fields is b2304200x. Note that all three are potentially repeatable and so we may need to consider whether they should be lists.

### Acceptance criteria

- All fields added to works page between publication/creation and physical description
- All fields added to API docs with description of the field purpose

**Comment by alexwlchan** [comment]
I'm doing an initial investigation of the underlying data.

Some notes:

* There are lots of examples where the 310 field has been used for both current and former frequency (e.g. b1352375, b1316635, b1351506). We should talk to Collections Information to find out whether this is fixable in the data, or whether we need to work around it in the transformer.
* All three fields have examples of repeated entries, but it's not clear yet whether those are genuine repeats or misused fields (as in 310/321).

**Comment by alexwlchan** [comment]
I've popped an initial question in #collections-info in Slack about the use of 310 for both current and repeated frequency: https://wellcome.slack.com/archives/CGXDT2GSH/p1669114036934909

**Comment by alexwlchan** [comment]
I've had a look at the data, and I think we need lists for 321/362 – there's only a single instance of repetition in 310, and I think we could make that a list by collapsing into a single string:

```
  "b13120323": [
    {
      "marcTag": "310",
      "subfields": [
        {
          "content": "Frequency: Thrice yearly",
          "tag": "a"
        }
      ]
    },
    {
      "marcTag": "310",
      "subfields": [
        {
          "content": "Frequency (online): twice per year.",
          "tag": "a"
        }
      ]
    }
  ],
```

**Comment by pollecuttn** [comment]
@alexwlchan I noticed on e.g. https://wellcomecollection.org/works/a5bkgrpx (b13172748) that the headings can exist when there is no data:

**Current frequency**
Frequency: Monthly

**Former frequency**

**Designation**

For the above there is no 321 Former frequency nor 362 Designation in the MARC.

Should headings not be there if there is no associated info?

**Comment by pollecuttn** [comment]
Nic reports "also spotted that these fields are appearing in non MATYPE d (journals) records: https://wellcomecollection.org/works/kp76anhh"
https://wellcome.slack.com/archives/CGXDT2GSH/p1674063942075269?thread_ts=1669114036.934909&cid=CGXDT2GSH

**Comment by alexwlchan** [comment]
That fix is deployed; closing as done.
