### ISSUE TITLE
Add 520 subfield $c to description

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5601]
Some 520 fields from Sierra contain a subfield $c, which notes the source of the description (eg the publisher).

We should append this to `description` to ensure that it's not truncated.

Example:
https://wellcomecollection.org/works/fheczbpz
https://catalogue.wellcomelibrary.org/record=b3303885~S12

**Comment by alexwlchan** [comment]
I've got a transformer patch up, and I've found a list of all the affected IDs, so we can reindex just those without a full-on pipeline reindex: [520_subfield_c.txt](https://github.com/wellcomecollection/platform/files/9575373/520_subfield_c.txt)

**Comment by alexwlchan** [comment]
I've kicked off a reindex for the affected records.

**Comment by alexwlchan** [comment]
This should be backfilled on existing records, e.g. the example in the original ticket now has "Provided by publisher" from 520 subfield $c.

I’m going to close this as done; if we want to tweak it later we can create new tickets.
