### ISSUE TITLE
Add additional notes fields for serials

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5602]
### Background

There are a number of note fields that are missing from works pages, which are often used for journals and other periodical/serials. We should add these to make sure that our descriptions are complete and as useful as possible for these works.

### Fields

| MARC field | Note type | Label          |
| ---------- | --------- | -------------- |
| 515        | numbering | Numbering note |
| 525        | general   | Notes          |
| 550        | general   | Notes          |
| 580        | general   | Notes          |
| 588        | general   | Notes          |

### Acceptance criteria

- 515 notes appear on works pages as “Numbering note”.
- All other notes appear as part of general “Notes”.

**Comment by alexwlchan** [comment]
This should be done, although I don't have an example to hand; it's very sparsely populated in Sierra.

**Comment by pollecuttn** [comment]
e.g. https://wellcomecollection.org/works/ayn8y83u
from https://wellcome.slack.com/archives/C8X9YKM5X/p1653467032500059
