### ISSUE TITLE
Scalable born digital workflow

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5617]
## Initiative

Investigate Enduro\+a3m prototype with Artefactual

## Objective

Build the platform services to support born digital access

## Key results

- IIIF services support born digital access

- Better understanding of future direction for born digital workflow

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/15789458

**Comment by kenoir** [comment]
Closing as represented as part of other work: https://www.notion.so/wellcometrust/Archivematica-next-steps-f91856390fcc4ec69753bd3fcecabb63?pvs=4
