### ISSUE TITLE
Add 787 as a related material note

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5633]
## Background

MARC field 787 is used to describe related works:

https://www.loc.gov/marc/bibliographic/bd787.html

We have about 25,000 bibs that use this, eg b33039136.

![image](https://user-images.githubusercontent.com/42490/203403228-58c2b853-f4b8-416a-83c0-4641d78fe557.png)

We would also like to use 787 to link re-catalogued M images from Wellcome Images to the works that the images originally came from. On the Calm side, this already exists as a related material note. As part of this ticket, we will use 787 to link back from the Sierra side.

There is a test record for exploring ways of doing this, which is b11534370:

![image](https://user-images.githubusercontent.com/42490/203403550-793c96dd-4460-4a2c-b448-e7e779bb7668.png)

## Approach

* Add a related material note for each 787 on a bib
* Where subfield $w is a UkLW id, look up the corresponding platform id and link $t to the works page
* Where subfield $i contains HTML, ensures this renders on the works page

Note: it is possible that the M image example will change to be more structured and more similar to the other example. We should still push ahead with implementing the above to support existing usage and inform the M images conversation.

**Comment by alexwlchan** [comment]
> Where subfield $w is a UkLW id, look up the corresponding platform id and link $t to the works page

This is an interesting one, because we don't currently have a way to look up platform IDs at the transformer stage. Hmm.

**Comment by alexwlchan** [comment]
My inclination is to use (3), it's not a lot of logic to implement. I don't love it, but I think it's the simplest path forward.

**Comment by alexwlchan** [comment]
Having discussed this elsewhere, I think (2) is closer to an MVP-esque approach and establishes whether this is useful.

**Comment by alexwlchan** [comment]
This is now available online, for example b11534370: https://wellcomecollection.org/works/dweu2ycs
