### ISSUE TITLE
Consider treating certain character pairs as equivalent in catalogue search

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5672]
From Alex H:

I have a question about searches on the catalogue. Because of the way rare books are printed and catalogued, often a u will be a v or a W will be vv or j will be i. It is quite common on library catalogues that, when searching for titles, the search automatically includes this within the search e.g. if someone is searching for the title 'Institutio Astronomica', results will also include 'Institvtio Astronomica'. Is this something that can be implemented on the Wellcome catalogue? At the moment when searching for 'Institutio Astronomica', only 4 of the 18 results are copies held at Wellcome and does not include 3 of our items (along with their digitised Proquest versions) which can only be found by searching 'Institvtio Astronomica'.

Institutio seqarch: https://wellcomecollection.org/search/works?query=institutio+astronomica
Institvtio search: https://wellcomecollection.org/search/works?query=institvtio+astronomica (edited)

Slack thread:

https://wellcome.slack.com/archives/C8X9YKM5X/p1679309592820029

**Comment by alexwlchan** [comment]
@harrisonpim is there something to be reviewed for this?
