### ISSUE TITLE
Sitewide search from the identity app (account pages) seems to be broken

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#5673]
### What
From [Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1680090933375599):

Sitewide search from the identity app (account pages) seems to be broken for me; I get sent to a 404 on https://wellcomecollection.org/account/search?query=Not+working

### To do
- [ ] Get search working on account pages

**Comment by alexwlchan** [comment]
When you're logged into your account (https://wellcomecollection.org/account), sitewide search from the global navigation should behave as if you're on any other page – e.g. typing "venice" into the search bar and running a search should take you to https://wellcomecollection.org/search?query=venice, not https://wellcomecollection.org/account/search?query=venice

Does that make sense?
