### ISSUE TITLE
Rank testing

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5680]
## Initiative

Rebuild the tooling for rank testing to make it easier to iterate on search relevance

## Objective

Increase findability across our collections and stories

## Key results

- Increase the number of relevance tests

- Increase conversion for broad searches

- Increase conversion for no results

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/19421778

**Comment by kenoir** [comment]
Closing as no longer valid.
