### ISSUE TITLE
What's up with the digital@wc.org account?

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5707]

**Comment by pollecuttn** [comment]
Prompt: an email from Google 4/7/23 re the phone number as the recovery number for this Google account makes me wonder:
- what do we use this Google account for?
- do we still need it?

**Comment by jennpb** [comment]
I can confirm it is **not used** in Google Analytics ✅

**Comment by pollecuttn** [comment]
20/7/23 NP messaged the number to try to find out what the Google account is used for.

**Comment by pollecuttn** [comment]
4/8/23 Password changed. Myself and Alex checked the account - it's not being used for anything. Tried deleting the account but couldn't as a verification code will be send to the existing phone number when:
- trying to delete the account
- trying to change the phone number on the account
- trying to switch of 2FA on the account

I have asked the phone number holder to either delete the account or switch off 2FA so I can login and delete it.

**Comment by pollecuttn** [comment]
4/8/23 Google confirmed this account is now deleted.
