### ISSUE TITLE
Reshow information from order records on /works pages

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/platform#5709]
Question from Nic:

> More a question than asking for a resolution, but did we used to have a bit of hardcoded text for users in records that hadn't yet been catalogued?
> So, before a record has arrived I would expect to see something like "this has been ordered" - record example: https://wellcomecollection.org/works/bhghjsmh
> And for when something's orders and arrived/awaiting cataloguing, I would expect to see something like "this is awaiting cataloguing" (old wording was like "being processed for" I think) - record example: https://wellcomecollection.org/works/a738kdjz
> I just can't remember if this existed and isn't there anymore, or... didn't exist on [WC.org](http://wc.org/).

https://wellcome.slack.com/archives/C8X9YKM5X/p1689947904107639

Jonathan confirms we have displayed information from order records previously.

## TODO
- [ ] Redisplay the information from order records

**Comment by alexwlchan** [comment]
It looks like something has broken, possibly in the order linker. This is the rough architecture:

```mermaid
graph LR
  S[(Sierra)] --> R[orders reader]
  R --> L[orders linker]
```

It looks like the reader picks up the modified record correctly, but then the linker marks the bib ID as "unlinked". I'm not sure why yet, probably the changes to the way the reader sends record after the big refactor?

**Comment by alexwlchan** [comment]
No, the reader had a bug – it wasn't extracting the list of linked bib numbers from the original Sierra record correctly.

**Comment by alexwlchan** [comment]
Fixed!
