### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5711]
## Initiative

Provide better guidance and possible alternate searches to users who get no results

## Objective

Increase findability across our collections and stories

## Key results

- Increase the number of relevance tests

- Increase conversion for broad searches

- Increase conversion for no results

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4910547

**Comment by kenoir** [comment]
Closing as no longer valid.
