### ISSUE TITLE
EBSCO resources

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/platform#5712]
## Initiative

Scope the ingest of resources directly from EBSCO, instead of via Sierra

## Objective

Increase findability across our collections and stories

## Key results

- Increase the number of relevance tests

- Increase conversion for broad searches

- Increase conversion for no results

**Comment by jtweed** [comment]
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/21688411

**Comment by alexwlchan** [comment]
Pasting some notes from Liz R about this project:

> There’s some good documentation here for HoldingsIQ (< https://developer.ebsco.com/knowledge-services/holdingsiq>). This works with EDS, FOLIO ERM and with other applications. If you need assistance, we have EBSCO Professional Services we can bring in to support.

**Comment by kenoir** [comment]
Closing as dupe of https://github.com/wellcomecollection/platform/issues/5738.
