### ISSUE TITLE
Update our Amazon RDS and Amazon Aurora SSL/TLS Certificates by August 22, 2024

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5721]
We've had some emails from AWS:

> You are receiving this message because your AWS Account has one or more Amazon RDS, or Amazon Aurora database instances in the EU-WEST-1 Region using an SSL/TLS Certificate that is expiring on August 22, 2024. 
>
> If your applications connect to these instances using the Secure Sockets Layer (SSL) or Transport Layer Security (TLS) protocol, you will need to take action before August 22, 2024 to prevent connectivity failures to your existing database instances.
>
> To protect your communications with your database instances, a Certificate Authority (CA) generates time-bound certificates that are checked by your database client software to authenticate any database instance before exchanging information. Following industry best practices, AWS renews the CA and creates new certificates on a routine basis to ensure customer connections are properly protected for years to come. The current CA in EU-WEST-1 will expire on August 22, 2024. Before this date you will need to first add new CA certificates to the trust stores in your client applications and then update the certificates on your database instances to the latest issued version.
>
> For detailed instructions on how to perform these updates please see the Amazon RDS instances [1] and Amazon Aurora instances [2] documentation.
>
> The ca-certificate-identifier option on the create-db-instance API is available for you to create a DB instance with a specific CA. For more information, see the create-db-instance API documentation [3].
>
> A modify-certificates API is also available that will allow you to temporarily override the default CA on newly created database instances to either the old or new CA. This override will only apply while the CA you are overriding to is valid. To use this API you will need to be running the AWS CLI version 1.17 or later. For more information see the modify-certificates API documentation [4].
>
> If you have questions or concerns, please contact AWS Support [5].
>
> [1] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html
> [2] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.SSL-certificate-rotation.html
> [3] https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html
> [4] https://docs.aws.amazon.com/cli/latest/reference/rds/modify-certificates.html
> [5] https://signin.aws.amazon.com/signin?redirect_uri=https%3A%2F%2Fsupport.console.aws.amazon.com%2Fsupport%2Fhome%3FhashArgs%3D%2523%26isauthcode%3Dtrue%26state%3DhashArgsFromTB_us-east-1_ca34fa00d6ce2ca2&client_id=arn%3Aaws%3Asignin%3A%3A%3Aconsole%2Fsupportcenter&forceMobileApp=0&code_challenge=F8z9D__b6vKi2hi8xZfAKHCqg-CI4qNw16dnqyOa7mU&code_challenge_method=SHA-256

They've given us a helpful list of affected databases:

> arn:aws:rds:eu-west-1:760097843905:db:tei-adapter-cluster-0
> arn:aws:rds:eu-west-1:760097843905:db:identifiers-delta-cluster-0
> arn:aws:rds:eu-west-1:299497370133:db:goobi-stage-aurora3-0
> arn:aws:rds:eu-west-1:299497370133:db:archivematica-instance-0
> arn:aws:rds:eu-west-1:299497370133:db:goobi-aurora3-0
> arn:aws:rds:eu-west-1:299497370133:db:archivematica-staging-instance-0
> arn:aws:rds:eu-west-1:299497370133:db:goobi-aurora3-1
> arn:aws:rds:eu-west-1:299497370133:db:goobi-stage-aurora3-1

**Comment by kenoir** [comment]
Closing as done, i've upgraded the certs for existing dbs (goobi looks like it no longer has this issue) - we do not use SSL/TLS connections at present so this should not be impactful.

See: https://wellcome.slack.com/archives/C02ANCYL90E/p1718097551814239
