### ISSUE TITLE
Investigate the spiky bill in the PutLogsEvent API

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5729]
We had a big bill last month for the PutLogEvents API.

Looking at the number of bytes written through the PutLogs API, it seems like the [elasticsearch-log-forwarder Lambda](https://github.com/wellcomecollection/elasticsearch-log-forwarder) is the culprit (see the yellow line in the graph):

![Screenshot 2023-09-12 at 11 59 48](https://github.com/wellcomecollection/platform/assets/301220/ce1a507b-0e05-4b62-a90f-1a82c134425e)

Looking in the logs for the Lambda, these seem to be caused by large log events being written, e.g. this one which is a single log that is 262KB:

[elasticsearch-log-forwarder.json.zip](https://github.com/wellcomecollection/platform/files/12586705/elasticsearch-log-forwarder.json.zip)

You can find these logs in the CloudWatch console here: https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Felasticsearch-log-forwarder/log-events/2023$252F09$252F05$252F$255B$2524LATEST$255D50d8b4f366a841f49885328dcf5452cd$3Fstart$3D1693919052000$26refEventId$3D37775657169714182808655433480461926647084831561724919809$26end$3D1694005992000

**Comment by kenoir** [comment]
Closing as lost context.
