### ISSUE TITLE
Analyse the contents of the libfs02-wellcome-it-com and libfs04-wellcome-it-com buckets

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#5733]
There are two S3 buckets in the NCW Prod account which were created several years ago as backups of on-premise file shares used by Wellcome Collection (last upload August 2019):

* `libfs02-wellcome-it-com` (~30TB)
* `libfs04-wellcome-it-com` (120.5GB, 145k objects)

Based on an initial analysis, the last time we uploaded anything to these buckets was in August 2019.

Kate W has asked whether we still need these buckets, or whether their contents has now been mirrored to our AWS setup and these backups can be safely deleted. I've done some quick analysis of the buckets, and I think it's fine, but I'd like somebody else to double check my working before I give the all-clear.

**Comment by alexwlchan** [comment]
## What I've learnt so far

If you want to get access to these buckets, you need to raise a ticket with D&T

[s3://wellcomecollection-assets-workingstorage/issue5733/](https://eu-west-1.console.aws.amazon.com/s3/buckets/wellcomecollection-assets-workingstorage?region=eu-west-1&prefix=issue5733/)

**Comment by alexwlchan** [comment]
I’ve run this past Ashley and the team; we’re happy to delete both of these.

I’m going to leave this ticket open until Kate confirms the buckets are gone, so we don’t lose it.

**Comment by pollecuttn** [comment]
5/10/2023 NP followed up with Kate.

**Comment by pollecuttn** [comment]
5/10/2023 confirmed deleted by Kate
