### ISSUE TITLE
Future collections management systems scoping

### ISSUE THREAD

**Issue by jcateswellcome** [wellcomecollection/platform#5745]
https://www.notion.so/wellcometrust/Future-collections-management-systems-scoping-80a72d2d6afd4995932ff8ea00cc468b?pvs=4

**Comment by jcateswellcome** [comment]
For Q1 24/25 use the focus will be to review CMS/LMS in the running from an integration perspective

**Comment by kenoir** [comment]
Dupe of https://github.com/wellcomecollection/platform/issues/5786
