### ISSUE TITLE
Enable off-site item requesting

### ISSUE THREAD

**Issue by jcateswellcome** [wellcomecollection/platform#5751]
To improve the end-to-end procedure, including allowing readers to request off-site, materials directly from the website. This will provide foundational capability that should support more complex inventory management and circulation policies in the future.

Link to Notion: https://www.notion.so/wellcometrust/Enable-off-site-item-requesting-f6ab9f0903d84623a6da6d168017ec51?pvs=4

**Comment by kenoir** [comment]
Link https://github.com/wellcomecollection/catalogue-pipeline/pull/2669
