### ISSUE TITLE
Metadata visibility: Ownership and custodial history [MARC 561] - discovery

### ISSUE THREAD

**Issue by jcateswellcome** [wellcomecollection/platform#5758]
### Background

Currently the data element 'ownership and custodial history' is not displaying on the works page for records from Sierra.

This is [MARC element 561](https://www.loc.gov/marc/bibliographic/bd561.html)

Given the nature of the collection, there are a range of 

Sample record: https://wellcomecollection.org/works/yw9umag7 does not contain much information, whereas the 561 contains a great deal of information relating to the history of the item as can be [seen in the reporting cluster](https://reporting.wellcomecollection.org/s/sierra/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-15m,to:now))&_a=(columns:!(),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,field:parent.id,index:d5ea4b8c-f58d-409c-8fb7-8a9973ea67f7,key:parent.id,negate:!f,params:(query:'3338926'),type:phrase),query:(match_phrase:(parent.id:'3338926')))),index:d5ea4b8c-f58d-409c-8fb7-8a9973ea67f7,interval:auto,query:(language:kuery,query:'varField.marcTag%20:%22561%22%20'),sort:!())) 

Consider how this transformation could be accommodated in the work model, for example can we map it as with archival collections which show an 'ownership note'.

This should be approached collaboratively, i.e. with collections information. This will help us better understand the user need and rationale for accessing this.

Part of: #5757

**Comment by kenoir** [comment]
Some notes from reviewing the conversation so far:

**Relevant MARC fields:**

- 561 - Ownership & Custodial History
  https://www.loc.gov/marc/bibliographic/bd561.html
- 541 - Immediate Source of Acquisition Note
  https://loc.gov/marc/bibliographic/bd541.html
- 591 - Local Notes (used to records some ownership information)
  https://www.loc.gov/marc/bibliographic/bd59x.html
  [Victoria Webb:](https://wellcome.slack.com/archives/CGXDT2GSH/p1723807806851519?thread_ts=1723802773.006609&cid=CGXDT2GSH) "As for the 591, it contains acquisitions info, but also a mix of other data. The data really isn't consistent, I think it would be worth CI spending some time sorting it & moving it to appropriate standard MARC fields where possible such as 561 & 541 …”

**Questions:**

561 is missing here:
https://wellcomecollection.org/works/yw9umag7
https://wellcomecollection.org/works/dwg8xwrc
_Why?_

561 does appear here:
https://wellcomecollection.org/works/u4hc2hwe
_Why?_

**Some terms of interest:**

MEI: Material Evidence in Incunabula
https://www.cerl.org/resources/mei/main
Incunabula: an early printed book, especially one printed before 1501.
https://en.wikipedia.org/wiki/Incunable

**Comment by kenoir** [comment]
To answer:

> 561 is mentioned in the catalogue pipeline:
> https://github.com/search?q=repo%3Awellcomecollection%2Fcatalogue-pipeline+561+language%3AScala&type=code&l=Scala
> How does this result in 561 appearing on works?

Of the 3 relevant MARC fields mentioned by Collection Information, we only appear to extract information from MARC 561 and then only in specific circumstance. The logic for this is contained in the `MarcNotes` class, [here](https://github.com/wellcomecollection/catalogue-pipeline/blob/main/pipeline/transformer/transformer_marc_common/src/main/scala/weco/pipeline/transformer/marc_common/transformers/MarcNotes.scala#L76).

There is a helpful comment indicating:

```scala
  /** Conditionally create an Ownership note, depending on the privacy of the
    * original note.
    *
    * A note is only created if it is explicitly marked as "Not Private" by
    * setting first indicator to 1
    *
    * https://www.loc.gov/marc/bibliographic/bd561.html
    */
```

`Notes` are added as a top level attribute of a work and can be of a constrained variety of types [listed here](https://github.com/wellcomecollection/catalogue-pipeline/blob/main/common/internal_model/src/main/scala/weco/catalogue/internal_model/work/Note.scala#L3), e.g. "binding-detail", "exhibitions-note" & "ownership-note". 

wellcomecollection.org will render there with labels provided by the catalogue API, see this example.
<img width="600" alt="Screenshot 2024-09-02 at 14 23 25" src="https://github.com/user-attachments/assets/a4d2492f-1ce9-4217-8eac-40446aa61c5e">
wellcomecollection.org: https://wellcomecollection.org/works/u4hc2hwe
<img width="600" alt="Screenshot 2024-09-02 at 14 23 44" src="https://github.com/user-attachments/assets/e0f82f5e-eb21-4e20-a316-a32ba1e3a17d">
API: https://api.wellcomecollection.org/catalogue/v2/works/u4hc2hwe?include=notes

**Comment by kenoir** [comment]
Some further questions to answer using the Sierra data available:

- How many bib records have 561 fields with contents (and are there any patterns in the contents)?
- Of the bib records with 561 fields, how often is the first indicator set to 1 i.e. explicitly marked "not private".

**Comment by kenoir** [comment]
Questions relating to the 541 field:

- How many bib records have 541 fields with contents (and are there any patterns in the contents)?
- Of the bib records with 541 fields, how often is the first indicator set to 1 i.e. explicitly marked "not private".
- How many bib records with 541 fields also have 561 fields?

**Comment by kenoir** [comment]
> How many bib records have 541 fields with contents?

[varField.marcTag : 541 AND parent.recordType : "bibs" [23718]](https://reporting.wellcomecollection.org/s/sierra/app/r/s/W7Xh1)

These breakdown like this:

<img width="1128" alt="Screenshot 2024-09-02 at 15 12 20" src="https://github.com/user-attachments/assets/5bddda39-7c81-4411-aac2-d47146a3f5b9">
https://reporting.wellcomecollection.org/s/sierra/app/r/s/TKTzT

> Of the bib records with 541 fields, how often is the first indicator set to 1 i.e. explicitly marked "not private".

[varField.marcTag : 541 AND parent.recordType : "bibs" and varField.ind1 : "1" [586]](https://reporting.wellcomecollection.org/s/sierra/app/r/s/jXwDZ)

**Comment by kenoir** [comment]
> How many bib records have 591 fields with contents (and are there any patterns in the contents)?

[varField.marcTag : 591 AND parent.recordType : "bibs" [149114]](https://reporting.wellcomecollection.org/s/sierra/app/r/s/TBSpw)

These breakdown like this (this samples only 5000 records and this dataset is much larger):

<img width="1801" alt="Screenshot 2024-09-02 at 15 39 26" src="https://github.com/user-attachments/assets/0290d0dd-1bf6-4606-8e39-da8cb9dd5389">

> Can we tell if the data in 591 fields should be private?

I can't! But #collections-info may be able to help work this out ... none of these fields have a value for indicator 1, but as this is [a locally defined field](https://www.oclc.org/bibformats/en/5xx/591.html) perhaps there is a Wellcome Collection standard for understanding privacy here? Otherwise we can inspect the 591 data for patterns that we think match private data?

**Comment by kenoir** [comment]
To summarise for now:

- We only take ownership data from bib records.
- We do not use data in the 541 field, but it does have a privacy indicator helping us to decide whether to use it. 
- We do not use the data in the 591 field, there are a significant number of records with this field, but it does not have a privacy indicator.
- The breakdown above for 591, 541 takes the values of all the subfields so we could do more work to understand where transforming data onto a work would be useful.

This is about as far as I can get using the reporting cluster data.

**Comment by kenoir** [comment]
Slack thread with more context: https://wellcome.slack.com/archives/CGXDT2GSH/p1723802773006609

**Comment by kenoir** [comment]
Closing this as discovery complete. We'll meet with Collections Info in early October to discuss implementation.
