### ISSUE TITLE
Decide how to handle restricted audio/video items on the work page

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/platform#5763]
Relates to #5762

For most works we provide a link to the item page to view the material. However, for audio and video items we display them on the work page.

If these items are restricted we don't show them, however, we will want to show them if a staff member is logged in and has the necessary permissions.

This would mean doing something similar to #5761, on the work page (but only for audio/video items)

OR **should we make the items page capable of displaying audio and video (and pdfs)**, remove the audio and video from the work page and always link to the item page.

This would make any further work around restricted items unnecessary.

There are also other reasons to do this:
- https://github.com/wellcomecollection/wellcomecollection.org/issues/9423
-  Would make the code much simpler and more maintainable
- If we wanted to link to the viewer for born digital items which we can display. These can be a mix of file types such as images, audio and video so we would need to
- More consistent user experience

**Comment by LaurenFBaily** [comment]
Discussed as a team and agreed to move audio and video player into viewer as reasons stated above outweigh benefits of having one less click for the user to access the work.
