### ISSUE TITLE
Update the ID Minter databases following AWS warning

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5785]
We need to deal with this warning in AWS:

> [!Warning]
> You have 2 Aurora MySQL with a DB engine version that is reaching its end of standard support date. Upgrade this database to a higher DB engine version soon, or it will be auto-enrolled into RDS Extended Support. Additional charges might apply for Extended Support. We suggest that you upgrade your DB engine version to the default Aurora MySQL version 3 (with MySQL 8.0 compatibility) before October 31, 2024. 

It will involve understanding the impact of the change, and moving to use the updated database version, a reindex may be required as part of this work, if so we can address [this issue](https://wellcome.slack.com/archives/C3TQSF63C/p1726754483077479) as part of the change.

**Comment by pollecuttn** [comment]
Agreed to update on Monday 14 October
