### ISSUE TITLE
Complete ingesting corporate photography

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5790]
Follows https://github.com/wellcomecollection/storage-service/issues/1126.

- [x] https://github.com/wellcomecollection/editorial-photography-ingest/issues/27

**Comment by kenoir** [comment]
@paul-butcher to update with ~% completion.

**Comment by paul-butcher** [comment]
There are now 60 sub shoots left to process, then I can look again and see if there are any failures that need to be pushed through again.

**Comment by paul-butcher** [comment]
Ashley has confirmed that it's all there.
