### ISSUE TITLE
Make ingestor-images tests in Catalogue Pipeline more reliable

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5793]
The ingestor-images tests fail repeatedly requiring manual re-runs, we should fix this to avoid wasted time and effort.

See [this Slack thread](https://wellcome.slack.com/archives/C02ANCYL90E/p1725876247624819?thread_ts=1725874278.316549&cid=C02ANCYL90E) for more context.

**Comment by paul-butcher** [comment]
The pertinent bit:
```
[info] - does not delete a message from the queue if it fails processing it *** FAILED ***
[info]   The code passed to eventually never returned normally. Attempted 41 times over 5.1402864280000005 seconds. Last failure message: 1 did not equal 0 Expected http://sqs.localhost.localhost.localstack.cloud:4566/000000000000/YJmiQLMRlQ to have ApproximateNumberOfMessagesNotVisible == 0, got ApproximateNumberOfMessagesNotVisible == 1. (ImagesIngestorFeatureTest.scala:91)
[info] Run completed in 12 seconds, 891 milliseconds.
[info] Total number of tests run: 21
[info] Suites: completed 7, aborted 0
[info] Tests: succeeded 20, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	weco.pipeline.ingestor.images.ImagesIngestorFeatureTest
```

**Comment by paul-butcher** [comment]
This is the [assertQueueEmpty](https://github.com/wellcomecollection/scala-libs/blob/70d728f5a903bd9137faee75e8392f01c32c9fed/messaging/src/test/scala/weco/messaging/fixtures/SQS.scala#L207) check [here](https://github.com/wellcomecollection/catalogue-pipeline/blob/a0204f4fc9f7e18b3935af71c2b275475e58527f/pipeline/ingestor/ingestor_images/src/test/scala/weco/pipeline/ingestor/images/ImagesIngestorFeatureTest.scala#L92)

Why is it giving up after having `Attempted 41 times over 5.1402864280000005 seconds`, when the timeout is supposed to be 10 seconds?

**Comment by paul-butcher** [comment]
Not that it should matter, because visibility timeout is 1s.  I wonder if it's being retried?  Perhaps this relates to weirdness about when things are being pulled. Maybe it only gets round to pulling the message off the queue at 4.15s after the eventually loop is entered.

**Comment by paul-butcher** [comment]
It's certainly wasteful to keep checking it so frequently.  The first interval at least should be 1s, as we know it's not going to succeed until then.  After that, I suppose we could consider checking more frequently in order to pass as soon as the message dies, but I doubt it's worth the effort.

**Comment by paul-butcher** [comment]
Well. [That seems to have fixed it](https://buildkite.com/wellcomecollection/catalogue-pipeline/builds/9195).  I've run this build three times now, and it worked every time.  A bit of an anticlimax there.
