### ISSUE TITLE
Auth0 upgrade to Node 18

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5795]
See [this Slack thread.](https://wellcome.slack.com/archives/C02ANCYL90E/p1726219673985749)

We need to upgrade some code that runs in Auth0 to keep things working.

```
Action Required: Use the Node.js 18 runtime for Actions and other extensibility

What is changing?

Starting February 10th, 2025, the Node.js 12 and 16 extensibility runtimes will progressively become unavailable for use across your tenants. Once removed, all extensibility integrations such as Actions, Rules, Hooks, Custom Database Connections, and Custom Social Connections will be forced to run on Node 18. If your code is not fully compatible, error rates may increase.

Why are we making this change?

Long-term support (LTS) for Node.js 12 and 16 ended in 2023, which means the Node.js development team no longer back-ports critical security fixes to this version. Continuing to run with Node.js 12 or 16 could potentially expose your extensibility code to security vulnerabilities.

How are you affected?

Your tenants have access to one or more of the planned to be discontinued extensibility runtimes. Any extensibility integration configured to use a runtime other than Node 18, whether already existing or to be created, will be at risk of experiencing increased error rates if it is not fully compatible with the Node.js 18 runtime.

What action do you need to take?

Custom actions using a discontinued runtime must be upgraded individually to Node 18 by deploying a new version. If needed, you can revert to the version using the previous runtime. If all custom Actions in the tenant already use the Node 18 runtime, you must only ensure that custom actions created in the future also use a non-discontinued version.
```

**Comment by kenoir** [comment]
This change has been made see: https://wellcome.slack.com/archives/C02ANCYL90E/p1730798520322949

**Comment by rcantin-w** [comment]
@kenoir [The actions are running on Node16 still](https://manage.auth0.com/dashboard/eu/wellcomecollection/actions/library), is there anything more to change there?

**Comment by kenoir** [comment]
> @kenoir [The actions are running on Node16 still](https://manage.auth0.com/dashboard/eu/wellcomecollection/actions/library), is there anything more to change there?

Yes! Good catch.

Didn't notice they had a seperate runtime.

**Comment by rcantin-w** [comment]
I'm also surprised they're not upgrading to _more_ than 18, [since it's unmaintained/end of life from May 2025](https://github.com/nodejs/Release), guessing we might have to do this again before a year has passed!

Happy to assist if I can.

**Comment by kenoir** [comment]
See also https://wellcome.slack.com/archives/C02ANCYL90E/p1730882704383149?thread_ts=1730826209.249169&cid=C02ANCYL90E

**Comment by kenoir** [comment]
Closing as done.

**Comment by rcantin-w** [comment]
Documentation being written for it https://github.com/wellcomecollection/developer-handbook/pull/3/files
