### ISSUE TITLE
Review Axiell Collections CMS

### ISSUE THREAD

**Issue by jcateswellcome** [wellcomecollection/platform#5797]
Part of https://github.com/wellcomecollection/platform/issues/5786

In order to better understand potential suppliers for a CMS, we should look at possible suppliers with a view to understanding risks and opportunities in relation to integration with the catalogue pipeline.

Filling out this [Notion template](https://www.notion.so/wellcometrust/Axiell-Collections-platform-team-review-1266687658a1802da3c4ee3aa96ad35e).

RFI information [available here](https://wellcomecloud.sharepoint.com/:f:/r/sites/WCTProgram/Shared%20Documents/General/7.%20RFI?csf=1&web=1&e=biszEr).

**Comment by jcateswellcome** [comment]
Yes the above is basically it - The most pertinent information is contained in [this folder](https://wellcomecloud.sharepoint.com/:f:/r/sites/WCTProgram/Shared%20Documents/General/7.%20RFI/2_RFI%20Supplier%20Responses/CMS/[Axiell](https://wellcomecloud.sharepoint.com/:f:/r/sites/WCTProgram/Shared%20Documents/General/7.%20RFI/2_RFI%20Supplier%20Responses/CMS/Axiell?csf=1&web=1&e=mEFwqj)?csf=1&web=1&e=mEFwqj)
The spreadsheet questionnaire contains the responses to the scenarios we included in the RFI. The supplementary information has background stuff about the supplier. 
Beyond this it would be worth looking at whether there is any documentation online, whether there are any obvious/active developer user groups etc.
All of the above limited to a few hours of investigation.

**Comment by kenoir** [comment]
Had a look through the notion page. Looks like a decent overview given the available information.

**Comment by kenoir** [comment]
Closing as done here: https://www.notion.so/wellcometrust/Future-collections-management-systems-scoping-80a72d2d6afd4995932ff8ea00cc468b?p=1266687658a1802da3c4ee3aa96ad35e&pm=c
