### ISSUE TITLE
List all node projects in need of an upgrade

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5810]
Following sprint planning we discussed tracking all repositories in need of an upgrade, in order that we don't miss any!

This can be a spreadsheet of repositories that need updating.

List: [Upgrade Nodejs Q1 2024-2025](https://wellcomecloud-my.sharepoint.com/personal/a_garoux_wellcome_ac_uk/_layouts/15/doc.aspx?sourcedoc={6a7536d8-03ac-4fb1-b649-b5191fc8a017}&action=edit)

**Comment by agnesgaroux** [comment]
Github code search "node:1" and "nodejs1" 

platform-infra
- [ ] https://github.com/wellcomecollection/platform-infrastructure/blob/main/cloudfront/invalidation/lambda/Dockerfile
- [ ] https://github.com/wellcomecollection/platform-infrastructure/blob/main/cloudfront/invalidation/terraform/sns_lambda/main.tf
- [ ] https://github.com/wellcomecollection/platform-infrastructure/blob/main/cloudfront/iiif.wellcomecollection.org/terraform/lambda_dlcs_path_rewrite.tf
- [ ] https://github.com/wellcomecollection/platform-infrastructure/blob/main/cloudfront/api.wellcomecollection.org/send_slack_alert_for_5xx_errors.tf

elasticsearch-log-forwarder
- [ ] https://github.com/wellcomecollection/elasticsearch-log-forwarder/blob/main/Dockerfile
- [ ] https://github.com/wellcomecollection/elasticsearch-log-forwarder/blob/main/terraform/main.tf

identity
- [ ] https://github.com/wellcomecollection/identity/blob/main/universal_login/Dockerfile
- [ ] https://github.com/wellcomecollection/identity/blob/main/.buildkite/Dockerfile
- [ ] https://github.com/wellcomecollection/identity/blob/main/smoke_tests/Dockerfile
- [ ] https://github.com/wellcomecollection/identity/blob/main/infra/scoped/lambda.tf

other
- [ ] https://github.com/wellcomecollection/catalogue-api/blob/main/concepts/Dockerfile
- [ ] https://github.com/wellcomecollection/wellcomelibrary.org/blob/main/terraform/lambdas.tf
- [ ] https://github.com/wellcomecollection/terraform-aws-lambda/blob/main/example/main.tf
- [ ] https://github.com/wellcomecollection/search-logger/blob/main/terraform/lambda.tf
- [ ] https://github.com/wellcomecollection/wellcomecollection.org/blob/main/cache/send_slack_alert_for_5xx_errors.tf

**Comment by agnesgaroux** [comment]
I just remembered this that came very handy last year when we [upgraded all the python lambdas](https://github.com/wellcomecollection/platform/issues/5732)

https://github.com/wellcomecollection/aws-account-infrastructure/tree/main/scripts#running-a-script-across-every-aws-account

**Comment by agnesgaroux** [comment]
To find lambdas with runtimes < 20 in all accounts, copy this into the root of `aws-account-infrastructure`

```
from config import get_all_aws_accounts

def isEarlierThanNode20(runtimeString): 
    return int(''.join(filter(str.isdigit, runtimeString))) < 20

if __name__ == "__main__":
    for account_id, account_name, sess in get_all_aws_accounts():
        print(f"\n# {account_name} ({account_id})\n")

        lambda_client = sess.client("lambda")

        for page in lambda_client.get_paginator("list_functions").paginate():
            for function in page["Functions"]:
                runtime = function.get("Runtime")
                if runtime != None and runtime.startswith('nodejs') and isEarlierThanNode20(runtime):
                  print(function["FunctionName"])
                  print(runtime)
```

**Comment by agnesgaroux** [comment]
** workflow (299497370133) **


** digitisation (404315009621) **


** platform (760097843905) **

elasticsearch-log-forwarder
nodejs18.x
iiif-test-cloudfront_invalidation
nodejs12.x
api-prod-cloudfront_invalidation
nodejs12.x
iiif-prod-cloudfront_invalidation
nodejs12.x
api-stage-cloudfront_invalidation
nodejs12.x
iiif-stage-cloudfront_invalidation
nodejs12.x
example-lambda
nodejs16.x
iiif-stage-new-cloudfront_invalidation
nodejs12.x
send_slack_alert_for_5xx_errors
nodejs16.x

** catalogue (756629837203) **


** data (964279923020) **


** digirati (653428163053) **


** experience (130871440101) **

search_logger_kinesis_to_es_lambda
nodejs12.x

** identity (770700576653) **

identity-authorizer-prod
nodejs18.x
patron-deletion-tracker-prod
nodejs18.x
identity-authorizer-stage
nodejs18.x
patron-deletion-tracker-stage
nodejs18.x
identity-api-stage
nodejs18.x
identity-api-prod
nodejs18.x

** reporting (269807742353) **


** storage (975596993436) **


** microsites (782179017633) **

**Comment by agnesgaroux** [comment]
NOTE: The script above only lists lambdas in the `eu-west-1` region
Here are the `us-east-1` ones (add `region_name="us-east-1"` when creating the session in `scripts/config.py`)

** platform (760097843905) **

cf_edge_wellcome_library_catalogue_redirect
nodejs16.x
cf_edge_dlcs_path_rewrite
nodejs16.x
cf_edge_wellcome_library_archive_redirect
nodejs16.x
cf_edge_wellcome_library_encore_redirect
nodejs16.x
cf_edge_wellcome_library_passthru
nodejs16.x
cf_edge_wellcome_library_blog_redirect
nodejs16.x
cf_edge_wellcome_library_redirect
nodejs16.x

** experience (130871440101) **

wellcomeimages_edge_lambda_request
nodejs8.10
send_slack_alert_for_5xx_errors (not sure what this is doing in N.Virginia) 
nodejs16.x
