### ISSUE TITLE
Upgrade node projects in platform-infrastructure

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5837]
Part of https://github.com/wellcomecollection/platform/issues/5812

**Comment by agnesgaroux** [comment]
Updated https://wellcomecloud-my.sharepoint.com/:x:/r/personal/a_garoux_wellcome_ac_uk/_layouts/15/Doc.aspx?sourcedoc=%7B6a7536d8-03ac-4fb1-b649-b5191fc8a017%7D&action=edit&wdinitialsession=38d16521-404a-e4ab-92a2-e9df36d8e4c9&wdrldsc=7&wdrldc=1&wdrldr=UserInteraction%2CBootTimeMismatch
