### ISSUE TITLE
Artefactual onboarding

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#5839]
Provide access for:
- [X] AWS accounts, via Wellcome Cloud Account
- [X] Reporting Kibana
- [X] Logging Kibana
- [X] [GitHub Project board](https://github.com/orgs/wellcomecollection/projects/26)
- [x] Draft "technical design" guidelines see [this Slack thread](https://wellcome.slack.com/archives/C02ANCYL90E/p1733222722942849).

**Comment by kenoir** [comment]
Sent emails to Joel Simpson, Jay Bosse, Donald Bassey, Santi Collazo with login detail.

> For AWS access see: 
> 
> https://docs.wellcomecollection.org/aws-account-setup
> 
> Log in with wither "Azure" or "Wellcome Collection":
> 
> Our reporting Kibana: https://reporting.wellcomecollection.org/login?next=%2F 
> Our logging Kibana: https://logging.wellcomecollection.org/login?next=%2F
> 
> Information about our digital production workflow is available in the reporting Kibana, under "Storage Service".
> 
> Application logs for all services (including Archivematica) is available on the logging Kibana, for example see: 
> 
> https://logging.wellcomecollection.org/app/r/s/XC0Qa

**Comment by kenoir** [comment]
Some issues with the reporting & logging access, have raised a ticket with our cloud team (RITM0058416).

**Comment by dana-saur** [comment]
Done
