### ISSUE TITLE
Investigate returning URL templates in Location blocks

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform#865]
Where we return URLs for a IIIF image server response, we could make use of [URL Templates](https://en.wikipedia.org/wiki/URL_Template) to indicate that certain values are substitutable.

This would make it easier for clients to consume and vary image URLs.

This change would likely not replace definitive URLs to resources but be in addition to them.

**Comment by kenoir** [comment]
Pinging @jamesgorrie @jtweed

**Comment by alexwlchan** [comment]
We haven't looked at this in five years and it's been fine; closing for now. We can open a new ticket if we decide to revisit this idea.
